import {
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowUp,
  ArrowDownWideNarrow,
  ArrowUpNarrowWide,
  Copy,
  Share2,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  Globe,
  House,
  List,
  ListFilter,
  LoaderCircle,
  Luggage,
  Map as MapIcon,
  Eye,
  Palette,
  Pencil,
  Plus,
  ReceiptText,
  RotateCw,
  Search,
  Trash2,
  User,
  Users,
} from '@lucide/vue'

/** 按需导入 Lucide，尺寸、描边与颜色由 ActionIcon 统一提供。 */
export const actionIcons = {
  archive: Archive,
  'archive-restore': ArchiveRestore,
  'sort-desc': ArrowDownWideNarrow,
  'sort-asc': ArrowUpNarrowWide,
  home: House,
  share: Share2,
  copy: Copy,
  edit: Pencil,
  eye: Eye,
  trash: Trash2,
  theme: Palette,
  refresh: RotateCw,
  search: Search,
  globe: Globe,
  receipt: ReceiptText,
  plus: Plus,
  map: MapIcon,
  list: List,
  filter: ListFilter,
  luggage: Luggage,
  loading: LoaderCircle,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-up': ChevronUp,
  user: User,
  users: Users,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
} as const

export type ActionIconName = keyof typeof actionIcons
