// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const accountExistsByEmailKey = `-- name: AccountExistsByEmailKey :one
SELECT EXISTS (SELECT 1 FROM accounts WHERE email_key = $1) AS exists
`

func (q *Queries) AccountExistsByEmailKey(ctx context.Context, emailKey string) (bool, error) {
	row := q.db.QueryRow(ctx, accountExistsByEmailKey, emailKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createAccount = `-- name: CreateAccount :one

INSERT INTO accounts (id, email, email_key, email_verified_at, password_hash, password_changed_at, nickname, default_timezone, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $4, $6, $7, $4, $4)
RETURNING id, email, email_key, email_verified_at, password_hash, password_changed_at, nickname, avatar_asset_id, default_timezone, status, version, created_at, updated_at
`

type CreateAccountParams struct {
	ID              uuid.UUID
	Email           string
	EmailKey        string
	EmailVerifiedAt time.Time
	PasswordHash    string
	Nickname        string
	DefaultTimezone string
}

// 账号基础查询。规范化邮箱 email_key 由服务端生成（去首尾空格、小写），不在 SQL 中处理。
// 时间一律由应用时钟给出（数据库时钟可能与应用不一致，会触发 updated_at >= created_at 约束）。
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.Email,
		arg.EmailKey,
		arg.EmailVerifiedAt,
		arg.PasswordHash,
		arg.Nickname,
		arg.DefaultTimezone,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailKey,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.Nickname,
		&i.AvatarAssetID,
		&i.DefaultTimezone,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAccountSyncState = `-- name: CreateAccountSyncState :exec
INSERT INTO account_sync_state (account_id)
VALUES ($1)
`

func (q *Queries) CreateAccountSyncState(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createAccountSyncState, accountID)
	return err
}

const getAccountByEmailKey = `-- name: GetAccountByEmailKey :one
SELECT id, email, email_key, email_verified_at, password_hash, password_changed_at, nickname, avatar_asset_id, default_timezone, status, version, created_at, updated_at FROM accounts
WHERE email_key = $1
`

func (q *Queries) GetAccountByEmailKey(ctx context.Context, emailKey string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByEmailKey, emailKey)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailKey,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.Nickname,
		&i.AvatarAssetID,
		&i.DefaultTimezone,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, email, email_key, email_verified_at, password_hash, password_changed_at, nickname, avatar_asset_id, default_timezone, status, version, created_at, updated_at FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailKey,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.Nickname,
		&i.AvatarAssetID,
		&i.DefaultTimezone,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountSyncState = `-- name: GetAccountSyncState :one
SELECT account_id, last_seq, retained_after_seq, updated_at FROM account_sync_state
WHERE account_id = $1
`

func (q *Queries) GetAccountSyncState(ctx context.Context, accountID uuid.UUID) (AccountSyncState, error) {
	row := q.db.QueryRow(ctx, getAccountSyncState, accountID)
	var i AccountSyncState
	err := row.Scan(
		&i.AccountID,
		&i.LastSeq,
		&i.RetainedAfterSeq,
		&i.UpdatedAt,
	)
	return i, err
}

const setAccountStatus = `-- name: SetAccountStatus :exec
UPDATE accounts
SET status = $2, version = version + 1, updated_at = $3
WHERE id = $1
`

type SetAccountStatusParams struct {
	ID        uuid.UUID
	Status    string
	UpdatedAt time.Time
}

func (q *Queries) SetAccountStatus(ctx context.Context, arg SetAccountStatusParams) error {
	_, err := q.db.Exec(ctx, setAccountStatus, arg.ID, arg.Status, arg.UpdatedAt)
	return err
}

const updateAccountPassword = `-- name: UpdateAccountPassword :exec
UPDATE accounts
SET password_hash = $2, password_changed_at = $3, updated_at = $3
WHERE id = $1
`

type UpdateAccountPasswordParams struct {
	ID                uuid.UUID
	PasswordHash      string
	PasswordChangedAt time.Time
}

func (q *Queries) UpdateAccountPassword(ctx context.Context, arg UpdateAccountPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAccountPassword, arg.ID, arg.PasswordHash, arg.PasswordChangedAt)
	return err
}

const updateAccountProfile = `-- name: UpdateAccountProfile :one
UPDATE accounts
SET nickname = $2, avatar_asset_id = $3, default_timezone = $4, version = version + 1, updated_at = $5
WHERE id = $1
RETURNING id, email, email_key, email_verified_at, password_hash, password_changed_at, nickname, avatar_asset_id, default_timezone, status, version, created_at, updated_at
`

type UpdateAccountProfileParams struct {
	ID              uuid.UUID
	Nickname        string
	AvatarAssetID   uuid.NullUUID
	DefaultTimezone string
	UpdatedAt       time.Time
}

func (q *Queries) UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountProfile,
		arg.ID,
		arg.Nickname,
		arg.AvatarAssetID,
		arg.DefaultTimezone,
		arg.UpdatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailKey,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.Nickname,
		&i.AvatarAssetID,
		&i.DefaultTimezone,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
