// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assetIDExists = `-- name: AssetIDExists :one
SELECT EXISTS (SELECT 1 FROM assets a WHERE a.id = $1)
    OR EXISTS (SELECT 1 FROM entity_tombstones et WHERE et.account_id = $2 AND et.entity_type = 'asset' AND et.entity_id = $1) AS exists
`

type AssetIDExistsParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) AssetIDExists(ctx context.Context, arg AssetIDExistsParams) (*bool, error) {
	row := q.db.QueryRow(ctx, assetIDExists, arg.ID, arg.AccountID)
	var exists *bool
	err := row.Scan(&exists)
	return exists, err
}

const getAsset = `-- name: GetAsset :one
SELECT id, account_id, version, created_at, updated_at, deleted_at, scope, trip_id, original_name, status, upload_attempt, staging_object_key, expected_size, declared_media_type, client_sha256, upload_expires_at, confirmed_at, media_type, byte_size, sha256, object_key, thumbnail_object_key, thumbnail_status, width, height, exif_taken_at_local, exif_latitude, exif_longitude, error_code, unreferenced_since FROM assets
WHERE account_id = $1 AND id = $2
`

type GetAssetParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetAsset(ctx context.Context, arg GetAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, arg.AccountID, arg.ID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Scope,
		&i.TripID,
		&i.OriginalName,
		&i.Status,
		&i.UploadAttempt,
		&i.StagingObjectKey,
		&i.ExpectedSize,
		&i.DeclaredMediaType,
		&i.ClientSha256,
		&i.UploadExpiresAt,
		&i.ConfirmedAt,
		&i.MediaType,
		&i.ByteSize,
		&i.Sha256,
		&i.ObjectKey,
		&i.ThumbnailObjectKey,
		&i.ThumbnailStatus,
		&i.Width,
		&i.Height,
		&i.ExifTakenAtLocal,
		&i.ExifLatitude,
		&i.ExifLongitude,
		&i.ErrorCode,
		&i.UnreferencedSince,
	)
	return i, err
}

const getAssetForUpdate = `-- name: GetAssetForUpdate :one
SELECT id, account_id, version, created_at, updated_at, deleted_at, scope, trip_id, original_name, status, upload_attempt, staging_object_key, expected_size, declared_media_type, client_sha256, upload_expires_at, confirmed_at, media_type, byte_size, sha256, object_key, thumbnail_object_key, thumbnail_status, width, height, exif_taken_at_local, exif_latitude, exif_longitude, error_code, unreferenced_since FROM assets
WHERE account_id = $1 AND id = $2
FOR UPDATE
`

type GetAssetForUpdateParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetAssetForUpdate(ctx context.Context, arg GetAssetForUpdateParams) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetForUpdate, arg.AccountID, arg.ID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Scope,
		&i.TripID,
		&i.OriginalName,
		&i.Status,
		&i.UploadAttempt,
		&i.StagingObjectKey,
		&i.ExpectedSize,
		&i.DeclaredMediaType,
		&i.ClientSha256,
		&i.UploadExpiresAt,
		&i.ConfirmedAt,
		&i.MediaType,
		&i.ByteSize,
		&i.Sha256,
		&i.ObjectKey,
		&i.ThumbnailObjectKey,
		&i.ThumbnailStatus,
		&i.Width,
		&i.Height,
		&i.ExifTakenAtLocal,
		&i.ExifLatitude,
		&i.ExifLongitude,
		&i.ErrorCode,
		&i.UnreferencedSince,
	)
	return i, err
}

const getAssetTripInfo = `-- name: GetAssetTripInfo :one

SELECT deleted_at FROM trips
WHERE account_id = $1 AND id = $2
`

type GetAssetTripInfoParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

// 私有文件资产（数据库设计表 14）。对象键由适配器按 account_id、asset_id、upload_attempt 推导后传入；
// 暂存键、最终键、缩略图键与声明信息不进入公开模型，由独立查询按需读取。
func (q *Queries) GetAssetTripInfo(ctx context.Context, arg GetAssetTripInfoParams) (*time.Time, error) {
	row := q.db.QueryRow(ctx, getAssetTripInfo, arg.AccountID, arg.ID)
	var deleted_at *time.Time
	err := row.Scan(&deleted_at)
	return deleted_at, err
}

const getAssetsByIDs = `-- name: GetAssetsByIDs :many
SELECT a.id, a.account_id, a.version, a.created_at, a.updated_at, a.deleted_at, a.scope, a.trip_id, a.original_name, a.status, a.upload_attempt, a.staging_object_key, a.expected_size, a.declared_media_type, a.client_sha256, a.upload_expires_at, a.confirmed_at, a.media_type, a.byte_size, a.sha256, a.object_key, a.thumbnail_object_key, a.thumbnail_status, a.width, a.height, a.exif_taken_at_local, a.exif_latitude, a.exif_longitude, a.error_code, a.unreferenced_since
FROM unnest($1::uuid[]) WITH ORDINALITY AS req(id, ord)
JOIN assets a ON a.id = req.id AND a.account_id = $2
ORDER BY req.ord
`

type GetAssetsByIDsParams struct {
	Ids       []uuid.UUID
	AccountID uuid.UUID
}

// 批量读取保持输入顺序：unnest WITH ORDINALITY 再按序号排序，适配器据此判断缺失项。
func (q *Queries) GetAssetsByIDs(ctx context.Context, arg GetAssetsByIDsParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, getAssetsByIDs, arg.Ids, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Scope,
			&i.TripID,
			&i.OriginalName,
			&i.Status,
			&i.UploadAttempt,
			&i.StagingObjectKey,
			&i.ExpectedSize,
			&i.DeclaredMediaType,
			&i.ClientSha256,
			&i.UploadExpiresAt,
			&i.ConfirmedAt,
			&i.MediaType,
			&i.ByteSize,
			&i.Sha256,
			&i.ObjectKey,
			&i.ThumbnailObjectKey,
			&i.ThumbnailStatus,
			&i.Width,
			&i.Height,
			&i.ExifTakenAtLocal,
			&i.ExifLatitude,
			&i.ExifLongitude,
			&i.ErrorCode,
			&i.UnreferencedSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAsset = `-- name: InsertAsset :one
INSERT INTO assets (
    id, account_id, version, created_at, updated_at, scope, trip_id, original_name,
    status, upload_attempt, staging_object_key, expected_size, declared_media_type, client_sha256,
    upload_expires_at, thumbnail_status
) VALUES (
    $1, $2, 1, $3, $3, $4, $5, $6,
    'uploading', 1, $7, $8, $9, $10,
    $11, 'none'
)
RETURNING id, account_id, version, created_at, updated_at, deleted_at, scope, trip_id, original_name, status, upload_attempt, staging_object_key, expected_size, declared_media_type, client_sha256, upload_expires_at, confirmed_at, media_type, byte_size, sha256, object_key, thumbnail_object_key, thumbnail_status, width, height, exif_taken_at_local, exif_latitude, exif_longitude, error_code, unreferenced_since
`

type InsertAssetParams struct {
	ID                uuid.UUID
	AccountID         uuid.UUID
	CreatedAt         time.Time
	Scope             string
	TripID            uuid.NullUUID
	OriginalName      string
	StagingObjectKey  *string
	ExpectedSize      *int64
	DeclaredMediaType *string
	ClientSha256      []byte
	UploadExpiresAt   *time.Time
}

func (q *Queries) InsertAsset(ctx context.Context, arg InsertAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, insertAsset,
		arg.ID,
		arg.AccountID,
		arg.CreatedAt,
		arg.Scope,
		arg.TripID,
		arg.OriginalName,
		arg.StagingObjectKey,
		arg.ExpectedSize,
		arg.DeclaredMediaType,
		arg.ClientSha256,
		arg.UploadExpiresAt,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Scope,
		&i.TripID,
		&i.OriginalName,
		&i.Status,
		&i.UploadAttempt,
		&i.StagingObjectKey,
		&i.ExpectedSize,
		&i.DeclaredMediaType,
		&i.ClientSha256,
		&i.UploadExpiresAt,
		&i.ConfirmedAt,
		&i.MediaType,
		&i.ByteSize,
		&i.Sha256,
		&i.ObjectKey,
		&i.ThumbnailObjectKey,
		&i.ThumbnailStatus,
		&i.Width,
		&i.Height,
		&i.ExifTakenAtLocal,
		&i.ExifLatitude,
		&i.ExifLongitude,
		&i.ErrorCode,
		&i.UnreferencedSince,
	)
	return i, err
}

const listTripAssets = `-- name: ListTripAssets :many
SELECT id, account_id, version, created_at, updated_at, deleted_at, scope, trip_id, original_name, status, upload_attempt, staging_object_key, expected_size, declared_media_type, client_sha256, upload_expires_at, confirmed_at, media_type, byte_size, sha256, object_key, thumbnail_object_key, thumbnail_status, width, height, exif_taken_at_local, exif_latitude, exif_longitude, error_code, unreferenced_since FROM assets a
WHERE a.account_id = $1 AND a.trip_id = $2 AND a.deleted_at IS NULL
  AND ($3::text IS NULL OR a.status = $3::text)
  AND (cardinality($4::uuid[]) = 0 OR a.id = ANY($4::uuid[]))
  AND ($5::timestamptz IS NULL
       OR (a.created_at, a.id) < ($5::timestamptz, $6::uuid))
ORDER BY a.created_at DESC, a.id DESC
LIMIT $7
`

type ListTripAssetsParams struct {
	AccountID       uuid.UUID
	TripID          uuid.NullUUID
	Status          *string
	Ids             []uuid.UUID
	CursorCreatedAt *time.Time
	CursorID        uuid.NullUUID
	RowLimit        int32
}

// 列表按 (created_at, id) 降序走部分索引 assets_trip_created_idx；ids 为空数组时不过滤。
func (q *Queries) ListTripAssets(ctx context.Context, arg ListTripAssetsParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listTripAssets,
		arg.AccountID,
		arg.TripID,
		arg.Status,
		arg.Ids,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Scope,
			&i.TripID,
			&i.OriginalName,
			&i.Status,
			&i.UploadAttempt,
			&i.StagingObjectKey,
			&i.ExpectedSize,
			&i.DeclaredMediaType,
			&i.ClientSha256,
			&i.UploadExpiresAt,
			&i.ConfirmedAt,
			&i.MediaType,
			&i.ByteSize,
			&i.Sha256,
			&i.ObjectKey,
			&i.ThumbnailObjectKey,
			&i.ThumbnailStatus,
			&i.Width,
			&i.Height,
			&i.ExifTakenAtLocal,
			&i.ExifLatitude,
			&i.ExifLongitude,
			&i.ErrorCode,
			&i.UnreferencedSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAssetFailed = `-- name: MarkAssetFailed :one
UPDATE assets
SET status = 'failed', error_code = $1, staging_object_key = NULL, upload_expires_at = NULL,
    version = version + 1, updated_at = $2
WHERE account_id = $3 AND id = $4
RETURNING id, account_id, version, created_at, updated_at, deleted_at, scope, trip_id, original_name, status, upload_attempt, staging_object_key, expected_size, declared_media_type, client_sha256, upload_expires_at, confirmed_at, media_type, byte_size, sha256, object_key, thumbnail_object_key, thumbnail_status, width, height, exif_taken_at_local, exif_latitude, exif_longitude, error_code, unreferenced_since
`

type MarkAssetFailedParams struct {
	ErrorCode *string
	UpdatedAt time.Time
	AccountID uuid.UUID
	ID        uuid.UUID
}

// 校验失败：记录可公开的错误码并清空暂存键，等待用户开启新尝试。
func (q *Queries) MarkAssetFailed(ctx context.Context, arg MarkAssetFailedParams) (Asset, error) {
	row := q.db.QueryRow(ctx, markAssetFailed,
		arg.ErrorCode,
		arg.UpdatedAt,
		arg.AccountID,
		arg.ID,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Scope,
		&i.TripID,
		&i.OriginalName,
		&i.Status,
		&i.UploadAttempt,
		&i.StagingObjectKey,
		&i.ExpectedSize,
		&i.DeclaredMediaType,
		&i.ClientSha256,
		&i.UploadExpiresAt,
		&i.ConfirmedAt,
		&i.MediaType,
		&i.ByteSize,
		&i.Sha256,
		&i.ObjectKey,
		&i.ThumbnailObjectKey,
		&i.ThumbnailStatus,
		&i.Width,
		&i.Height,
		&i.ExifTakenAtLocal,
		&i.ExifLatitude,
		&i.ExifLongitude,
		&i.ErrorCode,
		&i.UnreferencedSince,
	)
	return i, err
}

const markAssetProcessing = `-- name: MarkAssetProcessing :one
UPDATE assets
SET status = 'processing', confirmed_at = $1, upload_expires_at = NULL,
    version = version + 1, updated_at = $2
WHERE account_id = $3 AND id = $4
RETURNING id, account_id, version, created_at, updated_at, deleted_at, scope, trip_id, original_name, status, upload_attempt, staging_object_key, expected_size, declared_media_type, client_sha256, upload_expires_at, confirmed_at, media_type, byte_size, sha256, object_key, thumbnail_object_key, thumbnail_status, width, height, exif_taken_at_local, exif_latitude, exif_longitude, error_code, unreferenced_since
`

type MarkAssetProcessingParams struct {
	ConfirmedAt *time.Time
	UpdatedAt   time.Time
	AccountID   uuid.UUID
	ID          uuid.UUID
}

// 确认：转入 processing，不再有确认窗口；暂存键保留给 worker 读取。
func (q *Queries) MarkAssetProcessing(ctx context.Context, arg MarkAssetProcessingParams) (Asset, error) {
	row := q.db.QueryRow(ctx, markAssetProcessing,
		arg.ConfirmedAt,
		arg.UpdatedAt,
		arg.AccountID,
		arg.ID,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Scope,
		&i.TripID,
		&i.OriginalName,
		&i.Status,
		&i.UploadAttempt,
		&i.StagingObjectKey,
		&i.ExpectedSize,
		&i.DeclaredMediaType,
		&i.ClientSha256,
		&i.UploadExpiresAt,
		&i.ConfirmedAt,
		&i.MediaType,
		&i.ByteSize,
		&i.Sha256,
		&i.ObjectKey,
		&i.ThumbnailObjectKey,
		&i.ThumbnailStatus,
		&i.Width,
		&i.Height,
		&i.ExifTakenAtLocal,
		&i.ExifLatitude,
		&i.ExifLongitude,
		&i.ErrorCode,
		&i.UnreferencedSince,
	)
	return i, err
}

const markAssetReady = `-- name: MarkAssetReady :one
UPDATE assets
SET status = 'ready', object_key = $1, staging_object_key = NULL, upload_expires_at = NULL, error_code = NULL,
    media_type = $2, byte_size = $3, sha256 = $4,
    width = $5, height = $6,
    exif_taken_at_local = $7, exif_latitude = $8, exif_longitude = $9,
    thumbnail_status = $10,
    version = version + 1, updated_at = $11
WHERE account_id = $12 AND id = $13
RETURNING id, account_id, version, created_at, updated_at, deleted_at, scope, trip_id, original_name, status, upload_attempt, staging_object_key, expected_size, declared_media_type, client_sha256, upload_expires_at, confirmed_at, media_type, byte_size, sha256, object_key, thumbnail_object_key, thumbnail_status, width, height, exif_taken_at_local, exif_latitude, exif_longitude, error_code, unreferenced_since
`

type MarkAssetReadyParams struct {
	ObjectKey        *string
	MediaType        *string
	ByteSize         *int64
	Sha256           []byte
	Width            *int32
	Height           *int32
	ExifTakenAtLocal *time.Time
	ExifLatitude     *string
	ExifLongitude    *string
	ThumbnailStatus  string
	UpdatedAt        time.Time
	AccountID        uuid.UUID
	ID               uuid.UUID
}

// 校验通过：写入最终键与实际元数据，清空暂存键（ready 的 CHECK 要求）；缩略图状态由适配器按类型传入。
func (q *Queries) MarkAssetReady(ctx context.Context, arg MarkAssetReadyParams) (Asset, error) {
	row := q.db.QueryRow(ctx, markAssetReady,
		arg.ObjectKey,
		arg.MediaType,
		arg.ByteSize,
		arg.Sha256,
		arg.Width,
		arg.Height,
		arg.ExifTakenAtLocal,
		arg.ExifLatitude,
		arg.ExifLongitude,
		arg.ThumbnailStatus,
		arg.UpdatedAt,
		arg.AccountID,
		arg.ID,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Scope,
		&i.TripID,
		&i.OriginalName,
		&i.Status,
		&i.UploadAttempt,
		&i.StagingObjectKey,
		&i.ExpectedSize,
		&i.DeclaredMediaType,
		&i.ClientSha256,
		&i.UploadExpiresAt,
		&i.ConfirmedAt,
		&i.MediaType,
		&i.ByteSize,
		&i.Sha256,
		&i.ObjectKey,
		&i.ThumbnailObjectKey,
		&i.ThumbnailStatus,
		&i.Width,
		&i.Height,
		&i.ExifTakenAtLocal,
		&i.ExifLatitude,
		&i.ExifLongitude,
		&i.ErrorCode,
		&i.UnreferencedSince,
	)
	return i, err
}

const renewAssetAttempt = `-- name: RenewAssetAttempt :one
UPDATE assets
SET upload_expires_at = $1, version = version + 1, updated_at = $2
WHERE account_id = $3 AND id = $4
RETURNING id, account_id, version, created_at, updated_at, deleted_at, scope, trip_id, original_name, status, upload_attempt, staging_object_key, expected_size, declared_media_type, client_sha256, upload_expires_at, confirmed_at, media_type, byte_size, sha256, object_key, thumbnail_object_key, thumbnail_status, width, height, exif_taken_at_local, exif_latitude, exif_longitude, error_code, unreferenced_since
`

type RenewAssetAttemptParams struct {
	UploadExpiresAt *time.Time
	UpdatedAt       time.Time
	AccountID       uuid.UUID
	ID              uuid.UUID
}

// 续签：只延长当前尝试的截止时间，暂存键与序号不变。
func (q *Queries) RenewAssetAttempt(ctx context.Context, arg RenewAssetAttemptParams) (Asset, error) {
	row := q.db.QueryRow(ctx, renewAssetAttempt,
		arg.UploadExpiresAt,
		arg.UpdatedAt,
		arg.AccountID,
		arg.ID,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Scope,
		&i.TripID,
		&i.OriginalName,
		&i.Status,
		&i.UploadAttempt,
		&i.StagingObjectKey,
		&i.ExpectedSize,
		&i.DeclaredMediaType,
		&i.ClientSha256,
		&i.UploadExpiresAt,
		&i.ConfirmedAt,
		&i.MediaType,
		&i.ByteSize,
		&i.Sha256,
		&i.ObjectKey,
		&i.ThumbnailObjectKey,
		&i.ThumbnailStatus,
		&i.Width,
		&i.Height,
		&i.ExifTakenAtLocal,
		&i.ExifLatitude,
		&i.ExifLongitude,
		&i.ErrorCode,
		&i.UnreferencedSince,
	)
	return i, err
}

const setAssetThumbnail = `-- name: SetAssetThumbnail :one
UPDATE assets
SET thumbnail_status = $1, thumbnail_object_key = $2,
    version = version + 1, updated_at = $3
WHERE account_id = $4 AND id = $5
RETURNING id, account_id, version, created_at, updated_at, deleted_at, scope, trip_id, original_name, status, upload_attempt, staging_object_key, expected_size, declared_media_type, client_sha256, upload_expires_at, confirmed_at, media_type, byte_size, sha256, object_key, thumbnail_object_key, thumbnail_status, width, height, exif_taken_at_local, exif_latitude, exif_longitude, error_code, unreferenced_since
`

type SetAssetThumbnailParams struct {
	ThumbnailStatus    string
	ThumbnailObjectKey *string
	UpdatedAt          time.Time
	AccountID          uuid.UUID
	ID                 uuid.UUID
}

func (q *Queries) SetAssetThumbnail(ctx context.Context, arg SetAssetThumbnailParams) (Asset, error) {
	row := q.db.QueryRow(ctx, setAssetThumbnail,
		arg.ThumbnailStatus,
		arg.ThumbnailObjectKey,
		arg.UpdatedAt,
		arg.AccountID,
		arg.ID,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Scope,
		&i.TripID,
		&i.OriginalName,
		&i.Status,
		&i.UploadAttempt,
		&i.StagingObjectKey,
		&i.ExpectedSize,
		&i.DeclaredMediaType,
		&i.ClientSha256,
		&i.UploadExpiresAt,
		&i.ConfirmedAt,
		&i.MediaType,
		&i.ByteSize,
		&i.Sha256,
		&i.ObjectKey,
		&i.ThumbnailObjectKey,
		&i.ThumbnailStatus,
		&i.Width,
		&i.Height,
		&i.ExifTakenAtLocal,
		&i.ExifLatitude,
		&i.ExifLongitude,
		&i.ErrorCode,
		&i.UnreferencedSince,
	)
	return i, err
}

const startAssetAttempt = `-- name: StartAssetAttempt :one
UPDATE assets
SET status = 'uploading', upload_attempt = $1, staging_object_key = $2,
    upload_expires_at = $3, confirmed_at = NULL, error_code = NULL,
    version = version + 1, updated_at = $4
WHERE account_id = $5 AND id = $6
RETURNING id, account_id, version, created_at, updated_at, deleted_at, scope, trip_id, original_name, status, upload_attempt, staging_object_key, expected_size, declared_media_type, client_sha256, upload_expires_at, confirmed_at, media_type, byte_size, sha256, object_key, thumbnail_object_key, thumbnail_status, width, height, exif_taken_at_local, exif_latitude, exif_longitude, error_code, unreferenced_since
`

type StartAssetAttemptParams struct {
	UploadAttempt    int32
	StagingObjectKey *string
	UploadExpiresAt  *time.Time
	UpdatedAt        time.Time
	AccountID        uuid.UUID
	ID               uuid.UUID
}

// 新尝试：序号加 1、换暂存键与截止时间、回到 uploading 并清掉上次错误码；最终键留空由校验重写。
func (q *Queries) StartAssetAttempt(ctx context.Context, arg StartAssetAttemptParams) (Asset, error) {
	row := q.db.QueryRow(ctx, startAssetAttempt,
		arg.UploadAttempt,
		arg.StagingObjectKey,
		arg.UploadExpiresAt,
		arg.UpdatedAt,
		arg.AccountID,
		arg.ID,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Scope,
		&i.TripID,
		&i.OriginalName,
		&i.Status,
		&i.UploadAttempt,
		&i.StagingObjectKey,
		&i.ExpectedSize,
		&i.DeclaredMediaType,
		&i.ClientSha256,
		&i.UploadExpiresAt,
		&i.ConfirmedAt,
		&i.MediaType,
		&i.ByteSize,
		&i.Sha256,
		&i.ObjectKey,
		&i.ThumbnailObjectKey,
		&i.ThumbnailStatus,
		&i.Width,
		&i.Height,
		&i.ExifTakenAtLocal,
		&i.ExifLatitude,
		&i.ExifLongitude,
		&i.ErrorCode,
		&i.UnreferencedSince,
	)
	return i, err
}
