// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countExpenseCategories = `-- name: CountExpenseCategories :one
SELECT count(*) AS n FROM expense_categories
WHERE account_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountExpenseCategories(ctx context.Context, accountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countExpenseCategories, accountID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countLedgerEntriesUsingCategory = `-- name: CountLedgerEntriesUsingCategory :one
SELECT count(*) AS n FROM ledger_entries
WHERE account_id = $1 AND category_id = $2 AND deleted_at IS NULL
`

type CountLedgerEntriesUsingCategoryParams struct {
	AccountID  uuid.UUID
	CategoryID uuid.UUID
}

func (q *Queries) CountLedgerEntriesUsingCategory(ctx context.Context, arg CountLedgerEntriesUsingCategoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLedgerEntriesUsingCategory, arg.AccountID, arg.CategoryID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const expenseCategoryIDExists = `-- name: ExpenseCategoryIDExists :one
SELECT EXISTS (SELECT 1 FROM expense_categories WHERE id = $1) AS exists
`

func (q *Queries) ExpenseCategoryIDExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, expenseCategoryIDExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getExpenseCategory = `-- name: GetExpenseCategory :one
SELECT id, account_id, version, created_at, updated_at, deleted_at, name, icon, sort_order, is_preset FROM expense_categories
WHERE account_id = $1 AND id = $2
`

type GetExpenseCategoryParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetExpenseCategory(ctx context.Context, arg GetExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, getExpenseCategory, arg.AccountID, arg.ID)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Icon,
		&i.SortOrder,
		&i.IsPreset,
	)
	return i, err
}

const getExpenseCategoryForUpdate = `-- name: GetExpenseCategoryForUpdate :one
SELECT id, account_id, version, created_at, updated_at, deleted_at, name, icon, sort_order, is_preset FROM expense_categories
WHERE account_id = $1 AND id = $2
FOR UPDATE
`

type GetExpenseCategoryForUpdateParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetExpenseCategoryForUpdate(ctx context.Context, arg GetExpenseCategoryForUpdateParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, getExpenseCategoryForUpdate, arg.AccountID, arg.ID)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Icon,
		&i.SortOrder,
		&i.IsPreset,
	)
	return i, err
}

const insertExpenseCategory = `-- name: InsertExpenseCategory :one

INSERT INTO expense_categories (id, account_id, name, icon, sort_order, is_preset, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
RETURNING id, account_id, version, created_at, updated_at, deleted_at, name, icon, sort_order, is_preset
`

type InsertExpenseCategoryParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	Name      string
	Icon      *string
	SortOrder int32
	IsPreset  bool
	CreatedAt time.Time
}

// 账号级账单分类。
func (q *Queries) InsertExpenseCategory(ctx context.Context, arg InsertExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, insertExpenseCategory,
		arg.ID,
		arg.AccountID,
		arg.Name,
		arg.Icon,
		arg.SortOrder,
		arg.IsPreset,
		arg.CreatedAt,
	)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Icon,
		&i.SortOrder,
		&i.IsPreset,
	)
	return i, err
}

const listExpenseCategories = `-- name: ListExpenseCategories :many
SELECT id, account_id, version, created_at, updated_at, deleted_at, name, icon, sort_order, is_preset FROM expense_categories
WHERE account_id = $1 AND deleted_at IS NULL
ORDER BY sort_order, id
`

func (q *Queries) ListExpenseCategories(ctx context.Context, accountID uuid.UUID) ([]ExpenseCategory, error) {
	rows, err := q.db.Query(ctx, listExpenseCategories, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseCategory{}
	for rows.Next() {
		var i ExpenseCategory
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.Icon,
			&i.SortOrder,
			&i.IsPreset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxExpenseCategorySortOrder = `-- name: MaxExpenseCategorySortOrder :one
SELECT coalesce(max(sort_order), -1)::integer AS max_sort FROM expense_categories
WHERE account_id = $1 AND deleted_at IS NULL
`

func (q *Queries) MaxExpenseCategorySortOrder(ctx context.Context, accountID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, maxExpenseCategorySortOrder, accountID)
	var max_sort int32
	err := row.Scan(&max_sort)
	return max_sort, err
}

const softDeleteExpenseCategory = `-- name: SoftDeleteExpenseCategory :one
UPDATE expense_categories
SET deleted_at = $3, version = version + 1, updated_at = $3
WHERE account_id = $1 AND id = $2
RETURNING id, account_id, version, created_at, updated_at, deleted_at, name, icon, sort_order, is_preset
`

type SoftDeleteExpenseCategoryParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
	DeletedAt *time.Time
}

func (q *Queries) SoftDeleteExpenseCategory(ctx context.Context, arg SoftDeleteExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, softDeleteExpenseCategory, arg.AccountID, arg.ID, arg.DeletedAt)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Icon,
		&i.SortOrder,
		&i.IsPreset,
	)
	return i, err
}

const updateExpenseCategory = `-- name: UpdateExpenseCategory :one
UPDATE expense_categories
SET name = $3, icon = $4, sort_order = $5, version = version + 1, updated_at = $6
WHERE account_id = $1 AND id = $2
RETURNING id, account_id, version, created_at, updated_at, deleted_at, name, icon, sort_order, is_preset
`

type UpdateExpenseCategoryParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
	Name      string
	Icon      *string
	SortOrder int32
	UpdatedAt time.Time
}

func (q *Queries) UpdateExpenseCategory(ctx context.Context, arg UpdateExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, updateExpenseCategory,
		arg.AccountID,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.SortOrder,
		arg.UpdatedAt,
	)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Icon,
		&i.SortOrder,
		&i.IsPreset,
	)
	return i, err
}
