// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: challenges.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeChallenge = `-- name: ConsumeChallenge :exec
UPDATE auth_challenges
SET consumed_at = $2
WHERE id = $1
`

type ConsumeChallengeParams struct {
	ID         uuid.UUID
	ConsumedAt *time.Time
}

func (q *Queries) ConsumeChallenge(ctx context.Context, arg ConsumeChallengeParams) error {
	_, err := q.db.Exec(ctx, consumeChallenge, arg.ID, arg.ConsumedAt)
	return err
}

const countChallengesSince = `-- name: CountChallengesSince :one
SELECT count(*) AS n FROM auth_challenges
WHERE email_key = $1 AND purpose = $2 AND created_at >= $3
`

type CountChallengesSinceParams struct {
	EmailKey  string
	Purpose   string
	CreatedAt time.Time
}

func (q *Queries) CountChallengesSince(ctx context.Context, arg CountChallengesSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countChallengesSince, arg.EmailKey, arg.Purpose, arg.CreatedAt)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const createChallenge = `-- name: CreateChallenge :one
INSERT INTO auth_challenges (id, purpose, email_key, code_mac, key_id, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, purpose, email_key, code_mac, key_id, attempts, delivery_status, created_at, expires_at, consumed_at, invalidated_at
`

type CreateChallengeParams struct {
	ID        uuid.UUID
	Purpose   string
	EmailKey  string
	CodeMac   []byte
	KeyID     string
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) CreateChallenge(ctx context.Context, arg CreateChallengeParams) (AuthChallenge, error) {
	row := q.db.QueryRow(ctx, createChallenge,
		arg.ID,
		arg.Purpose,
		arg.EmailKey,
		arg.CodeMac,
		arg.KeyID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i AuthChallenge
	err := row.Scan(
		&i.ID,
		&i.Purpose,
		&i.EmailKey,
		&i.CodeMac,
		&i.KeyID,
		&i.Attempts,
		&i.DeliveryStatus,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.InvalidatedAt,
	)
	return i, err
}

const deleteExpiredChallenges = `-- name: DeleteExpiredChallenges :execrows
DELETE FROM auth_challenges
WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredChallenges(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredChallenges, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChallengeForUpdate = `-- name: GetChallengeForUpdate :one
SELECT id, purpose, email_key, code_mac, key_id, attempts, delivery_status, created_at, expires_at, consumed_at, invalidated_at FROM auth_challenges
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetChallengeForUpdate(ctx context.Context, id uuid.UUID) (AuthChallenge, error) {
	row := q.db.QueryRow(ctx, getChallengeForUpdate, id)
	var i AuthChallenge
	err := row.Scan(
		&i.ID,
		&i.Purpose,
		&i.EmailKey,
		&i.CodeMac,
		&i.KeyID,
		&i.Attempts,
		&i.DeliveryStatus,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.InvalidatedAt,
	)
	return i, err
}

const incrementChallengeAttempts = `-- name: IncrementChallengeAttempts :exec
UPDATE auth_challenges
SET attempts = attempts + 1
WHERE id = $1
`

func (q *Queries) IncrementChallengeAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementChallengeAttempts, id)
	return err
}

const invalidateChallenges = `-- name: InvalidateChallenges :exec

UPDATE auth_challenges
SET invalidated_at = $3
WHERE email_key = $1 AND purpose = $2 AND consumed_at IS NULL AND invalidated_at IS NULL
`

type InvalidateChallengesParams struct {
	EmailKey      string
	Purpose       string
	InvalidatedAt *time.Time
}

// 邮箱验证码挑战。
func (q *Queries) InvalidateChallenges(ctx context.Context, arg InvalidateChallengesParams) error {
	_, err := q.db.Exec(ctx, invalidateChallenges, arg.EmailKey, arg.Purpose, arg.InvalidatedAt)
	return err
}

const latestChallengeCreatedAt = `-- name: LatestChallengeCreatedAt :one
SELECT created_at FROM auth_challenges
WHERE email_key = $1 AND purpose = $2
ORDER BY created_at DESC
LIMIT 1
`

type LatestChallengeCreatedAtParams struct {
	EmailKey string
	Purpose  string
}

func (q *Queries) LatestChallengeCreatedAt(ctx context.Context, arg LatestChallengeCreatedAtParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, latestChallengeCreatedAt, arg.EmailKey, arg.Purpose)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const setChallengeDelivery = `-- name: SetChallengeDelivery :exec
UPDATE auth_challenges
SET delivery_status = $2
WHERE id = $1
`

type SetChallengeDeliveryParams struct {
	ID             uuid.UUID
	DeliveryStatus string
}

func (q *Queries) SetChallengeDelivery(ctx context.Context, arg SetChallengeDeliveryParams) error {
	_, err := q.db.Exec(ctx, setChallengeDelivery, arg.ID, arg.DeliveryStatus)
	return err
}
