// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const contentTombstoneExists = `-- name: ContentTombstoneExists :one
SELECT EXISTS(SELECT 1 FROM entity_tombstones WHERE account_id=$1 AND trip_id=$2 AND entity_type=$3 AND entity_id=$4)::boolean
`

type ContentTombstoneExistsParams struct {
	AccountID  uuid.UUID
	TripID     uuid.NullUUID
	EntityType string
	EntityID   uuid.UUID
}

func (q *Queries) ContentTombstoneExists(ctx context.Context, arg ContentTombstoneExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, contentTombstoneExists,
		arg.AccountID,
		arg.TripID,
		arg.EntityType,
		arg.EntityID,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const documentIDExists = `-- name: DocumentIDExists :one
SELECT (EXISTS(SELECT 1 FROM documents WHERE id=$1) OR EXISTS(SELECT 1 FROM entity_tombstones t WHERE t.account_id=$2 AND t.entity_type='document' AND t.entity_id=$1))::boolean AS used
`

type DocumentIDExistsParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) DocumentIDExists(ctx context.Context, arg DocumentIDExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, documentIDExists, arg.ID, arg.AccountID)
	var used bool
	err := row.Scan(&used)
	return used, err
}

const getContentAssetReference = `-- name: GetContentAssetReference :one
SELECT COALESCE(media_type,declared_media_type,'')::text AS media_type, deleted_at FROM assets
WHERE account_id=$1 AND trip_id=$2 AND id=$3 AND scope='trip' FOR UPDATE
`

type GetContentAssetReferenceParams struct {
	AccountID uuid.UUID
	TripID    uuid.NullUUID
	ID        uuid.UUID
}

type GetContentAssetReferenceRow struct {
	MediaType string
	DeletedAt *time.Time
}

func (q *Queries) GetContentAssetReference(ctx context.Context, arg GetContentAssetReferenceParams) (GetContentAssetReferenceRow, error) {
	row := q.db.QueryRow(ctx, getContentAssetReference, arg.AccountID, arg.TripID, arg.ID)
	var i GetContentAssetReferenceRow
	err := row.Scan(&i.MediaType, &i.DeletedAt)
	return i, err
}

const getContentReservationReference = `-- name: GetContentReservationReference :one
SELECT deleted_at FROM reservations WHERE account_id=$1 AND trip_id=$2 AND id=$3
`

type GetContentReservationReferenceParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetContentReservationReference(ctx context.Context, arg GetContentReservationReferenceParams) (*time.Time, error) {
	row := q.db.QueryRow(ctx, getContentReservationReference, arg.AccountID, arg.TripID, arg.ID)
	var deleted_at *time.Time
	err := row.Scan(&deleted_at)
	return deleted_at, err
}

const getDocument = `-- name: GetDocument :one
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, title, notes, asset_id, reservation_id FROM documents WHERE account_id=$1 AND trip_id=$2 AND id=$3
`

type GetDocumentParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.AccountID, arg.TripID, arg.ID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Title,
		&i.Notes,
		&i.AssetID,
		&i.ReservationID,
	)
	return i, err
}

const getPhoto = `-- name: GetPhoto :one
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, asset_id, taken_at_local, recorded_on, caption, sort_order, place_name, address, latitude, longitude FROM photos WHERE account_id=$1 AND trip_id=$2 AND id=$3
`

type GetPhotoParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetPhoto(ctx context.Context, arg GetPhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, getPhoto, arg.AccountID, arg.TripID, arg.ID)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.AssetID,
		&i.TakenAtLocal,
		&i.RecordedOn,
		&i.Caption,
		&i.SortOrder,
		&i.PlaceName,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getReservation = `-- name: GetReservation :one
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, kind, title, booking_reference, transport_number, provider_name, start_local, end_local, origin, destination, address, contact_name, contact_phone, notes FROM reservations WHERE account_id=$1 AND trip_id=$2 AND id=$3
`

type GetReservationParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetReservation(ctx context.Context, arg GetReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservation, arg.AccountID, arg.TripID, arg.ID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Kind,
		&i.Title,
		&i.BookingReference,
		&i.TransportNumber,
		&i.ProviderName,
		&i.StartLocal,
		&i.EndLocal,
		&i.Origin,
		&i.Destination,
		&i.Address,
		&i.ContactName,
		&i.ContactPhone,
		&i.Notes,
	)
	return i, err
}

const insertDocument = `-- name: InsertDocument :one
INSERT INTO documents (id,account_id,trip_id,title,notes,asset_id,reservation_id,created_at,updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$8) RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, title, notes, asset_id, reservation_id
`

type InsertDocumentParams struct {
	ID            uuid.UUID
	AccountID     uuid.UUID
	TripID        uuid.UUID
	Title         string
	Notes         string
	AssetID       uuid.UUID
	ReservationID uuid.NullUUID
	CreatedAt     time.Time
}

func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, insertDocument,
		arg.ID,
		arg.AccountID,
		arg.TripID,
		arg.Title,
		arg.Notes,
		arg.AssetID,
		arg.ReservationID,
		arg.CreatedAt,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Title,
		&i.Notes,
		&i.AssetID,
		&i.ReservationID,
	)
	return i, err
}

const insertPhoto = `-- name: InsertPhoto :one
INSERT INTO photos (id,account_id,trip_id,asset_id,taken_at_local,recorded_on,caption,sort_order,place_name,address,latitude,longitude,created_at,updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$13) RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, asset_id, taken_at_local, recorded_on, caption, sort_order, place_name, address, latitude, longitude
`

type InsertPhotoParams struct {
	ID           uuid.UUID
	AccountID    uuid.UUID
	TripID       uuid.UUID
	AssetID      uuid.UUID
	TakenAtLocal *time.Time
	RecordedOn   time.Time
	Caption      string
	SortOrder    int32
	PlaceName    string
	Address      string
	Latitude     *string
	Longitude    *string
	CreatedAt    time.Time
}

func (q *Queries) InsertPhoto(ctx context.Context, arg InsertPhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, insertPhoto,
		arg.ID,
		arg.AccountID,
		arg.TripID,
		arg.AssetID,
		arg.TakenAtLocal,
		arg.RecordedOn,
		arg.Caption,
		arg.SortOrder,
		arg.PlaceName,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.CreatedAt,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.AssetID,
		&i.TakenAtLocal,
		&i.RecordedOn,
		&i.Caption,
		&i.SortOrder,
		&i.PlaceName,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const insertReservation = `-- name: InsertReservation :one
INSERT INTO reservations (id,account_id,trip_id,kind,title,booking_reference,transport_number,provider_name,start_local,end_local,origin,destination,address,contact_name,contact_phone,notes,created_at,updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$17) RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, kind, title, booking_reference, transport_number, provider_name, start_local, end_local, origin, destination, address, contact_name, contact_phone, notes
`

type InsertReservationParams struct {
	ID               uuid.UUID
	AccountID        uuid.UUID
	TripID           uuid.UUID
	Kind             string
	Title            string
	BookingReference string
	TransportNumber  *string
	ProviderName     *string
	StartLocal       *time.Time
	EndLocal         *time.Time
	Origin           *string
	Destination      *string
	Address          string
	ContactName      *string
	ContactPhone     *string
	Notes            string
	CreatedAt        time.Time
}

func (q *Queries) InsertReservation(ctx context.Context, arg InsertReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, insertReservation,
		arg.ID,
		arg.AccountID,
		arg.TripID,
		arg.Kind,
		arg.Title,
		arg.BookingReference,
		arg.TransportNumber,
		arg.ProviderName,
		arg.StartLocal,
		arg.EndLocal,
		arg.Origin,
		arg.Destination,
		arg.Address,
		arg.ContactName,
		arg.ContactPhone,
		arg.Notes,
		arg.CreatedAt,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Kind,
		&i.Title,
		&i.BookingReference,
		&i.TransportNumber,
		&i.ProviderName,
		&i.StartLocal,
		&i.EndLocal,
		&i.Origin,
		&i.Destination,
		&i.Address,
		&i.ContactName,
		&i.ContactPhone,
		&i.Notes,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, title, notes, asset_id, reservation_id FROM documents WHERE account_id=$1 AND trip_id=$2 AND deleted_at IS NULL
AND ($3::uuid IS NULL OR reservation_id=$3)
AND ($4::timestamptz IS NULL OR (created_at,id)<($4::timestamptz,$5::uuid))
ORDER BY created_at DESC,id DESC LIMIT $6
`

type ListDocumentsParams struct {
	AccountID     uuid.UUID
	TripID        uuid.UUID
	ReservationID uuid.NullUUID
	AfterTime     *time.Time
	AfterID       uuid.UUID
	PageLimit     int32
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocuments,
		arg.AccountID,
		arg.TripID,
		arg.ReservationID,
		arg.AfterTime,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TripID,
			&i.Title,
			&i.Notes,
			&i.AssetID,
			&i.ReservationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotos = `-- name: ListPhotos :many
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, asset_id, taken_at_local, recorded_on, caption, sort_order, place_name, address, latitude, longitude FROM photos WHERE account_id=$1 AND trip_id=$2 AND deleted_at IS NULL
AND ($3::date IS NULL OR recorded_on>=$3::date)
AND ($4::date IS NULL OR recorded_on<=$4::date)
AND ($5::date IS NULL OR recorded_on<$5::date
 OR (recorded_on=$5::date AND (COALESCE(taken_at_local,TIMESTAMP '9999-12-31 23:59:59'),sort_order,id)>($6::timestamp,$7::integer,$8::uuid)))
ORDER BY recorded_on DESC,COALESCE(taken_at_local,TIMESTAMP '9999-12-31 23:59:59'),sort_order,id LIMIT $9
`

type ListPhotosParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	DateFrom  *time.Time
	DateTo    *time.Time
	AfterDay  *time.Time
	AfterTime time.Time
	AfterSort int32
	AfterID   uuid.UUID
	PageLimit int32
}

func (q *Queries) ListPhotos(ctx context.Context, arg ListPhotosParams) ([]Photo, error) {
	rows, err := q.db.Query(ctx, listPhotos,
		arg.AccountID,
		arg.TripID,
		arg.DateFrom,
		arg.DateTo,
		arg.AfterDay,
		arg.AfterTime,
		arg.AfterSort,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TripID,
			&i.AssetID,
			&i.TakenAtLocal,
			&i.RecordedOn,
			&i.Caption,
			&i.SortOrder,
			&i.PlaceName,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservations = `-- name: ListReservations :many
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, kind, title, booking_reference, transport_number, provider_name, start_local, end_local, origin, destination, address, contact_name, contact_phone, notes FROM reservations WHERE account_id=$1 AND trip_id=$2 AND deleted_at IS NULL
AND ($3::text IS NULL OR kind=$3)
AND ($4::timestamp IS NULL OR (COALESCE(start_local,TIMESTAMP '9999-12-31 23:59:59'),id)>($4::timestamp,$5::uuid))
ORDER BY COALESCE(start_local,TIMESTAMP '9999-12-31 23:59:59'),id LIMIT $6
`

type ListReservationsParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	Kind      *string
	AfterTime *time.Time
	AfterID   uuid.UUID
	PageLimit int32
}

func (q *Queries) ListReservations(ctx context.Context, arg ListReservationsParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservations,
		arg.AccountID,
		arg.TripID,
		arg.Kind,
		arg.AfterTime,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TripID,
			&i.Kind,
			&i.Title,
			&i.BookingReference,
			&i.TransportNumber,
			&i.ProviderName,
			&i.StartLocal,
			&i.EndLocal,
			&i.Origin,
			&i.Destination,
			&i.Address,
			&i.ContactName,
			&i.ContactPhone,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const photoIDExists = `-- name: PhotoIDExists :one
SELECT (EXISTS(SELECT 1 FROM photos WHERE id=$1) OR EXISTS(SELECT 1 FROM entity_tombstones t WHERE t.account_id=$2 AND t.entity_type='photo' AND t.entity_id=$1))::boolean AS used
`

type PhotoIDExistsParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) PhotoIDExists(ctx context.Context, arg PhotoIDExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, photoIDExists, arg.ID, arg.AccountID)
	var used bool
	err := row.Scan(&used)
	return used, err
}

const reservationIDExists = `-- name: ReservationIDExists :one
SELECT (EXISTS(SELECT 1 FROM reservations WHERE id=$1) OR EXISTS(SELECT 1 FROM entity_tombstones t WHERE t.account_id=$2 AND t.entity_type='reservation' AND t.entity_id=$1))::boolean AS used
`

type ReservationIDExistsParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) ReservationIDExists(ctx context.Context, arg ReservationIDExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, reservationIDExists, arg.ID, arg.AccountID)
	var used bool
	err := row.Scan(&used)
	return used, err
}

const softDeleteDocument = `-- name: SoftDeleteDocument :one
UPDATE documents SET deleted_at=$1,updated_at=$1,version=version+1
WHERE account_id=$2 AND trip_id=$3 AND id=$4 RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, title, notes, asset_id, reservation_id
`

type SoftDeleteDocumentParams struct {
	UpdatedAt *time.Time
	AccountID uuid.UUID
	TripID    uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteDocument(ctx context.Context, arg SoftDeleteDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, softDeleteDocument,
		arg.UpdatedAt,
		arg.AccountID,
		arg.TripID,
		arg.ID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Title,
		&i.Notes,
		&i.AssetID,
		&i.ReservationID,
	)
	return i, err
}

const softDeletePhoto = `-- name: SoftDeletePhoto :one
UPDATE photos SET deleted_at=$1,updated_at=$1,version=version+1
WHERE account_id=$2 AND trip_id=$3 AND id=$4 RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, asset_id, taken_at_local, recorded_on, caption, sort_order, place_name, address, latitude, longitude
`

type SoftDeletePhotoParams struct {
	UpdatedAt *time.Time
	AccountID uuid.UUID
	TripID    uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeletePhoto(ctx context.Context, arg SoftDeletePhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, softDeletePhoto,
		arg.UpdatedAt,
		arg.AccountID,
		arg.TripID,
		arg.ID,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.AssetID,
		&i.TakenAtLocal,
		&i.RecordedOn,
		&i.Caption,
		&i.SortOrder,
		&i.PlaceName,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const softDeleteReservation = `-- name: SoftDeleteReservation :one
UPDATE reservations SET deleted_at=$1,updated_at=$1,version=version+1
WHERE account_id=$2 AND trip_id=$3 AND id=$4 RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, kind, title, booking_reference, transport_number, provider_name, start_local, end_local, origin, destination, address, contact_name, contact_phone, notes
`

type SoftDeleteReservationParams struct {
	UpdatedAt *time.Time
	AccountID uuid.UUID
	TripID    uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteReservation(ctx context.Context, arg SoftDeleteReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, softDeleteReservation,
		arg.UpdatedAt,
		arg.AccountID,
		arg.TripID,
		arg.ID,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Kind,
		&i.Title,
		&i.BookingReference,
		&i.TransportNumber,
		&i.ProviderName,
		&i.StartLocal,
		&i.EndLocal,
		&i.Origin,
		&i.Destination,
		&i.Address,
		&i.ContactName,
		&i.ContactPhone,
		&i.Notes,
	)
	return i, err
}

const unlinkReservationDocuments = `-- name: UnlinkReservationDocuments :many
UPDATE documents SET reservation_id=NULL,version=version+1,updated_at=$1
WHERE account_id=$2 AND trip_id=$3 AND reservation_id=$4 AND deleted_at IS NULL RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, title, notes, asset_id, reservation_id
`

type UnlinkReservationDocumentsParams struct {
	UpdatedAt     time.Time
	AccountID     uuid.UUID
	TripID        uuid.UUID
	ReservationID uuid.NullUUID
}

func (q *Queries) UnlinkReservationDocuments(ctx context.Context, arg UnlinkReservationDocumentsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, unlinkReservationDocuments,
		arg.UpdatedAt,
		arg.AccountID,
		arg.TripID,
		arg.ReservationID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TripID,
			&i.Title,
			&i.Notes,
			&i.AssetID,
			&i.ReservationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents SET title=$1,notes=$2,asset_id=$3,reservation_id=$4,version=version+1,updated_at=$5
WHERE account_id=$6 AND trip_id=$7 AND id=$8 RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, title, notes, asset_id, reservation_id
`

type UpdateDocumentParams struct {
	Title         string
	Notes         string
	AssetID       uuid.UUID
	ReservationID uuid.NullUUID
	UpdatedAt     time.Time
	AccountID     uuid.UUID
	TripID        uuid.UUID
	ID            uuid.UUID
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.Title,
		arg.Notes,
		arg.AssetID,
		arg.ReservationID,
		arg.UpdatedAt,
		arg.AccountID,
		arg.TripID,
		arg.ID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Title,
		&i.Notes,
		&i.AssetID,
		&i.ReservationID,
	)
	return i, err
}

const updatePhoto = `-- name: UpdatePhoto :one
UPDATE photos SET asset_id=$1,taken_at_local=$2,recorded_on=$3,caption=$4,sort_order=$5,place_name=$6,address=$7,latitude=$8,longitude=$9,version=version+1,updated_at=$10
WHERE account_id=$11 AND trip_id=$12 AND id=$13 RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, asset_id, taken_at_local, recorded_on, caption, sort_order, place_name, address, latitude, longitude
`

type UpdatePhotoParams struct {
	AssetID      uuid.UUID
	TakenAtLocal *time.Time
	RecordedOn   time.Time
	Caption      string
	SortOrder    int32
	PlaceName    string
	Address      string
	Latitude     *string
	Longitude    *string
	UpdatedAt    time.Time
	AccountID    uuid.UUID
	TripID       uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) UpdatePhoto(ctx context.Context, arg UpdatePhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, updatePhoto,
		arg.AssetID,
		arg.TakenAtLocal,
		arg.RecordedOn,
		arg.Caption,
		arg.SortOrder,
		arg.PlaceName,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.UpdatedAt,
		arg.AccountID,
		arg.TripID,
		arg.ID,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.AssetID,
		&i.TakenAtLocal,
		&i.RecordedOn,
		&i.Caption,
		&i.SortOrder,
		&i.PlaceName,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const updateReservation = `-- name: UpdateReservation :one
UPDATE reservations SET kind=$1,title=$2,booking_reference=$3,transport_number=$4,provider_name=$5,start_local=$6,end_local=$7,origin=$8,destination=$9,address=$10,contact_name=$11,contact_phone=$12,notes=$13,version=version+1,updated_at=$14
WHERE account_id=$15 AND trip_id=$16 AND id=$17 RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, kind, title, booking_reference, transport_number, provider_name, start_local, end_local, origin, destination, address, contact_name, contact_phone, notes
`

type UpdateReservationParams struct {
	Kind             string
	Title            string
	BookingReference string
	TransportNumber  *string
	ProviderName     *string
	StartLocal       *time.Time
	EndLocal         *time.Time
	Origin           *string
	Destination      *string
	Address          string
	ContactName      *string
	ContactPhone     *string
	Notes            string
	UpdatedAt        time.Time
	AccountID        uuid.UUID
	TripID           uuid.UUID
	ID               uuid.UUID
}

func (q *Queries) UpdateReservation(ctx context.Context, arg UpdateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, updateReservation,
		arg.Kind,
		arg.Title,
		arg.BookingReference,
		arg.TransportNumber,
		arg.ProviderName,
		arg.StartLocal,
		arg.EndLocal,
		arg.Origin,
		arg.Destination,
		arg.Address,
		arg.ContactName,
		arg.ContactPhone,
		arg.Notes,
		arg.UpdatedAt,
		arg.AccountID,
		arg.TripID,
		arg.ID,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Kind,
		&i.Title,
		&i.BookingReference,
		&i.TransportNumber,
		&i.ProviderName,
		&i.StartLocal,
		&i.EndLocal,
		&i.Origin,
		&i.Destination,
		&i.Address,
		&i.ContactName,
		&i.ContactPhone,
		&i.Notes,
	)
	return i, err
}
