// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const dashboardCategories = `-- name: DashboardCategories :many
SELECT l.trip_id, l.category_id, COALESCE(c.name, '已删除分类')::text AS category_name,
       COALESCE(SUM(CASE WHEN l.kind = 'expense' THEN l.personal_amount ELSE 0 END), 0)::numeric AS personal_expense,
       COALESCE(SUM(CASE WHEN l.kind = 'refund' THEN l.personal_amount ELSE 0 END), 0)::numeric AS personal_refund,
       COALESCE(SUM(CASE WHEN l.kind = 'expense' THEN l.amount ELSE 0 END), 0)::numeric AS whole_expense,
       COALESCE(SUM(CASE WHEN l.kind = 'refund' THEN l.amount ELSE 0 END), 0)::numeric AS whole_refund
FROM ledger_entries l
JOIN trips t ON t.account_id = l.account_id AND t.id = l.trip_id
LEFT JOIN expense_categories c ON c.account_id = l.account_id AND c.id = l.category_id
WHERE l.account_id = $1 AND l.trip_id = ANY($2::uuid[])
  AND l.deleted_at IS NULL AND t.deleted_at IS NULL
GROUP BY l.trip_id, l.category_id, c.name
ORDER BY l.trip_id, l.category_id
`

type DashboardCategoriesParams struct {
	AccountID uuid.UUID
	TripIds   []uuid.UUID
}

type DashboardCategoriesRow struct {
	TripID          uuid.UUID
	CategoryID      uuid.UUID
	CategoryName    string
	PersonalExpense string
	PersonalRefund  string
	WholeExpense    string
	WholeRefund     string
}

func (q *Queries) DashboardCategories(ctx context.Context, arg DashboardCategoriesParams) ([]DashboardCategoriesRow, error) {
	rows, err := q.db.Query(ctx, dashboardCategories, arg.AccountID, arg.TripIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardCategoriesRow{}
	for rows.Next() {
		var i DashboardCategoriesRow
		if err := rows.Scan(
			&i.TripID,
			&i.CategoryID,
			&i.CategoryName,
			&i.PersonalExpense,
			&i.PersonalRefund,
			&i.WholeExpense,
			&i.WholeRefund,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardPlaces = `-- name: DashboardPlaces :many
SELECT i.id, i.trip_id, i.version, i.title, i.place_name, i.kind, i.scheduled_on,
       i.address, i.latitude, i.longitude, i.footprint_excluded, i.poi_id,
       r.province_code, r.province_name, r.city_code, r.city_name
FROM itinerary_items i
JOIN trips t ON t.account_id = i.account_id AND t.id = i.trip_id
LEFT JOIN dashboard_regions r ON r.latitude = i.latitude AND r.longitude = i.longitude
WHERE i.account_id = $1 AND i.trip_id = ANY($2::uuid[])
  AND i.deleted_at IS NULL AND t.deleted_at IS NULL
ORDER BY i.scheduled_on DESC, i.sort_order, i.id
`

type DashboardPlacesParams struct {
	AccountID uuid.UUID
	TripIds   []uuid.UUID
}

type DashboardPlacesRow struct {
	ID                uuid.UUID
	TripID            uuid.UUID
	Version           int64
	Title             string
	PlaceName         string
	Kind              string
	ScheduledOn       time.Time
	Address           string
	Latitude          *string
	Longitude         *string
	FootprintExcluded bool
	PoiID             string
	ProvinceCode      *string
	ProvinceName      *string
	CityCode          *string
	CityName          *string
}

func (q *Queries) DashboardPlaces(ctx context.Context, arg DashboardPlacesParams) ([]DashboardPlacesRow, error) {
	rows, err := q.db.Query(ctx, dashboardPlaces, arg.AccountID, arg.TripIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardPlacesRow{}
	for rows.Next() {
		var i DashboardPlacesRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Version,
			&i.Title,
			&i.PlaceName,
			&i.Kind,
			&i.ScheduledOn,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.FootprintExcluded,
			&i.PoiID,
			&i.ProvinceCode,
			&i.ProvinceName,
			&i.CityCode,
			&i.CityName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardTrips = `-- name: DashboardTrips :many
SELECT id, name, start_date, end_date, currency_code
FROM trips
WHERE account_id = $1 AND deleted_at IS NULL
  AND end_date < ($2::timestamptz AT TIME ZONE timezone)::date
ORDER BY start_date DESC, id
`

type DashboardTripsParams struct {
	AccountID uuid.UUID
	AsOf      time.Time
}

type DashboardTripsRow struct {
	ID           uuid.UUID
	Name         string
	StartDate    time.Time
	EndDate      time.Time
	CurrencyCode string
}

func (q *Queries) DashboardTrips(ctx context.Context, arg DashboardTripsParams) ([]DashboardTripsRow, error) {
	rows, err := q.db.Query(ctx, dashboardTrips, arg.AccountID, arg.AsOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardTripsRow{}
	for rows.Next() {
		var i DashboardTripsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.CurrencyCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveDashboardRegion = `-- name: SaveDashboardRegion :exec
INSERT INTO dashboard_regions (latitude, longitude, province_code, province_name, city_code, city_name, resolved_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (latitude, longitude) DO UPDATE SET
    province_code = EXCLUDED.province_code, province_name = EXCLUDED.province_name,
    city_code = EXCLUDED.city_code, city_name = EXCLUDED.city_name, resolved_at = EXCLUDED.resolved_at
`

type SaveDashboardRegionParams struct {
	Latitude     string
	Longitude    string
	ProvinceCode string
	ProvinceName string
	CityCode     string
	CityName     string
	ResolvedAt   time.Time
}

func (q *Queries) SaveDashboardRegion(ctx context.Context, arg SaveDashboardRegionParams) error {
	_, err := q.db.Exec(ctx, saveDashboardRegion,
		arg.Latitude,
		arg.Longitude,
		arg.ProvinceCode,
		arg.ProvinceName,
		arg.CityCode,
		arg.CityName,
		arg.ResolvedAt,
	)
	return err
}
