// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: itinerary.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getItineraryItem = `-- name: GetItineraryItem :one
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, title, kind, scheduled_on, sort_order, planned_start_local, planned_end_local, planned_duration_minutes, place_name, address, latitude, longitude, estimated_amount, notes, status, actual_start_local, actual_end_local, actual_notes, footprint_excluded, poi_id FROM itinerary_items
WHERE account_id = $1 AND trip_id = $2 AND id = $3
`

type GetItineraryItemParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetItineraryItem(ctx context.Context, arg GetItineraryItemParams) (ItineraryItem, error) {
	row := q.db.QueryRow(ctx, getItineraryItem, arg.AccountID, arg.TripID, arg.ID)
	var i ItineraryItem
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Title,
		&i.Kind,
		&i.ScheduledOn,
		&i.SortOrder,
		&i.PlannedStartLocal,
		&i.PlannedEndLocal,
		&i.PlannedDurationMinutes,
		&i.PlaceName,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.EstimatedAmount,
		&i.Notes,
		&i.Status,
		&i.ActualStartLocal,
		&i.ActualEndLocal,
		&i.ActualNotes,
		&i.FootprintExcluded,
		&i.PoiID,
	)
	return i, err
}

const getItineraryItemForUpdate = `-- name: GetItineraryItemForUpdate :one
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, title, kind, scheduled_on, sort_order, planned_start_local, planned_end_local, planned_duration_minutes, place_name, address, latitude, longitude, estimated_amount, notes, status, actual_start_local, actual_end_local, actual_notes, footprint_excluded, poi_id FROM itinerary_items
WHERE account_id = $1 AND trip_id = $2 AND id = $3
FOR UPDATE
`

type GetItineraryItemForUpdateParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetItineraryItemForUpdate(ctx context.Context, arg GetItineraryItemForUpdateParams) (ItineraryItem, error) {
	row := q.db.QueryRow(ctx, getItineraryItemForUpdate, arg.AccountID, arg.TripID, arg.ID)
	var i ItineraryItem
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Title,
		&i.Kind,
		&i.ScheduledOn,
		&i.SortOrder,
		&i.PlannedStartLocal,
		&i.PlannedEndLocal,
		&i.PlannedDurationMinutes,
		&i.PlaceName,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.EstimatedAmount,
		&i.Notes,
		&i.Status,
		&i.ActualStartLocal,
		&i.ActualEndLocal,
		&i.ActualNotes,
		&i.FootprintExcluded,
		&i.PoiID,
	)
	return i, err
}

const getTripContentInfo = `-- name: GetTripContentInfo :one

SELECT currency_code, timezone, start_date, end_date, deleted_at FROM trips
WHERE account_id = $1 AND id = $2
`

type GetTripContentInfoParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

type GetTripContentInfoRow struct {
	CurrencyCode string
	Timezone     string
	StartDate    time.Time
	EndDate      time.Time
	DeletedAt    *time.Time
}

// 每日行程项目（数据库设计表 5）。时间由应用时钟传入；currency_code 不存列，由适配器按旅行币种派生。
func (q *Queries) GetTripContentInfo(ctx context.Context, arg GetTripContentInfoParams) (GetTripContentInfoRow, error) {
	row := q.db.QueryRow(ctx, getTripContentInfo, arg.AccountID, arg.ID)
	var i GetTripContentInfoRow
	err := row.Scan(
		&i.CurrencyCode,
		&i.Timezone,
		&i.StartDate,
		&i.EndDate,
		&i.DeletedAt,
	)
	return i, err
}

const insertItineraryItem = `-- name: InsertItineraryItem :one
INSERT INTO itinerary_items (id, account_id, trip_id, title, kind, scheduled_on, sort_order,
    planned_start_local, planned_end_local, planned_duration_minutes, place_name, address, latitude, longitude,
    poi_id, estimated_amount, notes, status, actual_start_local, actual_end_local, actual_notes, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18,
    $19, $20, $21, $22, $22)
RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, title, kind, scheduled_on, sort_order, planned_start_local, planned_end_local, planned_duration_minutes, place_name, address, latitude, longitude, estimated_amount, notes, status, actual_start_local, actual_end_local, actual_notes, footprint_excluded, poi_id
`

type InsertItineraryItemParams struct {
	ID                     uuid.UUID
	AccountID              uuid.UUID
	TripID                 uuid.UUID
	Title                  string
	Kind                   string
	ScheduledOn            time.Time
	SortOrder              int32
	PlannedStartLocal      *time.Time
	PlannedEndLocal        *time.Time
	PlannedDurationMinutes *int32
	PlaceName              string
	Address                string
	Latitude               *string
	Longitude              *string
	PoiID                  string
	EstimatedAmount        *string
	Notes                  string
	Status                 string
	ActualStartLocal       *time.Time
	ActualEndLocal         *time.Time
	ActualNotes            string
	CreatedAt              time.Time
}

func (q *Queries) InsertItineraryItem(ctx context.Context, arg InsertItineraryItemParams) (ItineraryItem, error) {
	row := q.db.QueryRow(ctx, insertItineraryItem,
		arg.ID,
		arg.AccountID,
		arg.TripID,
		arg.Title,
		arg.Kind,
		arg.ScheduledOn,
		arg.SortOrder,
		arg.PlannedStartLocal,
		arg.PlannedEndLocal,
		arg.PlannedDurationMinutes,
		arg.PlaceName,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.PoiID,
		arg.EstimatedAmount,
		arg.Notes,
		arg.Status,
		arg.ActualStartLocal,
		arg.ActualEndLocal,
		arg.ActualNotes,
		arg.CreatedAt,
	)
	var i ItineraryItem
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Title,
		&i.Kind,
		&i.ScheduledOn,
		&i.SortOrder,
		&i.PlannedStartLocal,
		&i.PlannedEndLocal,
		&i.PlannedDurationMinutes,
		&i.PlaceName,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.EstimatedAmount,
		&i.Notes,
		&i.Status,
		&i.ActualStartLocal,
		&i.ActualEndLocal,
		&i.ActualNotes,
		&i.FootprintExcluded,
		&i.PoiID,
	)
	return i, err
}

const itineraryItemIDExists = `-- name: ItineraryItemIDExists :one
SELECT EXISTS (SELECT 1 FROM itinerary_items i WHERE i.id = $1)
    OR EXISTS (SELECT 1 FROM entity_tombstones et WHERE et.account_id = $2 AND et.entity_type = 'itinerary_item' AND et.entity_id = $1) AS exists
`

type ItineraryItemIDExistsParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) ItineraryItemIDExists(ctx context.Context, arg ItineraryItemIDExistsParams) (*bool, error) {
	row := q.db.QueryRow(ctx, itineraryItemIDExists, arg.ID, arg.AccountID)
	var exists *bool
	err := row.Scan(&exists)
	return exists, err
}

const listItineraryItems = `-- name: ListItineraryItems :many
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, title, kind, scheduled_on, sort_order, planned_start_local, planned_end_local, planned_duration_minutes, place_name, address, latitude, longitude, estimated_amount, notes, status, actual_start_local, actual_end_local, actual_notes, footprint_excluded, poi_id FROM itinerary_items
WHERE account_id = $1 AND trip_id = $2 AND deleted_at IS NULL
  AND ($3::date IS NULL OR scheduled_on >= $3::date)
  AND ($4::date IS NULL OR scheduled_on <= $4::date)
  AND ($5::text IS NULL OR status = $5::text)
  AND ($6::date IS NULL
       OR (scheduled_on, sort_order, id) > ($6::date, $7::int, $8::uuid))
ORDER BY scheduled_on, sort_order, id
LIMIT $9
`

type ListItineraryItemsParams struct {
	AccountID         uuid.UUID
	TripID            uuid.UUID
	DateFrom          *time.Time
	DateTo            *time.Time
	Status            *string
	CursorScheduledOn *time.Time
	CursorSortOrder   *int32
	CursorID          uuid.NullUUID
	RowLimit          int32
}

// 列表：接口设计 3.9 ItineraryFilters；游标用行比较走 (account_id, trip_id, scheduled_on, sort_order, id) 部分索引。
func (q *Queries) ListItineraryItems(ctx context.Context, arg ListItineraryItemsParams) ([]ItineraryItem, error) {
	rows, err := q.db.Query(ctx, listItineraryItems,
		arg.AccountID,
		arg.TripID,
		arg.DateFrom,
		arg.DateTo,
		arg.Status,
		arg.CursorScheduledOn,
		arg.CursorSortOrder,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItineraryItem{}
	for rows.Next() {
		var i ItineraryItem
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TripID,
			&i.Title,
			&i.Kind,
			&i.ScheduledOn,
			&i.SortOrder,
			&i.PlannedStartLocal,
			&i.PlannedEndLocal,
			&i.PlannedDurationMinutes,
			&i.PlaceName,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.EstimatedAmount,
			&i.Notes,
			&i.Status,
			&i.ActualStartLocal,
			&i.ActualEndLocal,
			&i.ActualNotes,
			&i.FootprintExcluded,
			&i.PoiID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItineraryItemsForDays = `-- name: ListItineraryItemsForDays :many
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, title, kind, scheduled_on, sort_order, planned_start_local, planned_end_local, planned_duration_minutes, place_name, address, latitude, longitude, estimated_amount, notes, status, actual_start_local, actual_end_local, actual_notes, footprint_excluded, poi_id FROM itinerary_items
WHERE account_id = $1 AND trip_id = $2 AND deleted_at IS NULL
  AND scheduled_on = ANY($3::date[])
ORDER BY scheduled_on, sort_order, id
FOR UPDATE
`

type ListItineraryItemsForDaysParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	Dates     []time.Time
}

func (q *Queries) ListItineraryItemsForDays(ctx context.Context, arg ListItineraryItemsForDaysParams) ([]ItineraryItem, error) {
	rows, err := q.db.Query(ctx, listItineraryItemsForDays, arg.AccountID, arg.TripID, arg.Dates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItineraryItem{}
	for rows.Next() {
		var i ItineraryItem
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TripID,
			&i.Title,
			&i.Kind,
			&i.ScheduledOn,
			&i.SortOrder,
			&i.PlannedStartLocal,
			&i.PlannedEndLocal,
			&i.PlannedDurationMinutes,
			&i.PlaceName,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.EstimatedAmount,
			&i.Notes,
			&i.Status,
			&i.ActualStartLocal,
			&i.ActualEndLocal,
			&i.ActualNotes,
			&i.FootprintExcluded,
			&i.PoiID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxItinerarySortOrder = `-- name: MaxItinerarySortOrder :one
SELECT COALESCE(max(sort_order), 0)::int AS max_order, count(*)::int AS item_count FROM itinerary_items
WHERE account_id = $1 AND trip_id = $2 AND scheduled_on = $3 AND deleted_at IS NULL
`

type MaxItinerarySortOrderParams struct {
	AccountID   uuid.UUID
	TripID      uuid.UUID
	ScheduledOn time.Time
}

type MaxItinerarySortOrderRow struct {
	MaxOrder  int32
	ItemCount int32
}

func (q *Queries) MaxItinerarySortOrder(ctx context.Context, arg MaxItinerarySortOrderParams) (MaxItinerarySortOrderRow, error) {
	row := q.db.QueryRow(ctx, maxItinerarySortOrder, arg.AccountID, arg.TripID, arg.ScheduledOn)
	var i MaxItinerarySortOrderRow
	err := row.Scan(&i.MaxOrder, &i.ItemCount)
	return i, err
}

const repositionItineraryItem = `-- name: RepositionItineraryItem :one
UPDATE itinerary_items
SET scheduled_on = $1, sort_order = $2, version = version + 1, updated_at = $3
WHERE account_id = $4 AND trip_id = $5 AND id = $6
RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, title, kind, scheduled_on, sort_order, planned_start_local, planned_end_local, planned_duration_minutes, place_name, address, latitude, longitude, estimated_amount, notes, status, actual_start_local, actual_end_local, actual_notes, footprint_excluded, poi_id
`

type RepositionItineraryItemParams struct {
	ScheduledOn time.Time
	SortOrder   int32
	UpdatedAt   time.Time
	AccountID   uuid.UUID
	TripID      uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) RepositionItineraryItem(ctx context.Context, arg RepositionItineraryItemParams) (ItineraryItem, error) {
	row := q.db.QueryRow(ctx, repositionItineraryItem,
		arg.ScheduledOn,
		arg.SortOrder,
		arg.UpdatedAt,
		arg.AccountID,
		arg.TripID,
		arg.ID,
	)
	var i ItineraryItem
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Title,
		&i.Kind,
		&i.ScheduledOn,
		&i.SortOrder,
		&i.PlannedStartLocal,
		&i.PlannedEndLocal,
		&i.PlannedDurationMinutes,
		&i.PlaceName,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.EstimatedAmount,
		&i.Notes,
		&i.Status,
		&i.ActualStartLocal,
		&i.ActualEndLocal,
		&i.ActualNotes,
		&i.FootprintExcluded,
		&i.PoiID,
	)
	return i, err
}

const softDeleteItineraryItem = `-- name: SoftDeleteItineraryItem :one
UPDATE itinerary_items
SET deleted_at = $1, version = version + 1, updated_at = $1
WHERE account_id = $2 AND trip_id = $3 AND id = $4
RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, title, kind, scheduled_on, sort_order, planned_start_local, planned_end_local, planned_duration_minutes, place_name, address, latitude, longitude, estimated_amount, notes, status, actual_start_local, actual_end_local, actual_notes, footprint_excluded, poi_id
`

type SoftDeleteItineraryItemParams struct {
	DeletedAt *time.Time
	AccountID uuid.UUID
	TripID    uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteItineraryItem(ctx context.Context, arg SoftDeleteItineraryItemParams) (ItineraryItem, error) {
	row := q.db.QueryRow(ctx, softDeleteItineraryItem,
		arg.DeletedAt,
		arg.AccountID,
		arg.TripID,
		arg.ID,
	)
	var i ItineraryItem
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Title,
		&i.Kind,
		&i.ScheduledOn,
		&i.SortOrder,
		&i.PlannedStartLocal,
		&i.PlannedEndLocal,
		&i.PlannedDurationMinutes,
		&i.PlaceName,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.EstimatedAmount,
		&i.Notes,
		&i.Status,
		&i.ActualStartLocal,
		&i.ActualEndLocal,
		&i.ActualNotes,
		&i.FootprintExcluded,
		&i.PoiID,
	)
	return i, err
}

const updateItineraryItem = `-- name: UpdateItineraryItem :one
WITH invalidated_routes AS (
    UPDATE itinerary_route_legs AS leg
    SET status = 'stale', route_distance_meters = NULL, route_duration_seconds = NULL,
        error_code = NULL, calculated_at = NULL, version = leg.version + 1, updated_at = $18
    FROM itinerary_items AS item
    WHERE item.account_id = $19 AND item.trip_id = $20 AND item.id = $21
      AND leg.account_id = item.account_id AND leg.trip_id = item.trip_id
      AND (leg.from_item_id = item.id OR leg.to_item_id = item.id)
      AND (item.latitude IS DISTINCT FROM $10::numeric
        OR item.longitude IS DISTINCT FROM $11::numeric)
)
UPDATE itinerary_items
SET footprint_excluded = $1, poi_id = $2, title = $3, kind = $4,
    planned_start_local = $5, planned_end_local = $6, planned_duration_minutes = $7,
    place_name = $8, address = $9, latitude = $10, longitude = $11,
    estimated_amount = $12, notes = $13, status = $14,
    actual_start_local = $15, actual_end_local = $16, actual_notes = $17,
    version = itinerary_items.version + 1, updated_at = $18
WHERE itinerary_items.account_id = $19 AND itinerary_items.trip_id = $20 AND itinerary_items.id = $21
RETURNING itinerary_items.id, itinerary_items.account_id, itinerary_items.version, itinerary_items.created_at, itinerary_items.updated_at, itinerary_items.deleted_at, itinerary_items.trip_id, itinerary_items.title, itinerary_items.kind, itinerary_items.scheduled_on, itinerary_items.sort_order, itinerary_items.planned_start_local, itinerary_items.planned_end_local, itinerary_items.planned_duration_minutes, itinerary_items.place_name, itinerary_items.address, itinerary_items.latitude, itinerary_items.longitude, itinerary_items.estimated_amount, itinerary_items.notes, itinerary_items.status, itinerary_items.actual_start_local, itinerary_items.actual_end_local, itinerary_items.actual_notes, itinerary_items.footprint_excluded, itinerary_items.poi_id
`

type UpdateItineraryItemParams struct {
	FootprintExcluded      bool
	PoiID                  string
	Title                  string
	Kind                   string
	PlannedStartLocal      *time.Time
	PlannedEndLocal        *time.Time
	PlannedDurationMinutes *int32
	PlaceName              string
	Address                string
	Latitude               *string
	Longitude              *string
	EstimatedAmount        *string
	Notes                  string
	Status                 string
	ActualStartLocal       *time.Time
	ActualEndLocal         *time.Time
	ActualNotes            string
	UpdatedAt              time.Time
	AccountID              uuid.UUID
	TripID                 uuid.UUID
	ID                     uuid.UUID
}

func (q *Queries) UpdateItineraryItem(ctx context.Context, arg UpdateItineraryItemParams) (ItineraryItem, error) {
	row := q.db.QueryRow(ctx, updateItineraryItem,
		arg.FootprintExcluded,
		arg.PoiID,
		arg.Title,
		arg.Kind,
		arg.PlannedStartLocal,
		arg.PlannedEndLocal,
		arg.PlannedDurationMinutes,
		arg.PlaceName,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.EstimatedAmount,
		arg.Notes,
		arg.Status,
		arg.ActualStartLocal,
		arg.ActualEndLocal,
		arg.ActualNotes,
		arg.UpdatedAt,
		arg.AccountID,
		arg.TripID,
		arg.ID,
	)
	var i ItineraryItem
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Title,
		&i.Kind,
		&i.ScheduledOn,
		&i.SortOrder,
		&i.PlannedStartLocal,
		&i.PlannedEndLocal,
		&i.PlannedDurationMinutes,
		&i.PlaceName,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.EstimatedAmount,
		&i.Notes,
		&i.Status,
		&i.ActualStartLocal,
		&i.ActualEndLocal,
		&i.ActualNotes,
		&i.FootprintExcluded,
		&i.PoiID,
	)
	return i, err
}
