// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveLedgerEntries = `-- name: CountActiveLedgerEntries :one
SELECT count(*) FROM ledger_entries
WHERE account_id = $1 AND trip_id = $2 AND deleted_at IS NULL
`

type CountActiveLedgerEntriesParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
}

func (q *Queries) CountActiveLedgerEntries(ctx context.Context, arg CountActiveLedgerEntriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveLedgerEntries, arg.AccountID, arg.TripID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteLedgerAttachments = `-- name: DeleteLedgerAttachments :exec
DELETE FROM ledger_attachments
WHERE account_id = $1 AND trip_id = $2 AND ledger_entry_id = $3
`

type DeleteLedgerAttachmentsParams struct {
	AccountID     uuid.UUID
	TripID        uuid.UUID
	LedgerEntryID uuid.UUID
}

// 票据引用：整体替换。
func (q *Queries) DeleteLedgerAttachments(ctx context.Context, arg DeleteLedgerAttachmentsParams) error {
	_, err := q.db.Exec(ctx, deleteLedgerAttachments, arg.AccountID, arg.TripID, arg.LedgerEntryID)
	return err
}

const deleteLedgerSplits = `-- name: DeleteLedgerSplits :exec
DELETE FROM ledger_entry_splits
WHERE account_id = $1 AND trip_id = $2 AND ledger_entry_id = $3
`

type DeleteLedgerSplitsParams struct {
	AccountID     uuid.UUID
	TripID        uuid.UUID
	LedgerEntryID uuid.UUID
}

// 分摊份额：整体替换；amounts 与 member_ids 一一对应，顺序即 sort_order。
func (q *Queries) DeleteLedgerSplits(ctx context.Context, arg DeleteLedgerSplitsParams) error {
	_, err := q.db.Exec(ctx, deleteLedgerSplits, arg.AccountID, arg.TripID, arg.LedgerEntryID)
	return err
}

const expenseCategoryActive = `-- name: ExpenseCategoryActive :one
SELECT EXISTS (
    SELECT 1 FROM expense_categories
    WHERE account_id = $1 AND id = $2 AND deleted_at IS NULL
) AS active
`

type ExpenseCategoryActiveParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) ExpenseCategoryActive(ctx context.Context, arg ExpenseCategoryActiveParams) (bool, error) {
	row := q.db.QueryRow(ctx, expenseCategoryActive, arg.AccountID, arg.ID)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const getLedgerEntry = `-- name: GetLedgerEntry :one
SELECT l.id, l.account_id, l.version, l.created_at, l.updated_at, l.deleted_at, l.trip_id, l.kind, l.amount, l.category_id, l.occurred_on, l.notes, l.refunded_entry_id, l.split_count, l.personal_amount, l.payer_member_id, l.split_mode, t.currency_code
FROM ledger_entries l
JOIN trips t ON t.account_id = l.account_id AND t.id = l.trip_id
WHERE l.account_id = $1 AND l.trip_id = $2 AND l.id = $3
`

type GetLedgerEntryParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	ID        uuid.UUID
}

type GetLedgerEntryRow struct {
	LedgerEntry  LedgerEntry
	CurrencyCode string
}

func (q *Queries) GetLedgerEntry(ctx context.Context, arg GetLedgerEntryParams) (GetLedgerEntryRow, error) {
	row := q.db.QueryRow(ctx, getLedgerEntry, arg.AccountID, arg.TripID, arg.ID)
	var i GetLedgerEntryRow
	err := row.Scan(
		&i.LedgerEntry.ID,
		&i.LedgerEntry.AccountID,
		&i.LedgerEntry.Version,
		&i.LedgerEntry.CreatedAt,
		&i.LedgerEntry.UpdatedAt,
		&i.LedgerEntry.DeletedAt,
		&i.LedgerEntry.TripID,
		&i.LedgerEntry.Kind,
		&i.LedgerEntry.Amount,
		&i.LedgerEntry.CategoryID,
		&i.LedgerEntry.OccurredOn,
		&i.LedgerEntry.Notes,
		&i.LedgerEntry.RefundedEntryID,
		&i.LedgerEntry.SplitCount,
		&i.LedgerEntry.PersonalAmount,
		&i.LedgerEntry.PayerMemberID,
		&i.LedgerEntry.SplitMode,
		&i.CurrencyCode,
	)
	return i, err
}

const getLedgerEntryForUpdate = `-- name: GetLedgerEntryForUpdate :one
SELECT l.id, l.account_id, l.version, l.created_at, l.updated_at, l.deleted_at, l.trip_id, l.kind, l.amount, l.category_id, l.occurred_on, l.notes, l.refunded_entry_id, l.split_count, l.personal_amount, l.payer_member_id, l.split_mode, t.currency_code
FROM ledger_entries l
JOIN trips t ON t.account_id = l.account_id AND t.id = l.trip_id
WHERE l.account_id = $1 AND l.trip_id = $2 AND l.id = $3
FOR UPDATE OF l
`

type GetLedgerEntryForUpdateParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	ID        uuid.UUID
}

type GetLedgerEntryForUpdateRow struct {
	LedgerEntry  LedgerEntry
	CurrencyCode string
}

func (q *Queries) GetLedgerEntryForUpdate(ctx context.Context, arg GetLedgerEntryForUpdateParams) (GetLedgerEntryForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getLedgerEntryForUpdate, arg.AccountID, arg.TripID, arg.ID)
	var i GetLedgerEntryForUpdateRow
	err := row.Scan(
		&i.LedgerEntry.ID,
		&i.LedgerEntry.AccountID,
		&i.LedgerEntry.Version,
		&i.LedgerEntry.CreatedAt,
		&i.LedgerEntry.UpdatedAt,
		&i.LedgerEntry.DeletedAt,
		&i.LedgerEntry.TripID,
		&i.LedgerEntry.Kind,
		&i.LedgerEntry.Amount,
		&i.LedgerEntry.CategoryID,
		&i.LedgerEntry.OccurredOn,
		&i.LedgerEntry.Notes,
		&i.LedgerEntry.RefundedEntryID,
		&i.LedgerEntry.SplitCount,
		&i.LedgerEntry.PersonalAmount,
		&i.LedgerEntry.PayerMemberID,
		&i.LedgerEntry.SplitMode,
		&i.CurrencyCode,
	)
	return i, err
}

const getLedgerTripInfo = `-- name: GetLedgerTripInfo :one

SELECT currency_code, timezone, budget_amount, currency_locked_at, deleted_at FROM trips
WHERE account_id = $1 AND id = $2
`

type GetLedgerTripInfoParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

type GetLedgerTripInfoRow struct {
	CurrencyCode     string
	Timezone         string
	BudgetAmount     *string
	CurrencyLockedAt *time.Time
	DeletedAt        *time.Time
}

// 账目与票据（数据库设计表 9、10）与开支统计（数据库设计 §5）。
// currency_code 不存列，查询时从 trips 派生；金额 NUMERIC(18,4) 由适配器按币种小数位转回规范字符串。
func (q *Queries) GetLedgerTripInfo(ctx context.Context, arg GetLedgerTripInfoParams) (GetLedgerTripInfoRow, error) {
	row := q.db.QueryRow(ctx, getLedgerTripInfo, arg.AccountID, arg.ID)
	var i GetLedgerTripInfoRow
	err := row.Scan(
		&i.CurrencyCode,
		&i.Timezone,
		&i.BudgetAmount,
		&i.CurrencyLockedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertLedgerAttachments = `-- name: InsertLedgerAttachments :exec
INSERT INTO ledger_attachments (account_id, trip_id, ledger_entry_id, asset_id, sort_order, created_at)
SELECT $1, $2, $3, a.asset_id, (a.ord - 1)::int, $4
FROM unnest($5::uuid[]) WITH ORDINALITY AS a(asset_id, ord)
`

type InsertLedgerAttachmentsParams struct {
	AccountID     uuid.UUID
	TripID        uuid.UUID
	LedgerEntryID uuid.UUID
	CreatedAt     time.Time
	AssetIds      []uuid.UUID
}

func (q *Queries) InsertLedgerAttachments(ctx context.Context, arg InsertLedgerAttachmentsParams) error {
	_, err := q.db.Exec(ctx, insertLedgerAttachments,
		arg.AccountID,
		arg.TripID,
		arg.LedgerEntryID,
		arg.CreatedAt,
		arg.AssetIds,
	)
	return err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :one
INSERT INTO ledger_entries (id, account_id, trip_id, kind, amount, split_count, personal_amount, payer_member_id, split_mode, category_id, occurred_on, notes, refunded_entry_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
        $12, $13, $14, $14)
RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, kind, amount, category_id, occurred_on, notes, refunded_entry_id, split_count, personal_amount, payer_member_id, split_mode
`

type InsertLedgerEntryParams struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	TripID          uuid.UUID
	Kind            string
	Amount          string
	SplitCount      int32
	PersonalAmount  string
	PayerMemberID   uuid.UUID
	SplitMode       string
	CategoryID      uuid.UUID
	OccurredOn      time.Time
	Notes           string
	RefundedEntryID uuid.NullUUID
	CreatedAt       time.Time
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, insertLedgerEntry,
		arg.ID,
		arg.AccountID,
		arg.TripID,
		arg.Kind,
		arg.Amount,
		arg.SplitCount,
		arg.PersonalAmount,
		arg.PayerMemberID,
		arg.SplitMode,
		arg.CategoryID,
		arg.OccurredOn,
		arg.Notes,
		arg.RefundedEntryID,
		arg.CreatedAt,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Kind,
		&i.Amount,
		&i.CategoryID,
		&i.OccurredOn,
		&i.Notes,
		&i.RefundedEntryID,
		&i.SplitCount,
		&i.PersonalAmount,
		&i.PayerMemberID,
		&i.SplitMode,
	)
	return i, err
}

const insertLedgerSplits = `-- name: InsertLedgerSplits :exec
INSERT INTO ledger_entry_splits (account_id, trip_id, ledger_entry_id, member_id, amount, sort_order)
SELECT $1, $2, $3, m.member_id, a.amount::numeric, (m.ord - 1)::int
FROM unnest($4::uuid[]) WITH ORDINALITY AS m(member_id, ord)
JOIN unnest($5::text[]) WITH ORDINALITY AS a(amount, ord) ON a.ord = m.ord
`

type InsertLedgerSplitsParams struct {
	AccountID     uuid.UUID
	TripID        uuid.UUID
	LedgerEntryID uuid.UUID
	MemberIds     []uuid.UUID
	Amounts       []string
}

func (q *Queries) InsertLedgerSplits(ctx context.Context, arg InsertLedgerSplitsParams) error {
	_, err := q.db.Exec(ctx, insertLedgerSplits,
		arg.AccountID,
		arg.TripID,
		arg.LedgerEntryID,
		arg.MemberIds,
		arg.Amounts,
	)
	return err
}

const ledgerCategoryTotals = `-- name: LedgerCategoryTotals :many
SELECT c.id AS category_id, c.name, c.icon, c.sort_order,
       COALESCE(SUM(CASE WHEN l.kind = 'expense'
                              AND ($1::date IS NULL OR l.occurred_on >= $1::date)
                              AND ($2::date IS NULL OR l.occurred_on <= $2::date)
                              AND ($3::uuid IS NULL OR l.category_id = $3::uuid)
                              AND ($4::text IS NULL OR l.split_mode = $4::text)
                         THEN l.personal_amount END), 0)::numeric AS filtered_expense,
       COALESCE(SUM(CASE WHEN l.kind = 'refund'
                              AND ($1::date IS NULL OR l.occurred_on >= $1::date)
                              AND ($2::date IS NULL OR l.occurred_on <= $2::date)
                              AND ($3::uuid IS NULL OR l.category_id = $3::uuid)
                              AND ($4::text IS NULL OR l.split_mode = $4::text)
                         THEN l.personal_amount END), 0)::numeric AS filtered_refund,
       COALESCE(SUM(CASE WHEN l.kind = 'expense' THEN l.personal_amount END), 0)::numeric AS trip_expense,
       COALESCE(SUM(CASE WHEN l.kind = 'refund' THEN l.personal_amount END), 0)::numeric AS trip_refund
FROM expense_categories c
LEFT JOIN ledger_entries l
       ON l.account_id = c.account_id AND l.category_id = c.id AND l.trip_id = $5 AND l.deleted_at IS NULL
WHERE c.account_id = $6
GROUP BY c.id, c.name, c.icon, c.sort_order, c.deleted_at
HAVING c.deleted_at IS NULL OR count(l.id) > 0
ORDER BY c.sort_order, c.id
`

type LedgerCategoryTotalsParams struct {
	DateFrom   *time.Time
	DateTo     *time.Time
	CategoryID uuid.NullUUID
	SplitMode  *string
	TripID     uuid.UUID
	AccountID  uuid.UUID
}

type LedgerCategoryTotalsRow struct {
	CategoryID      uuid.UUID
	Name            string
	Icon            *string
	SortOrder       int32
	FilteredExpense string
	FilteredRefund  string
	TripExpense     string
	TripRefund      string
}

// 每个有效分类以及仍被本旅行有效账目引用的已删除分类；筛选范围的金额与整趟的金额分别聚合。
func (q *Queries) LedgerCategoryTotals(ctx context.Context, arg LedgerCategoryTotalsParams) ([]LedgerCategoryTotalsRow, error) {
	rows, err := q.db.Query(ctx, ledgerCategoryTotals,
		arg.DateFrom,
		arg.DateTo,
		arg.CategoryID,
		arg.SplitMode,
		arg.TripID,
		arg.AccountID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerCategoryTotalsRow{}
	for rows.Next() {
		var i LedgerCategoryTotalsRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.Name,
			&i.Icon,
			&i.SortOrder,
			&i.FilteredExpense,
			&i.FilteredRefund,
			&i.TripExpense,
			&i.TripRefund,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ledgerDailyTotals = `-- name: LedgerDailyTotals :many
SELECT occurred_on,
       COALESCE(SUM(CASE WHEN kind = 'expense' THEN personal_amount END), 0)::numeric AS expense_amount,
       COALESCE(SUM(CASE WHEN kind = 'refund' THEN personal_amount END), 0)::numeric AS refund_amount
FROM ledger_entries
WHERE account_id = $1 AND trip_id = $2 AND deleted_at IS NULL
  AND ($3::date IS NULL OR occurred_on >= $3::date)
  AND ($4::date IS NULL OR occurred_on <= $4::date)
  AND ($5::uuid IS NULL OR category_id = $5::uuid)
  AND ($6::date IS NULL OR occurred_on < $6::date)
  AND ($7::text IS NULL OR split_mode = $7::text)
GROUP BY occurred_on
ORDER BY occurred_on DESC
LIMIT $8
`

type LedgerDailyTotalsParams struct {
	AccountID  uuid.UUID
	TripID     uuid.UUID
	DateFrom   *time.Time
	DateTo     *time.Time
	CategoryID uuid.NullUUID
	CursorDate *time.Time
	SplitMode  *string
	RowLimit   int32
}

type LedgerDailyTotalsRow struct {
	OccurredOn    time.Time
	ExpenseAmount string
	RefundAmount  string
}

// 每日明细：只含有账目的日期，按日期降序，游标取更早的日期。
func (q *Queries) LedgerDailyTotals(ctx context.Context, arg LedgerDailyTotalsParams) ([]LedgerDailyTotalsRow, error) {
	rows, err := q.db.Query(ctx, ledgerDailyTotals,
		arg.AccountID,
		arg.TripID,
		arg.DateFrom,
		arg.DateTo,
		arg.CategoryID,
		arg.CursorDate,
		arg.SplitMode,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerDailyTotalsRow{}
	for rows.Next() {
		var i LedgerDailyTotalsRow
		if err := rows.Scan(&i.OccurredOn, &i.ExpenseAmount, &i.RefundAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ledgerEntryIDExists = `-- name: LedgerEntryIDExists :one
SELECT EXISTS (SELECT 1 FROM ledger_entries l WHERE l.id = $1)
    OR EXISTS (SELECT 1 FROM entity_tombstones et WHERE et.account_id = $2 AND et.entity_type = 'ledger_entry' AND et.entity_id = $1) AS exists
`

type LedgerEntryIDExistsParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) LedgerEntryIDExists(ctx context.Context, arg LedgerEntryIDExistsParams) (*bool, error) {
	row := q.db.QueryRow(ctx, ledgerEntryIDExists, arg.ID, arg.AccountID)
	var exists *bool
	err := row.Scan(&exists)
	return exists, err
}

const ledgerFilteredTotals = `-- name: LedgerFilteredTotals :one
SELECT COALESCE(SUM(CASE WHEN kind = 'expense' THEN personal_amount END), 0)::numeric AS expense_amount,
       COALESCE(SUM(CASE WHEN kind = 'refund' THEN personal_amount END), 0)::numeric AS refund_amount,
       count(*) AS entry_count
FROM ledger_entries
WHERE account_id = $1 AND trip_id = $2 AND deleted_at IS NULL
  AND ($3::date IS NULL OR occurred_on >= $3::date)
  AND ($4::date IS NULL OR occurred_on <= $4::date)
  AND ($5::uuid IS NULL OR category_id = $5::uuid)
  AND ($6::text IS NULL OR split_mode = $6::text)
`

type LedgerFilteredTotalsParams struct {
	AccountID  uuid.UUID
	TripID     uuid.UUID
	DateFrom   *time.Time
	DateTo     *time.Time
	CategoryID uuid.NullUUID
	SplitMode  *string
}

type LedgerFilteredTotalsRow struct {
	ExpenseAmount string
	RefundAmount  string
	EntryCount    int64
}

// 统计（数据库设计 §5）：净额用 CASE 聚合，按实际 occurred_on；支出与退款都取「我」的份额 personal_amount；下面四条在同一个只读一致性事务中执行。
func (q *Queries) LedgerFilteredTotals(ctx context.Context, arg LedgerFilteredTotalsParams) (LedgerFilteredTotalsRow, error) {
	row := q.db.QueryRow(ctx, ledgerFilteredTotals,
		arg.AccountID,
		arg.TripID,
		arg.DateFrom,
		arg.DateTo,
		arg.CategoryID,
		arg.SplitMode,
	)
	var i LedgerFilteredTotalsRow
	err := row.Scan(&i.ExpenseAmount, &i.RefundAmount, &i.EntryCount)
	return i, err
}

const ledgerTripTotals = `-- name: LedgerTripTotals :one
SELECT COALESCE(SUM(CASE WHEN kind = 'expense' THEN personal_amount END), 0)::numeric AS expense_amount,
       COALESCE(SUM(CASE WHEN kind = 'refund' THEN personal_amount END), 0)::numeric AS refund_amount
FROM ledger_entries
WHERE account_id = $1 AND trip_id = $2 AND deleted_at IS NULL
`

type LedgerTripTotalsParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
}

type LedgerTripTotalsRow struct {
	ExpenseAmount string
	RefundAmount  string
}

func (q *Queries) LedgerTripTotals(ctx context.Context, arg LedgerTripTotalsParams) (LedgerTripTotalsRow, error) {
	row := q.db.QueryRow(ctx, ledgerTripTotals, arg.AccountID, arg.TripID)
	var i LedgerTripTotalsRow
	err := row.Scan(&i.ExpenseAmount, &i.RefundAmount)
	return i, err
}

const listLedgerAttachments = `-- name: ListLedgerAttachments :many
SELECT ledger_entry_id, asset_id FROM ledger_attachments
WHERE account_id = $1 AND trip_id = $2 AND ledger_entry_id = ANY($3::uuid[])
ORDER BY ledger_entry_id, sort_order, asset_id
`

type ListLedgerAttachmentsParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	EntryIds  []uuid.UUID
}

type ListLedgerAttachmentsRow struct {
	LedgerEntryID uuid.UUID
	AssetID       uuid.UUID
}

func (q *Queries) ListLedgerAttachments(ctx context.Context, arg ListLedgerAttachmentsParams) ([]ListLedgerAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listLedgerAttachments, arg.AccountID, arg.TripID, arg.EntryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLedgerAttachmentsRow{}
	for rows.Next() {
		var i ListLedgerAttachmentsRow
		if err := rows.Scan(&i.LedgerEntryID, &i.AssetID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntries = `-- name: ListLedgerEntries :many
SELECT l.id, l.account_id, l.version, l.created_at, l.updated_at, l.deleted_at, l.trip_id, l.kind, l.amount, l.category_id, l.occurred_on, l.notes, l.refunded_entry_id, l.split_count, l.personal_amount, l.payer_member_id, l.split_mode, t.currency_code
FROM ledger_entries l
JOIN trips t ON t.account_id = l.account_id AND t.id = l.trip_id
WHERE l.account_id = $1 AND l.trip_id = $2 AND l.deleted_at IS NULL
  AND ($3::date IS NULL OR l.occurred_on >= $3::date)
  AND ($4::date IS NULL OR l.occurred_on <= $4::date)
  AND ($5::uuid IS NULL OR l.category_id = $5::uuid)
  AND ($6::text IS NULL OR l.kind = $6::text)
  AND ($7::text IS NULL OR l.split_mode = $7::text)
  AND ($8::uuid IS NULL OR l.refunded_entry_id = $8::uuid)
  AND ($9::boolean IS NULL OR $9::boolean = EXISTS (
      SELECT 1 FROM ledger_entries r
      WHERE r.account_id = l.account_id AND r.trip_id = l.trip_id AND r.refunded_entry_id = l.id
        AND r.kind = 'refund' AND r.deleted_at IS NULL
  ))
  AND ($10::date IS NULL
       OR (l.occurred_on, l.id) < ($10::date, $11::uuid))
ORDER BY l.occurred_on DESC, l.id DESC
LIMIT $12
`

type ListLedgerEntriesParams struct {
	AccountID        uuid.UUID
	TripID           uuid.UUID
	DateFrom         *time.Time
	DateTo           *time.Time
	CategoryID       uuid.NullUUID
	Kind             *string
	SplitMode        *string
	RefundedEntryID  uuid.NullUUID
	HasRefunds       *bool
	CursorOccurredOn *time.Time
	CursorID         uuid.NullUUID
	RowLimit         int32
}

type ListLedgerEntriesRow struct {
	LedgerEntry  LedgerEntry
	CurrencyCode string
}

// 列表：接口设计 3.9 LedgerFilters；游标用行比较走 (account_id, trip_id, occurred_on DESC, id DESC) 部分索引。
func (q *Queries) ListLedgerEntries(ctx context.Context, arg ListLedgerEntriesParams) ([]ListLedgerEntriesRow, error) {
	rows, err := q.db.Query(ctx, listLedgerEntries,
		arg.AccountID,
		arg.TripID,
		arg.DateFrom,
		arg.DateTo,
		arg.CategoryID,
		arg.Kind,
		arg.SplitMode,
		arg.RefundedEntryID,
		arg.HasRefunds,
		arg.CursorOccurredOn,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLedgerEntriesRow{}
	for rows.Next() {
		var i ListLedgerEntriesRow
		if err := rows.Scan(
			&i.LedgerEntry.ID,
			&i.LedgerEntry.AccountID,
			&i.LedgerEntry.Version,
			&i.LedgerEntry.CreatedAt,
			&i.LedgerEntry.UpdatedAt,
			&i.LedgerEntry.DeletedAt,
			&i.LedgerEntry.TripID,
			&i.LedgerEntry.Kind,
			&i.LedgerEntry.Amount,
			&i.LedgerEntry.CategoryID,
			&i.LedgerEntry.OccurredOn,
			&i.LedgerEntry.Notes,
			&i.LedgerEntry.RefundedEntryID,
			&i.LedgerEntry.SplitCount,
			&i.LedgerEntry.PersonalAmount,
			&i.LedgerEntry.PayerMemberID,
			&i.LedgerEntry.SplitMode,
			&i.CurrencyCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerSplits = `-- name: ListLedgerSplits :many
SELECT ledger_entry_id, member_id, amount FROM ledger_entry_splits
WHERE account_id = $1 AND trip_id = $2 AND ledger_entry_id = ANY($3::uuid[])
ORDER BY ledger_entry_id, sort_order, member_id
`

type ListLedgerSplitsParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	EntryIds  []uuid.UUID
}

type ListLedgerSplitsRow struct {
	LedgerEntryID uuid.UUID
	MemberID      uuid.UUID
	Amount        string
}

func (q *Queries) ListLedgerSplits(ctx context.Context, arg ListLedgerSplitsParams) ([]ListLedgerSplitsRow, error) {
	rows, err := q.db.Query(ctx, listLedgerSplits, arg.AccountID, arg.TripID, arg.EntryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLedgerSplitsRow{}
	for rows.Next() {
		var i ListLedgerSplitsRow
		if err := rows.Scan(&i.LedgerEntryID, &i.MemberID, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkedRefundsForUpdate = `-- name: ListLinkedRefundsForUpdate :many
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, kind, amount, category_id, occurred_on, notes, refunded_entry_id, split_count, personal_amount, payer_member_id, split_mode FROM ledger_entries
WHERE account_id = $1 AND trip_id = $2 AND refunded_entry_id = $3
  AND deleted_at IS NULL AND kind = 'refund'
ORDER BY created_at, id
FOR UPDATE
`

type ListLinkedRefundsForUpdateParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	ExpenseID uuid.NullUUID
}

// 关联到某原支出的全部有效退款并锁定，按创建时间、id 升序。
func (q *Queries) ListLinkedRefundsForUpdate(ctx context.Context, arg ListLinkedRefundsForUpdateParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLinkedRefundsForUpdate, arg.AccountID, arg.TripID, arg.ExpenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TripID,
			&i.Kind,
			&i.Amount,
			&i.CategoryID,
			&i.OccurredOn,
			&i.Notes,
			&i.RefundedEntryID,
			&i.SplitCount,
			&i.PersonalAmount,
			&i.PayerMemberID,
			&i.SplitMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripImageAssetIDs = `-- name: ListTripImageAssetIDs :many
SELECT id FROM assets
WHERE account_id = $1 AND trip_id = $2::uuid AND deleted_at IS NULL
  AND id = ANY($3::uuid[])
  AND COALESCE(media_type, declared_media_type, 'image/') LIKE 'image/%'
`

type ListTripImageAssetIDsParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	Ids       []uuid.UUID
}

// 票据引用校验：同账号同旅行、未删除的图片资产，状态不限。
func (q *Queries) ListTripImageAssetIDs(ctx context.Context, arg ListTripImageAssetIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listTripImageAssetIDs, arg.AccountID, arg.TripID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTripCurrencyLock = `-- name: SetTripCurrencyLock :one
UPDATE trips
SET currency_locked_at = $1, version = version + 1, updated_at = $2
WHERE account_id = $3 AND id = $4
RETURNING id, account_id, version, created_at, updated_at, deleted_at, name, start_date, end_date, destination, notes, timezone, currency_code, currency_locked_at, budget_amount, archived_at, purge_after_at, purge_requested_at, route_short_mode, route_short_distance_meters
`

type SetTripCurrencyLockParams struct {
	LockedAt  *time.Time
	UpdatedAt time.Time
	AccountID uuid.UUID
	ID        uuid.UUID
}

// 币种锁定与解锁：只改 currency_locked_at，递增旅行版本并返回整行作为同步快照。
func (q *Queries) SetTripCurrencyLock(ctx context.Context, arg SetTripCurrencyLockParams) (Trip, error) {
	row := q.db.QueryRow(ctx, setTripCurrencyLock,
		arg.LockedAt,
		arg.UpdatedAt,
		arg.AccountID,
		arg.ID,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Destination,
		&i.Notes,
		&i.Timezone,
		&i.CurrencyCode,
		&i.CurrencyLockedAt,
		&i.BudgetAmount,
		&i.ArchivedAt,
		&i.PurgeAfterAt,
		&i.PurgeRequestedAt,
		&i.RouteShortMode,
		&i.RouteShortDistanceMeters,
	)
	return i, err
}

const softDeleteLedgerEntry = `-- name: SoftDeleteLedgerEntry :one
UPDATE ledger_entries
SET deleted_at = $1, version = version + 1, updated_at = $1
WHERE account_id = $2 AND trip_id = $3 AND id = $4
RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, kind, amount, category_id, occurred_on, notes, refunded_entry_id, split_count, personal_amount, payer_member_id, split_mode
`

type SoftDeleteLedgerEntryParams struct {
	DeletedAt *time.Time
	AccountID uuid.UUID
	TripID    uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteLedgerEntry(ctx context.Context, arg SoftDeleteLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, softDeleteLedgerEntry,
		arg.DeletedAt,
		arg.AccountID,
		arg.TripID,
		arg.ID,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Kind,
		&i.Amount,
		&i.CategoryID,
		&i.OccurredOn,
		&i.Notes,
		&i.RefundedEntryID,
		&i.SplitCount,
		&i.PersonalAmount,
		&i.PayerMemberID,
		&i.SplitMode,
	)
	return i, err
}

const updateLedgerEntry = `-- name: UpdateLedgerEntry :one
UPDATE ledger_entries
SET amount = $1, split_count = $2, personal_amount = $3, payer_member_id = $4, split_mode = $5,
    category_id = $6, occurred_on = $7, notes = $8,
    refunded_entry_id = $9, version = version + 1, updated_at = $10
WHERE account_id = $11 AND trip_id = $12 AND id = $13
RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, kind, amount, category_id, occurred_on, notes, refunded_entry_id, split_count, personal_amount, payer_member_id, split_mode
`

type UpdateLedgerEntryParams struct {
	Amount          string
	SplitCount      int32
	PersonalAmount  string
	PayerMemberID   uuid.UUID
	SplitMode       string
	CategoryID      uuid.UUID
	OccurredOn      time.Time
	Notes           string
	RefundedEntryID uuid.NullUUID
	UpdatedAt       time.Time
	AccountID       uuid.UUID
	TripID          uuid.UUID
	ID              uuid.UUID
}

func (q *Queries) UpdateLedgerEntry(ctx context.Context, arg UpdateLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, updateLedgerEntry,
		arg.Amount,
		arg.SplitCount,
		arg.PersonalAmount,
		arg.PayerMemberID,
		arg.SplitMode,
		arg.CategoryID,
		arg.OccurredOn,
		arg.Notes,
		arg.RefundedEntryID,
		arg.UpdatedAt,
		arg.AccountID,
		arg.TripID,
		arg.ID,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Kind,
		&i.Amount,
		&i.CategoryID,
		&i.OccurredOn,
		&i.Notes,
		&i.RefundedEntryID,
		&i.SplitCount,
		&i.PersonalAmount,
		&i.PayerMemberID,
		&i.SplitMode,
	)
	return i, err
}
