// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countTripMemberReferences = `-- name: CountTripMemberReferences :one
SELECT count(*) FROM ledger_entries l
WHERE l.account_id = $1 AND l.trip_id = $2 AND l.deleted_at IS NULL
  AND (l.payer_member_id = $3
       OR EXISTS (SELECT 1 FROM ledger_entry_splits s
                  WHERE s.account_id = l.account_id AND s.trip_id = l.trip_id AND s.ledger_entry_id = l.id AND s.member_id = $3))
`

type CountTripMemberReferencesParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	MemberID  uuid.UUID
}

// 删除前的引用检查：有效账目的付款人或分摊参与人。
func (q *Queries) CountTripMemberReferences(ctx context.Context, arg CountTripMemberReferencesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTripMemberReferences, arg.AccountID, arg.TripID, arg.MemberID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTripMember = `-- name: GetTripMember :one

SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, name, share_percent, sort_order, is_self FROM trip_members
WHERE account_id = $1 AND trip_id = $2 AND id = $3
`

type GetTripMemberParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	ID        uuid.UUID
}

// 旅行成员（数据库设计表 25）。percent 为 NUMERIC(5,2)，适配器按 2 位小数转回字符串。
func (q *Queries) GetTripMember(ctx context.Context, arg GetTripMemberParams) (TripMember, error) {
	row := q.db.QueryRow(ctx, getTripMember, arg.AccountID, arg.TripID, arg.ID)
	var i TripMember
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Name,
		&i.SharePercent,
		&i.SortOrder,
		&i.IsSelf,
	)
	return i, err
}

const insertTripMember = `-- name: InsertTripMember :one
INSERT INTO trip_members (id, account_id, trip_id, name, share_percent, sort_order, is_self, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $8)
RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, name, share_percent, sort_order, is_self
`

type InsertTripMemberParams struct {
	ID           uuid.UUID
	AccountID    uuid.UUID
	TripID       uuid.UUID
	Name         string
	SharePercent string
	SortOrder    int32
	IsSelf       bool
	CreatedAt    time.Time
}

func (q *Queries) InsertTripMember(ctx context.Context, arg InsertTripMemberParams) (TripMember, error) {
	row := q.db.QueryRow(ctx, insertTripMember,
		arg.ID,
		arg.AccountID,
		arg.TripID,
		arg.Name,
		arg.SharePercent,
		arg.SortOrder,
		arg.IsSelf,
		arg.CreatedAt,
	)
	var i TripMember
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Name,
		&i.SharePercent,
		&i.SortOrder,
		&i.IsSelf,
	)
	return i, err
}

const listTripMembers = `-- name: ListTripMembers :many
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, name, share_percent, sort_order, is_self FROM trip_members
WHERE account_id = $1 AND trip_id = $2 AND deleted_at IS NULL
ORDER BY sort_order, id
`

type ListTripMembersParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
}

// 有效成员按 sort_order、id 升序。
func (q *Queries) ListTripMembers(ctx context.Context, arg ListTripMembersParams) ([]TripMember, error) {
	rows, err := q.db.Query(ctx, listTripMembers, arg.AccountID, arg.TripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TripMember{}
	for rows.Next() {
		var i TripMember
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TripID,
			&i.Name,
			&i.SharePercent,
			&i.SortOrder,
			&i.IsSelf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripMembersForUpdate = `-- name: ListTripMembersForUpdate :many
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, name, share_percent, sort_order, is_self FROM trip_members
WHERE account_id = $1 AND trip_id = $2 AND deleted_at IS NULL
ORDER BY sort_order, id
FOR UPDATE
`

type ListTripMembersForUpdateParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
}

// 整体保存前锁定本旅行全部有效成员。
func (q *Queries) ListTripMembersForUpdate(ctx context.Context, arg ListTripMembersForUpdateParams) ([]TripMember, error) {
	rows, err := q.db.Query(ctx, listTripMembersForUpdate, arg.AccountID, arg.TripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TripMember{}
	for rows.Next() {
		var i TripMember
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TripID,
			&i.Name,
			&i.SharePercent,
			&i.SortOrder,
			&i.IsSelf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTripMember = `-- name: SoftDeleteTripMember :one
UPDATE trip_members
SET deleted_at = $1, version = version + 1, updated_at = $1
WHERE account_id = $2 AND trip_id = $3 AND id = $4
RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, name, share_percent, sort_order, is_self
`

type SoftDeleteTripMemberParams struct {
	DeletedAt *time.Time
	AccountID uuid.UUID
	TripID    uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteTripMember(ctx context.Context, arg SoftDeleteTripMemberParams) (TripMember, error) {
	row := q.db.QueryRow(ctx, softDeleteTripMember,
		arg.DeletedAt,
		arg.AccountID,
		arg.TripID,
		arg.ID,
	)
	var i TripMember
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Name,
		&i.SharePercent,
		&i.SortOrder,
		&i.IsSelf,
	)
	return i, err
}

const tripMemberIDExists = `-- name: TripMemberIDExists :one
SELECT EXISTS (SELECT 1 FROM trip_members m WHERE m.id = $1)
    OR EXISTS (SELECT 1 FROM entity_tombstones et WHERE et.account_id = $2 AND et.entity_type = 'trip_member' AND et.entity_id = $1) AS exists
`

type TripMemberIDExistsParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) TripMemberIDExists(ctx context.Context, arg TripMemberIDExistsParams) (*bool, error) {
	row := q.db.QueryRow(ctx, tripMemberIDExists, arg.ID, arg.AccountID)
	var exists *bool
	err := row.Scan(&exists)
	return exists, err
}

const tripMemberSettlement = `-- name: TripMemberSettlement :many
SELECT m.id AS member_id, m.name, m.is_self,
       COALESCE((SELECT SUM(CASE WHEN l.kind = 'expense' THEN l.amount ELSE -l.amount END) FROM ledger_entries l
                 WHERE l.account_id = m.account_id AND l.trip_id = m.trip_id AND l.payer_member_id = m.id AND l.deleted_at IS NULL AND l.split_mode <> 'personal'), 0)::numeric AS paid_amount,
       COALESCE((SELECT SUM(CASE WHEN l.kind = 'expense' THEN s.amount ELSE -s.amount END) FROM ledger_entry_splits s
                 JOIN ledger_entries l ON l.account_id = s.account_id AND l.trip_id = s.trip_id AND l.id = s.ledger_entry_id
                 WHERE s.account_id = m.account_id AND s.trip_id = m.trip_id AND s.member_id = m.id AND l.deleted_at IS NULL AND l.split_mode <> 'personal'), 0)::numeric AS owed_amount
FROM trip_members m
WHERE m.account_id = $1 AND m.trip_id = $2 AND m.deleted_at IS NULL
ORDER BY m.sort_order, m.id
`

type TripMemberSettlementParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
}

type TripMemberSettlementRow struct {
	MemberID   uuid.UUID
	Name       string
	IsSelf     bool
	PaidAmount string
	OwedAmount string
}

// 成员结算（接口设计 3.8 TripSettlement）：每位有效成员作为付款人与参与人的支出、退款合计。
func (q *Queries) TripMemberSettlement(ctx context.Context, arg TripMemberSettlementParams) ([]TripMemberSettlementRow, error) {
	rows, err := q.db.Query(ctx, tripMemberSettlement, arg.AccountID, arg.TripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TripMemberSettlementRow{}
	for rows.Next() {
		var i TripMemberSettlementRow
		if err := rows.Scan(
			&i.MemberID,
			&i.Name,
			&i.IsSelf,
			&i.PaidAmount,
			&i.OwedAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTripMember = `-- name: UpdateTripMember :one
UPDATE trip_members
SET name = $1, share_percent = $2, sort_order = $3,
    version = version + 1, updated_at = $4
WHERE account_id = $5 AND trip_id = $6 AND id = $7
RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, name, share_percent, sort_order, is_self
`

type UpdateTripMemberParams struct {
	Name         string
	SharePercent string
	SortOrder    int32
	UpdatedAt    time.Time
	AccountID    uuid.UUID
	TripID       uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) UpdateTripMember(ctx context.Context, arg UpdateTripMemberParams) (TripMember, error) {
	row := q.db.QueryRow(ctx, updateTripMember,
		arg.Name,
		arg.SharePercent,
		arg.SortOrder,
		arg.UpdatedAt,
		arg.AccountID,
		arg.TripID,
		arg.ID,
	)
	var i TripMember
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Name,
		&i.SharePercent,
		&i.SortOrder,
		&i.IsSelf,
	)
	return i, err
}
