// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID                uuid.UUID
	Email             string
	EmailKey          string
	EmailVerifiedAt   time.Time
	PasswordHash      string
	PasswordChangedAt time.Time
	Nickname          string
	AvatarAssetID     uuid.NullUUID
	DefaultTimezone   string
	Status            string
	Version           int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type AccountSession struct {
	ID                       uuid.UUID
	AccountID                uuid.UUID
	ClientKind               string
	DeviceID                 uuid.UUID
	DeviceName               *string
	RefreshTokenHash         []byte
	PreviousRefreshTokenHash []byte
	PreviousRotatedAt        *time.Time
	CsrfTokenHash            []byte
	ReauthenticatedAt        *time.Time
	CreatedAt                time.Time
	LastSeenAt               time.Time
	ExpiresAt                time.Time
	RevokedAt                *time.Time
}

type AccountSyncState struct {
	AccountID        uuid.UUID
	LastSeq          int64
	RetainedAfterSeq int64
	UpdatedAt        time.Time
}

type Asset struct {
	ID                 uuid.UUID
	AccountID          uuid.UUID
	Version            int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          *time.Time
	Scope              string
	TripID             uuid.NullUUID
	OriginalName       string
	Status             string
	UploadAttempt      int32
	StagingObjectKey   *string
	ExpectedSize       *int64
	DeclaredMediaType  *string
	ClientSha256       []byte
	UploadExpiresAt    *time.Time
	ConfirmedAt        *time.Time
	MediaType          *string
	ByteSize           *int64
	Sha256             []byte
	ObjectKey          *string
	ThumbnailObjectKey *string
	ThumbnailStatus    string
	Width              *int32
	Height             *int32
	ExifTakenAtLocal   *time.Time
	ExifLatitude       *string
	ExifLongitude      *string
	ErrorCode          *string
	UnreferencedSince  *time.Time
}

type AuthChallenge struct {
	ID             uuid.UUID
	Purpose        string
	EmailKey       string
	CodeMac        []byte
	KeyID          string
	Attempts       int16
	DeliveryStatus string
	CreatedAt      time.Time
	ExpiresAt      time.Time
	ConsumedAt     *time.Time
	InvalidatedAt  *time.Time
}

type DataSnapshot struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	Purpose         string
	SelectedTripIds []byte
	Status          string
	HighWaterSeq    *int64
	ItemCount       int64
	SchemaVersion   int16
	ErrorCode       *string
	CreatedAt       time.Time
	CapturedAt      *time.Time
	ExpiresAt       time.Time
}

type DeletionJob struct {
	ID               uuid.UUID
	OwnerAccountID   uuid.UUID
	Scope            string
	TargetTripID     uuid.NullUUID
	Status           string
	Stage            string
	ProcessedItems   int64
	TotalItems       *int64
	ReceiptTokenHash []byte
	ReceiptExpiresAt *time.Time
	ErrorCode        *string
	CreatedAt        time.Time
	StartedAt        *time.Time
	FinishedAt       *time.Time
	RetainUntil      *time.Time
}

type Document struct {
	ID            uuid.UUID
	AccountID     uuid.UUID
	Version       int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
	TripID        uuid.UUID
	Title         string
	Notes         string
	AssetID       uuid.UUID
	ReservationID uuid.NullUUID
}

type EntityTombstone struct {
	AccountID   uuid.UUID
	EntityType  string
	EntityID    uuid.UUID
	TripID      uuid.NullUUID
	LastVersion int64
	DeletedAt   time.Time
	PurgedAt    time.Time
}

type ExpenseCategory struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
	Name      string
	Icon      *string
	SortOrder int32
	IsPreset  bool
}

type ExportJob struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	Format          string
	Scope           string
	SelectedTripIds []byte
	Filters         []byte
	SnapshotID      uuid.NullUUID
	Status          string
	ProcessedItems  int64
	TotalItems      *int64
	ObjectKey       *string
	ByteSize        *int64
	Sha256          []byte
	ErrorCode       *string
	CapturedAt      *time.Time
	CreatedAt       time.Time
	FinishedAt      *time.Time
	ExpiresAt       *time.Time
}

type ItineraryItem struct {
	ID                     uuid.UUID
	AccountID              uuid.UUID
	Version                int64
	CreatedAt              time.Time
	UpdatedAt              time.Time
	DeletedAt              *time.Time
	TripID                 uuid.UUID
	Title                  string
	Kind                   string
	ScheduledOn            time.Time
	SortOrder              int32
	PlannedStartLocal      *time.Time
	PlannedEndLocal        *time.Time
	PlannedDurationMinutes *int32
	PlaceName              string
	Address                string
	Latitude               *string
	Longitude              *string
	EstimatedAmount        *string
	Notes                  string
	Status                 string
	ActualStartLocal       *time.Time
	ActualEndLocal         *time.Time
	ActualNotes            string
}

type LedgerAttachment struct {
	AccountID     uuid.UUID
	TripID        uuid.UUID
	LedgerEntryID uuid.UUID
	AssetID       uuid.UUID
	SortOrder     int32
	CreatedAt     time.Time
}

type LedgerEntry struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	Version         int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       *time.Time
	TripID          uuid.UUID
	Kind            string
	Amount          string
	CategoryID      uuid.UUID
	OccurredOn      time.Time
	Notes           string
	RefundedEntryID uuid.NullUUID
}

type MutationReceipt struct {
	AccountID     uuid.UUID
	OperationID   uuid.UUID
	OperationType string
	RequestHash   []byte
	Result        []byte
	CreatedAt     time.Time
}

type PackingItem struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
	TripID    uuid.UUID
	Name      string
	Category  string
	Quantity  int32
	Notes     string
	Status    string
}

type Photo struct {
	ID           uuid.UUID
	AccountID    uuid.UUID
	Version      int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    *time.Time
	TripID       uuid.UUID
	AssetID      uuid.UUID
	TakenAtLocal *time.Time
	RecordedOn   time.Time
	Caption      string
	SortOrder    int32
	PlaceName    string
	Address      string
	Latitude     *string
	Longitude    *string
}

type Reservation struct {
	ID               uuid.UUID
	AccountID        uuid.UUID
	Version          int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        *time.Time
	TripID           uuid.UUID
	Kind             string
	Title            string
	BookingReference string
	TransportNumber  *string
	ProviderName     *string
	StartLocal       *time.Time
	EndLocal         *time.Time
	Origin           *string
	Destination      *string
	Address          string
	ContactName      *string
	ContactPhone     *string
	Notes            string
}

type SnapshotAssetRef struct {
	SnapshotID uuid.UUID
	AccountID  uuid.UUID
	AssetID    uuid.UUID
}

type SnapshotItem struct {
	SnapshotID    uuid.UUID
	AccountID     uuid.UUID
	Ordinal       int64
	TripID        uuid.NullUUID
	EntityType    string
	EntityID      uuid.UUID
	EntityVersion int64
	Payload       []byte
}

type SyncChange struct {
	AccountID        uuid.UUID
	Seq              int64
	BatchID          uuid.UUID
	BatchEndSeq      int64
	EntityType       string
	EntityID         uuid.UUID
	TripID           uuid.NullUUID
	EntityVersion    int64
	ChangeKind       string
	SchemaVersion    int16
	Snapshot         []byte
	ChangedFields    []string
	RequiresSnapshot bool
	CreatedAt        time.Time
}

type TodoItem struct {
	ID          uuid.UUID
	AccountID   uuid.UUID
	Version     int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
	TripID      uuid.UUID
	Title       string
	DueOn       *time.Time
	Notes       string
	CompletedAt *time.Time
}

type Trip struct {
	ID               uuid.UUID
	AccountID        uuid.UUID
	Version          int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        *time.Time
	Name             string
	StartDate        time.Time
	EndDate          time.Time
	Destination      string
	Notes            string
	Timezone         string
	CurrencyCode     string
	CurrencyLockedAt *time.Time
	BudgetAmount     *string
	ArchivedAt       *time.Time
	PurgeAfterAt     *time.Time
	PurgeRequestedAt *time.Time
}
