// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: packing.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPackingItem = `-- name: GetPackingItem :one

SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, name, category, quantity, notes, status FROM packing_items
WHERE account_id = $1 AND trip_id = $2 AND id = $3
`

type GetPackingItemParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	ID        uuid.UUID
}

// 行李清单物品（数据库设计表 6）。同分类同名唯一由部分唯一索引兜底，应用层先用 PackingNameTaken 预检以返回 422。
func (q *Queries) GetPackingItem(ctx context.Context, arg GetPackingItemParams) (PackingItem, error) {
	row := q.db.QueryRow(ctx, getPackingItem, arg.AccountID, arg.TripID, arg.ID)
	var i PackingItem
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Name,
		&i.Category,
		&i.Quantity,
		&i.Notes,
		&i.Status,
	)
	return i, err
}

const getPackingItemForUpdate = `-- name: GetPackingItemForUpdate :one
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, name, category, quantity, notes, status FROM packing_items
WHERE account_id = $1 AND trip_id = $2 AND id = $3
FOR UPDATE
`

type GetPackingItemForUpdateParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetPackingItemForUpdate(ctx context.Context, arg GetPackingItemForUpdateParams) (PackingItem, error) {
	row := q.db.QueryRow(ctx, getPackingItemForUpdate, arg.AccountID, arg.TripID, arg.ID)
	var i PackingItem
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Name,
		&i.Category,
		&i.Quantity,
		&i.Notes,
		&i.Status,
	)
	return i, err
}

const insertPackingItem = `-- name: InsertPackingItem :one
INSERT INTO packing_items (id, account_id, trip_id, name, category, quantity, notes, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $9)
RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, name, category, quantity, notes, status
`

type InsertPackingItemParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	TripID    uuid.UUID
	Name      string
	Category  string
	Quantity  int32
	Notes     string
	Status    string
	CreatedAt time.Time
}

func (q *Queries) InsertPackingItem(ctx context.Context, arg InsertPackingItemParams) (PackingItem, error) {
	row := q.db.QueryRow(ctx, insertPackingItem,
		arg.ID,
		arg.AccountID,
		arg.TripID,
		arg.Name,
		arg.Category,
		arg.Quantity,
		arg.Notes,
		arg.Status,
		arg.CreatedAt,
	)
	var i PackingItem
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Name,
		&i.Category,
		&i.Quantity,
		&i.Notes,
		&i.Status,
	)
	return i, err
}

const listPackingItems = `-- name: ListPackingItems :many
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, name, category, quantity, notes, status FROM packing_items
WHERE account_id = $1 AND trip_id = $2 AND deleted_at IS NULL
  AND ($3::text IS NULL OR category = $3::text)
  AND ($4::text IS NULL OR status = $4::text)
  AND ($5::text IS NULL
       OR (category, created_at, id) > ($5::text, $6::timestamptz, $7::uuid))
ORDER BY category, created_at, id
LIMIT $8
`

type ListPackingItemsParams struct {
	AccountID       uuid.UUID
	TripID          uuid.UUID
	Category        *string
	Status          *string
	CursorCategory  *string
	CursorCreatedAt *time.Time
	CursorID        uuid.NullUUID
	RowLimit        int32
}

// 列表：接口设计 3.9 PackingFilters；游标走 (account_id, trip_id, category, created_at, id) 部分索引。
func (q *Queries) ListPackingItems(ctx context.Context, arg ListPackingItemsParams) ([]PackingItem, error) {
	rows, err := q.db.Query(ctx, listPackingItems,
		arg.AccountID,
		arg.TripID,
		arg.Category,
		arg.Status,
		arg.CursorCategory,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PackingItem{}
	for rows.Next() {
		var i PackingItem
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TripID,
			&i.Name,
			&i.Category,
			&i.Quantity,
			&i.Notes,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const packingItemIDExists = `-- name: PackingItemIDExists :one
SELECT EXISTS (SELECT 1 FROM packing_items p WHERE p.id = $1)
    OR EXISTS (SELECT 1 FROM entity_tombstones et WHERE et.account_id = $2 AND et.entity_type = 'packing_item' AND et.entity_id = $1) AS exists
`

type PackingItemIDExistsParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) PackingItemIDExists(ctx context.Context, arg PackingItemIDExistsParams) (*bool, error) {
	row := q.db.QueryRow(ctx, packingItemIDExists, arg.ID, arg.AccountID)
	var exists *bool
	err := row.Scan(&exists)
	return exists, err
}

const packingNameTaken = `-- name: PackingNameTaken :one
SELECT EXISTS (
    SELECT 1 FROM packing_items
    WHERE account_id = $1 AND trip_id = $2 AND deleted_at IS NULL
      AND category = $3 AND lower(btrim(name)) = lower(btrim($4::text))
      AND id <> $5
) AS exists
`

type PackingNameTakenParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	Category  string
	Name      string
	ExcludeID uuid.UUID
}

func (q *Queries) PackingNameTaken(ctx context.Context, arg PackingNameTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, packingNameTaken,
		arg.AccountID,
		arg.TripID,
		arg.Category,
		arg.Name,
		arg.ExcludeID,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeletePackingItem = `-- name: SoftDeletePackingItem :one
UPDATE packing_items
SET deleted_at = $1, version = version + 1, updated_at = $1
WHERE account_id = $2 AND trip_id = $3 AND id = $4
RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, name, category, quantity, notes, status
`

type SoftDeletePackingItemParams struct {
	DeletedAt *time.Time
	AccountID uuid.UUID
	TripID    uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeletePackingItem(ctx context.Context, arg SoftDeletePackingItemParams) (PackingItem, error) {
	row := q.db.QueryRow(ctx, softDeletePackingItem,
		arg.DeletedAt,
		arg.AccountID,
		arg.TripID,
		arg.ID,
	)
	var i PackingItem
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Name,
		&i.Category,
		&i.Quantity,
		&i.Notes,
		&i.Status,
	)
	return i, err
}

const updatePackingItem = `-- name: UpdatePackingItem :one
UPDATE packing_items
SET name = $1, category = $2, quantity = $3, notes = $4, status = $5,
    version = version + 1, updated_at = $6
WHERE account_id = $7 AND trip_id = $8 AND id = $9
RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, name, category, quantity, notes, status
`

type UpdatePackingItemParams struct {
	Name      string
	Category  string
	Quantity  int32
	Notes     string
	Status    string
	UpdatedAt time.Time
	AccountID uuid.UUID
	TripID    uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) UpdatePackingItem(ctx context.Context, arg UpdatePackingItemParams) (PackingItem, error) {
	row := q.db.QueryRow(ctx, updatePackingItem,
		arg.Name,
		arg.Category,
		arg.Quantity,
		arg.Notes,
		arg.Status,
		arg.UpdatedAt,
		arg.AccountID,
		arg.TripID,
		arg.ID,
	)
	var i PackingItem
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Name,
		&i.Category,
		&i.Quantity,
		&i.Notes,
		&i.Status,
	)
	return i, err
}

const updatePackingStatusIfVersion = `-- name: UpdatePackingStatusIfVersion :one
UPDATE packing_items p
SET status = $1, version = p.version + 1, updated_at = $2
WHERE p.account_id = $3 AND p.trip_id = $4 AND p.id = $5
  AND p.version = $6 AND p.deleted_at IS NULL
  AND EXISTS (SELECT 1 FROM trips t WHERE t.account_id = p.account_id AND t.id = p.trip_id AND t.deleted_at IS NULL)
RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, name, category, quantity, notes, status
`

type UpdatePackingStatusIfVersionParams struct {
	Status    string
	UpdatedAt time.Time
	AccountID uuid.UUID
	TripID    uuid.UUID
	ID        uuid.UUID
	Version   int64
}

func (q *Queries) UpdatePackingStatusIfVersion(ctx context.Context, arg UpdatePackingStatusIfVersionParams) (PackingItem, error) {
	row := q.db.QueryRow(ctx, updatePackingStatusIfVersion,
		arg.Status,
		arg.UpdatedAt,
		arg.AccountID,
		arg.TripID,
		arg.ID,
		arg.Version,
	)
	var i PackingItem
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Name,
		&i.Category,
		&i.Quantity,
		&i.Notes,
		&i.Status,
	)
	return i, err
}
