// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AccountExistsByEmailKey(ctx context.Context, emailKey string) (bool, error)
	AdvanceAccountSeq(ctx context.Context, arg AdvanceAccountSeqParams) error
	AssetIDExists(ctx context.Context, arg AssetIDExistsParams) (*bool, error)
	ChangedFieldsBetweenVersions(ctx context.Context, arg ChangedFieldsBetweenVersionsParams) ([]ChangedFieldsBetweenVersionsRow, error)
	ConsumeChallenge(ctx context.Context, arg ConsumeChallengeParams) error
	CountActiveLedgerEntries(ctx context.Context, arg CountActiveLedgerEntriesParams) (int64, error)
	CountChallengesSince(ctx context.Context, arg CountChallengesSinceParams) (int64, error)
	CountExpenseCategories(ctx context.Context, accountID uuid.UUID) (int64, error)
	CountLedgerEntriesUsingCategory(ctx context.Context, arg CountLedgerEntriesUsingCategoryParams) (int64, error)
	// 删除前的引用检查：有效账目的付款人或分摊参与人。
	CountTripMemberReferences(ctx context.Context, arg CountTripMemberReferencesParams) (int64, error)
	// 账号基础查询。规范化邮箱 email_key 由服务端生成（去首尾空格、小写），不在 SQL 中处理。
	// 时间一律由应用时钟给出（数据库时钟可能与应用不一致，会触发 updated_at >= created_at 约束）。
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateAccountSyncState(ctx context.Context, accountID uuid.UUID) error
	CreateChallenge(ctx context.Context, arg CreateChallengeParams) (AuthChallenge, error)
	// 登录会话。摘要列只做常量时间比较，所有查找按主键。
	CreateSession(ctx context.Context, arg CreateSessionParams) (AccountSession, error)
	DeleteExpiredChallenges(ctx context.Context, expiresAt time.Time) (int64, error)
	// 票据引用：整体替换。
	DeleteLedgerAttachments(ctx context.Context, arg DeleteLedgerAttachmentsParams) error
	// 分摊份额：整体替换；amounts 与 member_ids 一一对应，顺序即 sort_order。
	DeleteLedgerSplits(ctx context.Context, arg DeleteLedgerSplitsParams) error
	DeleteRoutePlanLegs(ctx context.Context, arg DeleteRoutePlanLegsParams) error
	DeleteTripShare(ctx context.Context, arg DeleteTripShareParams) (int64, error)
	ExpenseCategoryActive(ctx context.Context, arg ExpenseCategoryActiveParams) (bool, error)
	ExpenseCategoryIDExists(ctx context.Context, id uuid.UUID) (bool, error)
	GetAccountByEmailKey(ctx context.Context, emailKey string) (Account, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountDefaultTimezone(ctx context.Context, accountID uuid.UUID) (string, error)
	GetAccountSyncState(ctx context.Context, accountID uuid.UUID) (AccountSyncState, error)
	GetActiveTripDeletionJob(ctx context.Context, arg GetActiveTripDeletionJobParams) (DeletionJob, error)
	GetAsset(ctx context.Context, arg GetAssetParams) (Asset, error)
	GetAssetForUpdate(ctx context.Context, arg GetAssetForUpdateParams) (Asset, error)
	// 私有文件资产（数据库设计表 14）。对象键由适配器按 account_id、asset_id、upload_attempt 推导后传入；
	// 暂存键、最终键、缩略图键与声明信息不进入公开模型，由独立查询按需读取。
	GetAssetTripInfo(ctx context.Context, arg GetAssetTripInfoParams) (*time.Time, error)
	// 批量读取保持输入顺序：unnest WITH ORDINALITY 再按序号排序，适配器据此判断缺失项。
	GetAssetsByIDs(ctx context.Context, arg GetAssetsByIDsParams) ([]Asset, error)
	GetChallengeForUpdate(ctx context.Context, id uuid.UUID) (AuthChallenge, error)
	GetExpenseCategory(ctx context.Context, arg GetExpenseCategoryParams) (ExpenseCategory, error)
	GetExpenseCategoryForUpdate(ctx context.Context, arg GetExpenseCategoryForUpdateParams) (ExpenseCategory, error)
	GetItineraryItem(ctx context.Context, arg GetItineraryItemParams) (ItineraryItem, error)
	GetItineraryItemForUpdate(ctx context.Context, arg GetItineraryItemForUpdateParams) (ItineraryItem, error)
	GetLedgerEntry(ctx context.Context, arg GetLedgerEntryParams) (GetLedgerEntryRow, error)
	GetLedgerEntryForUpdate(ctx context.Context, arg GetLedgerEntryForUpdateParams) (GetLedgerEntryForUpdateRow, error)
	// 账目与票据（数据库设计表 9、10）与开支统计（数据库设计 §5）。
	// currency_code 不存列，查询时从 trips 派生；金额 NUMERIC(18,4) 由适配器按币种小数位转回规范字符串。
	GetLedgerTripInfo(ctx context.Context, arg GetLedgerTripInfoParams) (GetLedgerTripInfoRow, error)
	GetMutationReceipt(ctx context.Context, arg GetMutationReceiptParams) (MutationReceipt, error)
	// 行李清单物品（数据库设计表 6）。同分类同名唯一由部分唯一索引兜底，应用层先用 PackingNameTaken 预检以返回 422。
	GetPackingItem(ctx context.Context, arg GetPackingItemParams) (PackingItem, error)
	GetPackingItemForUpdate(ctx context.Context, arg GetPackingItemForUpdateParams) (PackingItem, error)
	GetRoutePlanLegForUpdate(ctx context.Context, arg GetRoutePlanLegForUpdateParams) (ItineraryRouteLeg, error)
	// 旅行路线偏好、相邻路段与列表汇总。
	GetRoutePlanTrip(ctx context.Context, arg GetRoutePlanTripParams) (GetRoutePlanTripRow, error)
	GetRouteSummary(ctx context.Context, arg GetRouteSummaryParams) (TripRouteSummary, error)
	GetRouteSummaryForUpdate(ctx context.Context, arg GetRouteSummaryForUpdateParams) (TripRouteSummary, error)
	GetSession(ctx context.Context, id uuid.UUID) (AccountSession, error)
	GetSessionForUpdate(ctx context.Context, id uuid.UUID) (AccountSession, error)
	// 待办（数据库设计表 7）。逾期不落列，按应用传入的旅行时区“今天”在 SQL 中筛选；空截止日期用哨兵排在最后，与索引表达式一致。
	GetTodoItem(ctx context.Context, arg GetTodoItemParams) (TodoItem, error)
	GetTodoItemForUpdate(ctx context.Context, arg GetTodoItemForUpdateParams) (TodoItem, error)
	// 旅行与回收站。时间一律由应用时钟传入；阶段按旅行时区的“今天”在 SQL 中计算，使筛选与返回值一致。
	GetTrip(ctx context.Context, arg GetTripParams) (Trip, error)
	// 每日行程项目（数据库设计表 5）。时间由应用时钟传入；currency_code 不存列，由适配器按旅行币种派生。
	GetTripContentInfo(ctx context.Context, arg GetTripContentInfoParams) (GetTripContentInfoRow, error)
	GetTripForUpdate(ctx context.Context, arg GetTripForUpdateParams) (Trip, error)
	// 旅行成员（数据库设计表 25）。percent 为 NUMERIC(5,2)，适配器按 2 位小数转回字符串。
	GetTripMember(ctx context.Context, arg GetTripMemberParams) (TripMember, error)
	// 旅行分享（数据库设计 v0.4 表 24）。解析查询联出主人账号状态与旅行删除标记，访客侧一次查询完成全部前置判断。
	GetTripShareByTrip(ctx context.Context, arg GetTripShareByTripParams) (TripShare, error)
	IncrementChallengeAttempts(ctx context.Context, id uuid.UUID) error
	InitEmptyRouteSummary(ctx context.Context, arg InitEmptyRouteSummaryParams) error
	InsertAsset(ctx context.Context, arg InsertAssetParams) (Asset, error)
	// 账号级账单分类。
	InsertExpenseCategory(ctx context.Context, arg InsertExpenseCategoryParams) (ExpenseCategory, error)
	InsertItineraryItem(ctx context.Context, arg InsertItineraryItemParams) (ItineraryItem, error)
	InsertLedgerAttachments(ctx context.Context, arg InsertLedgerAttachmentsParams) error
	InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error)
	InsertLedgerSplits(ctx context.Context, arg InsertLedgerSplitsParams) error
	InsertMutationReceipt(ctx context.Context, arg InsertMutationReceiptParams) error
	InsertPackingItem(ctx context.Context, arg InsertPackingItemParams) (PackingItem, error)
	InsertRoutePlanLeg(ctx context.Context, arg InsertRoutePlanLegParams) (ItineraryRouteLeg, error)
	InsertSyncChange(ctx context.Context, arg InsertSyncChangeParams) error
	InsertTodoItem(ctx context.Context, arg InsertTodoItemParams) (TodoItem, error)
	InsertTrip(ctx context.Context, arg InsertTripParams) (Trip, error)
	InsertTripDeletionJob(ctx context.Context, arg InsertTripDeletionJobParams) (DeletionJob, error)
	InsertTripMember(ctx context.Context, arg InsertTripMemberParams) (TripMember, error)
	InsertTripShare(ctx context.Context, arg InsertTripShareParams) (TripShare, error)
	// 邮箱验证码挑战。
	InvalidateChallenges(ctx context.Context, arg InvalidateChallengesParams) error
	InvalidateRouteSummary(ctx context.Context, arg InvalidateRouteSummaryParams) (TripRouteSummary, error)
	ItineraryItemIDExists(ctx context.Context, arg ItineraryItemIDExistsParams) (*bool, error)
	LatestChallengeCreatedAt(ctx context.Context, arg LatestChallengeCreatedAtParams) (time.Time, error)
	// 每个有效分类以及仍被本旅行有效账目引用的已删除分类；筛选范围的金额与整趟的金额分别聚合。
	LedgerCategoryTotals(ctx context.Context, arg LedgerCategoryTotalsParams) ([]LedgerCategoryTotalsRow, error)
	// 每日明细：只含有账目的日期，按日期降序，游标取更早的日期。
	LedgerDailyTotals(ctx context.Context, arg LedgerDailyTotalsParams) ([]LedgerDailyTotalsRow, error)
	LedgerEntryIDExists(ctx context.Context, arg LedgerEntryIDExistsParams) (*bool, error)
	// 统计（数据库设计 §5）：净额用 CASE 聚合，按实际 occurred_on；支出与退款都取「我」的份额 personal_amount；下面四条在同一个只读一致性事务中执行。
	LedgerFilteredTotals(ctx context.Context, arg LedgerFilteredTotalsParams) (LedgerFilteredTotalsRow, error)
	LedgerTripTotals(ctx context.Context, arg LedgerTripTotalsParams) (LedgerTripTotalsRow, error)
	ListActiveSessions(ctx context.Context, arg ListActiveSessionsParams) ([]AccountSession, error)
	ListExpenseCategories(ctx context.Context, accountID uuid.UUID) ([]ExpenseCategory, error)
	// 列表：接口设计 3.9 ItineraryFilters；游标用行比较走 (account_id, trip_id, scheduled_on, sort_order, id) 部分索引。
	ListItineraryItems(ctx context.Context, arg ListItineraryItemsParams) ([]ItineraryItem, error)
	ListItineraryItemsForDays(ctx context.Context, arg ListItineraryItemsForDaysParams) ([]ItineraryItem, error)
	ListLedgerAttachments(ctx context.Context, arg ListLedgerAttachmentsParams) ([]ListLedgerAttachmentsRow, error)
	// 列表：接口设计 3.9 LedgerFilters；游标用行比较走 (account_id, trip_id, occurred_on DESC, id DESC) 部分索引。
	ListLedgerEntries(ctx context.Context, arg ListLedgerEntriesParams) ([]ListLedgerEntriesRow, error)
	ListLedgerSplits(ctx context.Context, arg ListLedgerSplitsParams) ([]ListLedgerSplitsRow, error)
	// 关联到某原支出的全部有效退款并锁定，按创建时间、id 升序。
	ListLinkedRefundsForUpdate(ctx context.Context, arg ListLinkedRefundsForUpdateParams) ([]LedgerEntry, error)
	// 列表：接口设计 3.9 PackingFilters；游标走 (account_id, trip_id, category, created_at, id) 部分索引。
	ListPackingItems(ctx context.Context, arg ListPackingItemsParams) ([]PackingItem, error)
	ListRoutePlanLegs(ctx context.Context, arg ListRoutePlanLegsParams) ([]ItineraryRouteLeg, error)
	ListRoutePlanPoints(ctx context.Context, arg ListRoutePlanPointsParams) ([]ListRoutePlanPointsRow, error)
	ListSyncChanges(ctx context.Context, arg ListSyncChangesParams) ([]SyncChange, error)
	// 列表：接口设计 3.9 TodoFilters；state 为 all/pending/completed/overdue，today 为旅行时区的今天。
	ListTodoItems(ctx context.Context, arg ListTodoItemsParams) ([]TodoItem, error)
	ListTrashedTrips(ctx context.Context, arg ListTrashedTripsParams) ([]Trip, error)
	// 列表按 (created_at, id) 降序走部分索引 assets_trip_created_idx；ids 为空数组时不过滤。
	ListTripAssets(ctx context.Context, arg ListTripAssetsParams) ([]Asset, error)
	// 票据引用校验：同账号同旅行、未删除的图片资产，状态不限。
	ListTripImageAssetIDs(ctx context.Context, arg ListTripImageAssetIDsParams) ([]uuid.UUID, error)
	// 有效成员按 sort_order、id 升序。
	ListTripMembers(ctx context.Context, arg ListTripMembersParams) ([]TripMember, error)
	// 整体保存前锁定本旅行全部有效成员。
	ListTripMembersForUpdate(ctx context.Context, arg ListTripMembersForUpdateParams) ([]TripMember, error)
	// 列表：接口设计 3.9 TripFilters。q 由应用转义 LIKE 通配符；游标用行比较走 (account_id, start_date DESC, id DESC) 索引。
	ListTripsByStartDate(ctx context.Context, arg ListTripsByStartDateParams) ([]ListTripsByStartDateRow, error)
	ListTripsByStartDateAsc(ctx context.Context, arg ListTripsByStartDateAscParams) ([]ListTripsByStartDateAscRow, error)
	ListTripsByUpdatedAt(ctx context.Context, arg ListTripsByUpdatedAtParams) ([]ListTripsByUpdatedAtRow, error)
	// 统一写事务：账号锁、变更日志、操作收据、字段级合并读取。
	LockAccountForWrite(ctx context.Context, accountID uuid.UUID) (LockAccountForWriteRow, error)
	// 校验失败：记录可公开的错误码并清空暂存键，等待用户开启新尝试。
	MarkAssetFailed(ctx context.Context, arg MarkAssetFailedParams) (Asset, error)
	// 确认：转入 processing，不再有确认窗口；暂存键保留给 worker 读取。
	MarkAssetProcessing(ctx context.Context, arg MarkAssetProcessingParams) (Asset, error)
	// 校验通过：写入最终键与实际元数据，清空暂存键（ready 的 CHECK 要求）；缩略图状态由适配器按类型传入。
	MarkAssetReady(ctx context.Context, arg MarkAssetReadyParams) (Asset, error)
	MaxExpenseCategorySortOrder(ctx context.Context, accountID uuid.UUID) (int32, error)
	MaxItinerarySortOrder(ctx context.Context, arg MaxItinerarySortOrderParams) (MaxItinerarySortOrderRow, error)
	PackingItemIDExists(ctx context.Context, arg PackingItemIDExistsParams) (*bool, error)
	PackingNameTaken(ctx context.Context, arg PackingNameTakenParams) (bool, error)
	RecordTripShareView(ctx context.Context, arg RecordTripShareViewParams) error
	ReissueSessionWithinGrace(ctx context.Context, arg ReissueSessionWithinGraceParams) error
	// 续签：只延长当前尝试的截止时间，暂存键与序号不变。
	RenewAssetAttempt(ctx context.Context, arg RenewAssetAttemptParams) (Asset, error)
	ReplaceRouteSummary(ctx context.Context, arg ReplaceRouteSummaryParams) (int64, error)
	RepositionItineraryItem(ctx context.Context, arg RepositionItineraryItemParams) (ItineraryItem, error)
	RequestTripPurge(ctx context.Context, arg RequestTripPurgeParams) (Trip, error)
	ResolveTripShareToken(ctx context.Context, token string) (ResolveTripShareTokenRow, error)
	RestoreTrip(ctx context.Context, arg RestoreTripParams) (Trip, error)
	RevokeAccountSessions(ctx context.Context, arg RevokeAccountSessionsParams) error
	RevokeOtherAccountSessions(ctx context.Context, arg RevokeOtherAccountSessionsParams) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	RotateSession(ctx context.Context, arg RotateSessionParams) error
	RotateTripShare(ctx context.Context, arg RotateTripShareParams) (TripShare, error)
	SetAccountStatus(ctx context.Context, arg SetAccountStatusParams) error
	SetAssetThumbnail(ctx context.Context, arg SetAssetThumbnailParams) (Asset, error)
	SetChallengeDelivery(ctx context.Context, arg SetChallengeDeliveryParams) error
	SetRouteSummaryCalculating(ctx context.Context, arg SetRouteSummaryCalculatingParams) error
	SetSessionReauthenticated(ctx context.Context, arg SetSessionReauthenticatedParams) error
	SetTripArchived(ctx context.Context, arg SetTripArchivedParams) (Trip, error)
	// 币种锁定与解锁：只改 currency_locked_at，递增旅行版本并返回整行作为同步快照。
	SetTripCurrencyLock(ctx context.Context, arg SetTripCurrencyLockParams) (Trip, error)
	SoftDeleteExpenseCategory(ctx context.Context, arg SoftDeleteExpenseCategoryParams) (ExpenseCategory, error)
	SoftDeleteItineraryItem(ctx context.Context, arg SoftDeleteItineraryItemParams) (ItineraryItem, error)
	SoftDeleteLedgerEntry(ctx context.Context, arg SoftDeleteLedgerEntryParams) (LedgerEntry, error)
	SoftDeletePackingItem(ctx context.Context, arg SoftDeletePackingItemParams) (PackingItem, error)
	SoftDeleteTodoItem(ctx context.Context, arg SoftDeleteTodoItemParams) (TodoItem, error)
	SoftDeleteTripMember(ctx context.Context, arg SoftDeleteTripMemberParams) (TripMember, error)
	// 新尝试：序号加 1、换暂存键与截止时间、回到 uploading 并清掉上次错误码；最终键留空由校验重写。
	StartAssetAttempt(ctx context.Context, arg StartAssetAttemptParams) (Asset, error)
	TodoItemIDExists(ctx context.Context, arg TodoItemIDExistsParams) (*bool, error)
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	TrashTrip(ctx context.Context, arg TrashTripParams) (Trip, error)
	TripHasEstimatedAmounts(ctx context.Context, arg TripHasEstimatedAmountsParams) (bool, error)
	TripHasItineraryOutside(ctx context.Context, arg TripHasItineraryOutsideParams) (bool, error)
	TripHasLocalTimes(ctx context.Context, arg TripHasLocalTimesParams) (*bool, error)
	TripIDExists(ctx context.Context, arg TripIDExistsParams) (*bool, error)
	TripMemberIDExists(ctx context.Context, arg TripMemberIDExistsParams) (*bool, error)
	// 成员结算（接口设计 3.8 TripSettlement）：每位有效成员作为付款人与参与人的支出、退款合计。
	TripMemberSettlement(ctx context.Context, arg TripMemberSettlementParams) ([]TripMemberSettlementRow, error)
	UpdateAccountPassword(ctx context.Context, arg UpdateAccountPasswordParams) error
	UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) (Account, error)
	UpdateExpenseCategory(ctx context.Context, arg UpdateExpenseCategoryParams) (ExpenseCategory, error)
	UpdateItineraryItem(ctx context.Context, arg UpdateItineraryItemParams) (ItineraryItem, error)
	UpdateLedgerEntry(ctx context.Context, arg UpdateLedgerEntryParams) (LedgerEntry, error)
	UpdatePackingItem(ctx context.Context, arg UpdatePackingItemParams) (PackingItem, error)
	UpdatePackingStatusIfVersion(ctx context.Context, arg UpdatePackingStatusIfVersionParams) (PackingItem, error)
	UpdateRouteLegMode(ctx context.Context, arg UpdateRouteLegModeParams) (ItineraryRouteLeg, error)
	UpdateTodoItem(ctx context.Context, arg UpdateTodoItemParams) (TodoItem, error)
	UpdateTrip(ctx context.Context, arg UpdateTripParams) (Trip, error)
	UpdateTripMember(ctx context.Context, arg UpdateTripMemberParams) (TripMember, error)
}

var _ Querier = (*Queries)(nil)
