// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AccountExistsByEmailKey(ctx context.Context, emailKey string) (bool, error)
	AdvanceAccountSeq(ctx context.Context, arg AdvanceAccountSeqParams) error
	ChangedFieldsBetweenVersions(ctx context.Context, arg ChangedFieldsBetweenVersionsParams) ([]ChangedFieldsBetweenVersionsRow, error)
	ConsumeChallenge(ctx context.Context, arg ConsumeChallengeParams) error
	CountChallengesSince(ctx context.Context, arg CountChallengesSinceParams) (int64, error)
	CountExpenseCategories(ctx context.Context, accountID uuid.UUID) (int64, error)
	CountLedgerEntriesUsingCategory(ctx context.Context, arg CountLedgerEntriesUsingCategoryParams) (int64, error)
	// 账号基础查询。规范化邮箱 email_key 由服务端生成（去首尾空格、小写），不在 SQL 中处理。
	// 时间一律由应用时钟给出（数据库时钟可能与应用不一致，会触发 updated_at >= created_at 约束）。
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateAccountSyncState(ctx context.Context, accountID uuid.UUID) error
	CreateChallenge(ctx context.Context, arg CreateChallengeParams) (AuthChallenge, error)
	// 登录会话。摘要列只做常量时间比较，所有查找按主键。
	CreateSession(ctx context.Context, arg CreateSessionParams) (AccountSession, error)
	DeleteExpiredChallenges(ctx context.Context, expiresAt time.Time) (int64, error)
	ExpenseCategoryIDExists(ctx context.Context, id uuid.UUID) (bool, error)
	GetAccountByEmailKey(ctx context.Context, emailKey string) (Account, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountDefaultTimezone(ctx context.Context, accountID uuid.UUID) (string, error)
	GetAccountSyncState(ctx context.Context, accountID uuid.UUID) (AccountSyncState, error)
	GetActiveTripDeletionJob(ctx context.Context, arg GetActiveTripDeletionJobParams) (DeletionJob, error)
	GetChallengeForUpdate(ctx context.Context, id uuid.UUID) (AuthChallenge, error)
	GetExpenseCategory(ctx context.Context, arg GetExpenseCategoryParams) (ExpenseCategory, error)
	GetExpenseCategoryForUpdate(ctx context.Context, arg GetExpenseCategoryForUpdateParams) (ExpenseCategory, error)
	GetMutationReceipt(ctx context.Context, arg GetMutationReceiptParams) (MutationReceipt, error)
	GetSession(ctx context.Context, id uuid.UUID) (AccountSession, error)
	GetSessionForUpdate(ctx context.Context, id uuid.UUID) (AccountSession, error)
	// 旅行与回收站。时间一律由应用时钟传入；阶段按旅行时区的“今天”在 SQL 中计算，使筛选与返回值一致。
	GetTrip(ctx context.Context, arg GetTripParams) (Trip, error)
	GetTripForUpdate(ctx context.Context, arg GetTripForUpdateParams) (Trip, error)
	IncrementChallengeAttempts(ctx context.Context, id uuid.UUID) error
	// 账号级账单分类。
	InsertExpenseCategory(ctx context.Context, arg InsertExpenseCategoryParams) (ExpenseCategory, error)
	InsertMutationReceipt(ctx context.Context, arg InsertMutationReceiptParams) error
	InsertSyncChange(ctx context.Context, arg InsertSyncChangeParams) error
	InsertTrip(ctx context.Context, arg InsertTripParams) (Trip, error)
	InsertTripDeletionJob(ctx context.Context, arg InsertTripDeletionJobParams) (DeletionJob, error)
	// 邮箱验证码挑战。
	InvalidateChallenges(ctx context.Context, arg InvalidateChallengesParams) error
	LatestChallengeCreatedAt(ctx context.Context, arg LatestChallengeCreatedAtParams) (time.Time, error)
	ListActiveSessions(ctx context.Context, arg ListActiveSessionsParams) ([]AccountSession, error)
	ListExpenseCategories(ctx context.Context, accountID uuid.UUID) ([]ExpenseCategory, error)
	ListSyncChanges(ctx context.Context, arg ListSyncChangesParams) ([]SyncChange, error)
	ListTrashedTrips(ctx context.Context, arg ListTrashedTripsParams) ([]Trip, error)
	// 列表：接口设计 3.9 TripFilters。q 由应用转义 LIKE 通配符；游标用行比较走 (account_id, start_date DESC, id DESC) 索引。
	ListTripsByStartDate(ctx context.Context, arg ListTripsByStartDateParams) ([]ListTripsByStartDateRow, error)
	ListTripsByUpdatedAt(ctx context.Context, arg ListTripsByUpdatedAtParams) ([]ListTripsByUpdatedAtRow, error)
	// 统一写事务：账号锁、变更日志、操作收据、字段级合并读取。
	LockAccountForWrite(ctx context.Context, accountID uuid.UUID) (LockAccountForWriteRow, error)
	MaxExpenseCategorySortOrder(ctx context.Context, accountID uuid.UUID) (int32, error)
	ReissueSessionWithinGrace(ctx context.Context, arg ReissueSessionWithinGraceParams) error
	RequestTripPurge(ctx context.Context, arg RequestTripPurgeParams) (Trip, error)
	RestoreTrip(ctx context.Context, arg RestoreTripParams) (Trip, error)
	RevokeAccountSessions(ctx context.Context, arg RevokeAccountSessionsParams) error
	RevokeOtherAccountSessions(ctx context.Context, arg RevokeOtherAccountSessionsParams) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	RotateSession(ctx context.Context, arg RotateSessionParams) error
	SetAccountStatus(ctx context.Context, arg SetAccountStatusParams) error
	SetChallengeDelivery(ctx context.Context, arg SetChallengeDeliveryParams) error
	SetSessionReauthenticated(ctx context.Context, arg SetSessionReauthenticatedParams) error
	SetTripArchived(ctx context.Context, arg SetTripArchivedParams) (Trip, error)
	SoftDeleteExpenseCategory(ctx context.Context, arg SoftDeleteExpenseCategoryParams) (ExpenseCategory, error)
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	TrashTrip(ctx context.Context, arg TrashTripParams) (Trip, error)
	TripHasEstimatedAmounts(ctx context.Context, arg TripHasEstimatedAmountsParams) (bool, error)
	TripHasItineraryOutside(ctx context.Context, arg TripHasItineraryOutsideParams) (bool, error)
	TripHasLocalTimes(ctx context.Context, arg TripHasLocalTimesParams) (*bool, error)
	TripIDExists(ctx context.Context, arg TripIDExistsParams) (*bool, error)
	UpdateAccountPassword(ctx context.Context, arg UpdateAccountPasswordParams) error
	UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) (Account, error)
	UpdateExpenseCategory(ctx context.Context, arg UpdateExpenseCategoryParams) (ExpenseCategory, error)
	UpdateTrip(ctx context.Context, arg UpdateTripParams) (Trip, error)
}

var _ Querier = (*Queries)(nil)
