// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteRoutePlanLegs = `-- name: DeleteRoutePlanLegs :exec
DELETE FROM itinerary_route_legs
WHERE account_id = $1 AND trip_id = $2
`

type DeleteRoutePlanLegsParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
}

func (q *Queries) DeleteRoutePlanLegs(ctx context.Context, arg DeleteRoutePlanLegsParams) error {
	_, err := q.db.Exec(ctx, deleteRoutePlanLegs, arg.AccountID, arg.TripID)
	return err
}

const getRoutePlanLegForUpdate = `-- name: GetRoutePlanLegForUpdate :one
SELECT id, account_id, trip_id, from_item_id, to_item_id, version, mode, mode_source, direct_distance_meters, route_distance_meters, route_duration_seconds, status, error_code, calculated_at, created_at, updated_at FROM itinerary_route_legs
WHERE account_id = $1 AND trip_id = $2 AND id = $3
FOR UPDATE
`

type GetRoutePlanLegForUpdateParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetRoutePlanLegForUpdate(ctx context.Context, arg GetRoutePlanLegForUpdateParams) (ItineraryRouteLeg, error) {
	row := q.db.QueryRow(ctx, getRoutePlanLegForUpdate, arg.AccountID, arg.TripID, arg.ID)
	var i ItineraryRouteLeg
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TripID,
		&i.FromItemID,
		&i.ToItemID,
		&i.Version,
		&i.Mode,
		&i.ModeSource,
		&i.DirectDistanceMeters,
		&i.RouteDistanceMeters,
		&i.RouteDurationSeconds,
		&i.Status,
		&i.ErrorCode,
		&i.CalculatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoutePlanTrip = `-- name: GetRoutePlanTrip :one

SELECT id, route_short_mode, route_short_distance_meters, deleted_at
FROM trips
WHERE account_id = $1 AND id = $2
`

type GetRoutePlanTripParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
}

type GetRoutePlanTripRow struct {
	ID                       uuid.UUID
	RouteShortMode           string
	RouteShortDistanceMeters int32
	DeletedAt                *time.Time
}

// 旅行路线偏好、相邻路段与列表汇总。
func (q *Queries) GetRoutePlanTrip(ctx context.Context, arg GetRoutePlanTripParams) (GetRoutePlanTripRow, error) {
	row := q.db.QueryRow(ctx, getRoutePlanTrip, arg.AccountID, arg.TripID)
	var i GetRoutePlanTripRow
	err := row.Scan(
		&i.ID,
		&i.RouteShortMode,
		&i.RouteShortDistanceMeters,
		&i.DeletedAt,
	)
	return i, err
}

const getRouteSummary = `-- name: GetRouteSummary :one
SELECT account_id, trip_id, revision, status, total_distance_meters, total_duration_seconds, ready_leg_count, total_leg_count, missing_point_count, calculated_at, updated_at FROM trip_route_summaries
WHERE account_id = $1 AND trip_id = $2
`

type GetRouteSummaryParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
}

func (q *Queries) GetRouteSummary(ctx context.Context, arg GetRouteSummaryParams) (TripRouteSummary, error) {
	row := q.db.QueryRow(ctx, getRouteSummary, arg.AccountID, arg.TripID)
	var i TripRouteSummary
	err := row.Scan(
		&i.AccountID,
		&i.TripID,
		&i.Revision,
		&i.Status,
		&i.TotalDistanceMeters,
		&i.TotalDurationSeconds,
		&i.ReadyLegCount,
		&i.TotalLegCount,
		&i.MissingPointCount,
		&i.CalculatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRouteSummaryForUpdate = `-- name: GetRouteSummaryForUpdate :one
SELECT account_id, trip_id, revision, status, total_distance_meters, total_duration_seconds, ready_leg_count, total_leg_count, missing_point_count, calculated_at, updated_at FROM trip_route_summaries
WHERE account_id = $1 AND trip_id = $2
FOR UPDATE
`

type GetRouteSummaryForUpdateParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
}

func (q *Queries) GetRouteSummaryForUpdate(ctx context.Context, arg GetRouteSummaryForUpdateParams) (TripRouteSummary, error) {
	row := q.db.QueryRow(ctx, getRouteSummaryForUpdate, arg.AccountID, arg.TripID)
	var i TripRouteSummary
	err := row.Scan(
		&i.AccountID,
		&i.TripID,
		&i.Revision,
		&i.Status,
		&i.TotalDistanceMeters,
		&i.TotalDurationSeconds,
		&i.ReadyLegCount,
		&i.TotalLegCount,
		&i.MissingPointCount,
		&i.CalculatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const initEmptyRouteSummary = `-- name: InitEmptyRouteSummary :exec
INSERT INTO trip_route_summaries (account_id, trip_id, revision, status, updated_at)
VALUES ($1, $2, 1, 'empty', $3)
ON CONFLICT (account_id, trip_id) DO NOTHING
`

type InitEmptyRouteSummaryParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	UpdatedAt time.Time
}

func (q *Queries) InitEmptyRouteSummary(ctx context.Context, arg InitEmptyRouteSummaryParams) error {
	_, err := q.db.Exec(ctx, initEmptyRouteSummary, arg.AccountID, arg.TripID, arg.UpdatedAt)
	return err
}

const insertRoutePlanLeg = `-- name: InsertRoutePlanLeg :one
INSERT INTO itinerary_route_legs (
    id, account_id, trip_id, from_item_id, to_item_id, version, mode, mode_source,
    direct_distance_meters, route_distance_meters, route_duration_seconds,
    status, error_code, calculated_at, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13,
    $14, $15, $16
)
RETURNING id, account_id, trip_id, from_item_id, to_item_id, version, mode, mode_source, direct_distance_meters, route_distance_meters, route_duration_seconds, status, error_code, calculated_at, created_at, updated_at
`

type InsertRoutePlanLegParams struct {
	ID                   uuid.UUID
	AccountID            uuid.UUID
	TripID               uuid.UUID
	FromItemID           uuid.UUID
	ToItemID             uuid.UUID
	Version              int64
	Mode                 string
	ModeSource           string
	DirectDistanceMeters int64
	RouteDistanceMeters  *int64
	RouteDurationSeconds *int64
	Status               string
	ErrorCode            *string
	CalculatedAt         *time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) InsertRoutePlanLeg(ctx context.Context, arg InsertRoutePlanLegParams) (ItineraryRouteLeg, error) {
	row := q.db.QueryRow(ctx, insertRoutePlanLeg,
		arg.ID,
		arg.AccountID,
		arg.TripID,
		arg.FromItemID,
		arg.ToItemID,
		arg.Version,
		arg.Mode,
		arg.ModeSource,
		arg.DirectDistanceMeters,
		arg.RouteDistanceMeters,
		arg.RouteDurationSeconds,
		arg.Status,
		arg.ErrorCode,
		arg.CalculatedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ItineraryRouteLeg
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TripID,
		&i.FromItemID,
		&i.ToItemID,
		&i.Version,
		&i.Mode,
		&i.ModeSource,
		&i.DirectDistanceMeters,
		&i.RouteDistanceMeters,
		&i.RouteDurationSeconds,
		&i.Status,
		&i.ErrorCode,
		&i.CalculatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const invalidateRouteSummary = `-- name: InvalidateRouteSummary :one
INSERT INTO trip_route_summaries (account_id, trip_id, revision, status, updated_at)
VALUES ($1, $2, 1, 'stale', $3)
ON CONFLICT (account_id, trip_id) DO UPDATE
SET revision = trip_route_summaries.revision + 1,
    status = 'stale',
    total_distance_meters = NULL,
    total_duration_seconds = NULL,
    calculated_at = NULL,
    updated_at = EXCLUDED.updated_at
RETURNING account_id, trip_id, revision, status, total_distance_meters, total_duration_seconds, ready_leg_count, total_leg_count, missing_point_count, calculated_at, updated_at
`

type InvalidateRouteSummaryParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	UpdatedAt time.Time
}

func (q *Queries) InvalidateRouteSummary(ctx context.Context, arg InvalidateRouteSummaryParams) (TripRouteSummary, error) {
	row := q.db.QueryRow(ctx, invalidateRouteSummary, arg.AccountID, arg.TripID, arg.UpdatedAt)
	var i TripRouteSummary
	err := row.Scan(
		&i.AccountID,
		&i.TripID,
		&i.Revision,
		&i.Status,
		&i.TotalDistanceMeters,
		&i.TotalDurationSeconds,
		&i.ReadyLegCount,
		&i.TotalLegCount,
		&i.MissingPointCount,
		&i.CalculatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoutePlanLegs = `-- name: ListRoutePlanLegs :many
SELECT id, account_id, trip_id, from_item_id, to_item_id, version, mode, mode_source,
       direct_distance_meters, route_distance_meters, route_duration_seconds,
       status, error_code, calculated_at, created_at, updated_at
FROM itinerary_route_legs
WHERE account_id = $1 AND trip_id = $2
ORDER BY created_at, id
`

type ListRoutePlanLegsParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
}

func (q *Queries) ListRoutePlanLegs(ctx context.Context, arg ListRoutePlanLegsParams) ([]ItineraryRouteLeg, error) {
	rows, err := q.db.Query(ctx, listRoutePlanLegs, arg.AccountID, arg.TripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItineraryRouteLeg{}
	for rows.Next() {
		var i ItineraryRouteLeg
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TripID,
			&i.FromItemID,
			&i.ToItemID,
			&i.Version,
			&i.Mode,
			&i.ModeSource,
			&i.DirectDistanceMeters,
			&i.RouteDistanceMeters,
			&i.RouteDurationSeconds,
			&i.Status,
			&i.ErrorCode,
			&i.CalculatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutePlanPoints = `-- name: ListRoutePlanPoints :many
SELECT id, title, scheduled_on, sort_order, latitude, longitude
FROM itinerary_items
WHERE account_id = $1 AND trip_id = $2 AND deleted_at IS NULL
ORDER BY scheduled_on, sort_order, id
`

type ListRoutePlanPointsParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
}

type ListRoutePlanPointsRow struct {
	ID          uuid.UUID
	Title       string
	ScheduledOn time.Time
	SortOrder   int32
	Latitude    *string
	Longitude   *string
}

func (q *Queries) ListRoutePlanPoints(ctx context.Context, arg ListRoutePlanPointsParams) ([]ListRoutePlanPointsRow, error) {
	rows, err := q.db.Query(ctx, listRoutePlanPoints, arg.AccountID, arg.TripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoutePlanPointsRow{}
	for rows.Next() {
		var i ListRoutePlanPointsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ScheduledOn,
			&i.SortOrder,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceRouteSummary = `-- name: ReplaceRouteSummary :execrows
UPDATE trip_route_summaries
SET status = $1,
    total_distance_meters = $2,
    total_duration_seconds = $3,
    ready_leg_count = $4,
    total_leg_count = $5,
    missing_point_count = $6,
    calculated_at = $7,
    updated_at = $8
WHERE account_id = $9 AND trip_id = $10 AND revision = $11
`

type ReplaceRouteSummaryParams struct {
	Status               string
	TotalDistanceMeters  *int64
	TotalDurationSeconds *int64
	ReadyLegCount        int32
	TotalLegCount        int32
	MissingPointCount    int32
	CalculatedAt         *time.Time
	UpdatedAt            time.Time
	AccountID            uuid.UUID
	TripID               uuid.UUID
	Revision             int64
}

func (q *Queries) ReplaceRouteSummary(ctx context.Context, arg ReplaceRouteSummaryParams) (int64, error) {
	result, err := q.db.Exec(ctx, replaceRouteSummary,
		arg.Status,
		arg.TotalDistanceMeters,
		arg.TotalDurationSeconds,
		arg.ReadyLegCount,
		arg.TotalLegCount,
		arg.MissingPointCount,
		arg.CalculatedAt,
		arg.UpdatedAt,
		arg.AccountID,
		arg.TripID,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setRouteSummaryCalculating = `-- name: SetRouteSummaryCalculating :exec
UPDATE trip_route_summaries
SET status = 'calculating', updated_at = $1
WHERE account_id = $2 AND trip_id = $3 AND revision = $4
`

type SetRouteSummaryCalculatingParams struct {
	UpdatedAt time.Time
	AccountID uuid.UUID
	TripID    uuid.UUID
	Revision  int64
}

func (q *Queries) SetRouteSummaryCalculating(ctx context.Context, arg SetRouteSummaryCalculatingParams) error {
	_, err := q.db.Exec(ctx, setRouteSummaryCalculating,
		arg.UpdatedAt,
		arg.AccountID,
		arg.TripID,
		arg.Revision,
	)
	return err
}

const updateRouteLegMode = `-- name: UpdateRouteLegMode :one
UPDATE itinerary_route_legs
SET mode = $1, mode_source = $2, status = 'stale',
    route_distance_meters = NULL, route_duration_seconds = NULL,
    error_code = NULL, calculated_at = NULL, version = version + 1, updated_at = $3
WHERE account_id = $4 AND trip_id = $5 AND id = $6
RETURNING id, account_id, trip_id, from_item_id, to_item_id, version, mode, mode_source, direct_distance_meters, route_distance_meters, route_duration_seconds, status, error_code, calculated_at, created_at, updated_at
`

type UpdateRouteLegModeParams struct {
	Mode       string
	ModeSource string
	UpdatedAt  time.Time
	AccountID  uuid.UUID
	TripID     uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) UpdateRouteLegMode(ctx context.Context, arg UpdateRouteLegModeParams) (ItineraryRouteLeg, error) {
	row := q.db.QueryRow(ctx, updateRouteLegMode,
		arg.Mode,
		arg.ModeSource,
		arg.UpdatedAt,
		arg.AccountID,
		arg.TripID,
		arg.ID,
	)
	var i ItineraryRouteLeg
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TripID,
		&i.FromItemID,
		&i.ToItemID,
		&i.Version,
		&i.Mode,
		&i.ModeSource,
		&i.DirectDistanceMeters,
		&i.RouteDistanceMeters,
		&i.RouteDurationSeconds,
		&i.Status,
		&i.ErrorCode,
		&i.CalculatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
