// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one

INSERT INTO account_sessions (id, account_id, client_kind, device_id, device_name, refresh_token_hash, csrf_token_hash, expires_at, created_at, last_seen_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $9)
RETURNING id, account_id, client_kind, device_id, device_name, refresh_token_hash, previous_refresh_token_hash, previous_rotated_at, csrf_token_hash, reauthenticated_at, created_at, last_seen_at, expires_at, revoked_at
`

type CreateSessionParams struct {
	ID               uuid.UUID
	AccountID        uuid.UUID
	ClientKind       string
	DeviceID         uuid.UUID
	DeviceName       *string
	RefreshTokenHash []byte
	CsrfTokenHash    []byte
	ExpiresAt        time.Time
	CreatedAt        time.Time
}

// 登录会话。摘要列只做常量时间比较，所有查找按主键。
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AccountSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.AccountID,
		arg.ClientKind,
		arg.DeviceID,
		arg.DeviceName,
		arg.RefreshTokenHash,
		arg.CsrfTokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i AccountSession
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ClientKind,
		&i.DeviceID,
		&i.DeviceName,
		&i.RefreshTokenHash,
		&i.PreviousRefreshTokenHash,
		&i.PreviousRotatedAt,
		&i.CsrfTokenHash,
		&i.ReauthenticatedAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, account_id, client_kind, device_id, device_name, refresh_token_hash, previous_refresh_token_hash, previous_rotated_at, csrf_token_hash, reauthenticated_at, created_at, last_seen_at, expires_at, revoked_at FROM account_sessions
WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (AccountSession, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i AccountSession
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ClientKind,
		&i.DeviceID,
		&i.DeviceName,
		&i.RefreshTokenHash,
		&i.PreviousRefreshTokenHash,
		&i.PreviousRotatedAt,
		&i.CsrfTokenHash,
		&i.ReauthenticatedAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionForUpdate = `-- name: GetSessionForUpdate :one
SELECT id, account_id, client_kind, device_id, device_name, refresh_token_hash, previous_refresh_token_hash, previous_rotated_at, csrf_token_hash, reauthenticated_at, created_at, last_seen_at, expires_at, revoked_at FROM account_sessions
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetSessionForUpdate(ctx context.Context, id uuid.UUID) (AccountSession, error) {
	row := q.db.QueryRow(ctx, getSessionForUpdate, id)
	var i AccountSession
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ClientKind,
		&i.DeviceID,
		&i.DeviceName,
		&i.RefreshTokenHash,
		&i.PreviousRefreshTokenHash,
		&i.PreviousRotatedAt,
		&i.CsrfTokenHash,
		&i.ReauthenticatedAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionWithAccount = `-- name: GetSessionWithAccount :one
SELECT s.id, s.account_id, s.client_kind, s.device_id, s.device_name, s.refresh_token_hash, s.previous_refresh_token_hash, s.previous_rotated_at, s.csrf_token_hash, s.reauthenticated_at, s.created_at, s.last_seen_at, s.expires_at, s.revoked_at, a.id, a.email, a.email_key, a.email_verified_at, a.password_hash, a.password_changed_at, a.nickname, a.avatar_asset_id, a.default_timezone, a.status, a.version, a.created_at, a.updated_at
FROM account_sessions s
JOIN accounts a ON a.id = s.account_id
WHERE s.id = $1
`

type GetSessionWithAccountRow struct {
	AccountSession AccountSession
	Account        Account
}

func (q *Queries) GetSessionWithAccount(ctx context.Context, id uuid.UUID) (GetSessionWithAccountRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithAccount, id)
	var i GetSessionWithAccountRow
	err := row.Scan(
		&i.AccountSession.ID,
		&i.AccountSession.AccountID,
		&i.AccountSession.ClientKind,
		&i.AccountSession.DeviceID,
		&i.AccountSession.DeviceName,
		&i.AccountSession.RefreshTokenHash,
		&i.AccountSession.PreviousRefreshTokenHash,
		&i.AccountSession.PreviousRotatedAt,
		&i.AccountSession.CsrfTokenHash,
		&i.AccountSession.ReauthenticatedAt,
		&i.AccountSession.CreatedAt,
		&i.AccountSession.LastSeenAt,
		&i.AccountSession.ExpiresAt,
		&i.AccountSession.RevokedAt,
		&i.Account.ID,
		&i.Account.Email,
		&i.Account.EmailKey,
		&i.Account.EmailVerifiedAt,
		&i.Account.PasswordHash,
		&i.Account.PasswordChangedAt,
		&i.Account.Nickname,
		&i.Account.AvatarAssetID,
		&i.Account.DefaultTimezone,
		&i.Account.Status,
		&i.Account.Version,
		&i.Account.CreatedAt,
		&i.Account.UpdatedAt,
	)
	return i, err
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT id, account_id, client_kind, device_id, device_name, refresh_token_hash, previous_refresh_token_hash, previous_rotated_at, csrf_token_hash, reauthenticated_at, created_at, last_seen_at, expires_at, revoked_at FROM account_sessions
WHERE account_id = $1 AND revoked_at IS NULL AND expires_at > $2
ORDER BY created_at DESC
`

type ListActiveSessionsParams struct {
	AccountID uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) ListActiveSessions(ctx context.Context, arg ListActiveSessionsParams) ([]AccountSession, error) {
	rows, err := q.db.Query(ctx, listActiveSessions, arg.AccountID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountSession{}
	for rows.Next() {
		var i AccountSession
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ClientKind,
			&i.DeviceID,
			&i.DeviceName,
			&i.RefreshTokenHash,
			&i.PreviousRefreshTokenHash,
			&i.PreviousRotatedAt,
			&i.CsrfTokenHash,
			&i.ReauthenticatedAt,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reissueSessionWithinGrace = `-- name: ReissueSessionWithinGrace :exec
UPDATE account_sessions
SET refresh_token_hash = $2, csrf_token_hash = $3, last_seen_at = $4
WHERE id = $1
`

type ReissueSessionWithinGraceParams struct {
	ID               uuid.UUID
	RefreshTokenHash []byte
	CsrfTokenHash    []byte
	LastSeenAt       time.Time
}

func (q *Queries) ReissueSessionWithinGrace(ctx context.Context, arg ReissueSessionWithinGraceParams) error {
	_, err := q.db.Exec(ctx, reissueSessionWithinGrace,
		arg.ID,
		arg.RefreshTokenHash,
		arg.CsrfTokenHash,
		arg.LastSeenAt,
	)
	return err
}

const revokeAccountSessions = `-- name: RevokeAccountSessions :exec
UPDATE account_sessions
SET revoked_at = $2
WHERE account_id = $1 AND revoked_at IS NULL
`

type RevokeAccountSessionsParams struct {
	AccountID uuid.UUID
	RevokedAt *time.Time
}

func (q *Queries) RevokeAccountSessions(ctx context.Context, arg RevokeAccountSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAccountSessions, arg.AccountID, arg.RevokedAt)
	return err
}

const revokeOtherAccountSessions = `-- name: RevokeOtherAccountSessions :exec
UPDATE account_sessions
SET revoked_at = $3
WHERE account_id = $1 AND id <> $2 AND revoked_at IS NULL
`

type RevokeOtherAccountSessionsParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
	RevokedAt *time.Time
}

func (q *Queries) RevokeOtherAccountSessions(ctx context.Context, arg RevokeOtherAccountSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeOtherAccountSessions, arg.AccountID, arg.ID, arg.RevokedAt)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE account_sessions
SET revoked_at = $2
WHERE id = $1 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID        uuid.UUID
	RevokedAt *time.Time
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.RevokedAt)
	return err
}

const rotateSession = `-- name: RotateSession :exec
UPDATE account_sessions
SET refresh_token_hash = $2,
    previous_refresh_token_hash = $3,
    previous_rotated_at = $4,
    csrf_token_hash = $5,
    last_seen_at = $6
WHERE id = $1
`

type RotateSessionParams struct {
	ID                       uuid.UUID
	RefreshTokenHash         []byte
	PreviousRefreshTokenHash []byte
	PreviousRotatedAt        *time.Time
	CsrfTokenHash            []byte
	LastSeenAt               time.Time
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) error {
	_, err := q.db.Exec(ctx, rotateSession,
		arg.ID,
		arg.RefreshTokenHash,
		arg.PreviousRefreshTokenHash,
		arg.PreviousRotatedAt,
		arg.CsrfTokenHash,
		arg.LastSeenAt,
	)
	return err
}

const setSessionReauthenticated = `-- name: SetSessionReauthenticated :exec
UPDATE account_sessions
SET reauthenticated_at = $2
WHERE id = $1
`

type SetSessionReauthenticatedParams struct {
	ID                uuid.UUID
	ReauthenticatedAt *time.Time
}

func (q *Queries) SetSessionReauthenticated(ctx context.Context, arg SetSessionReauthenticatedParams) error {
	_, err := q.db.Exec(ctx, setSessionReauthenticated, arg.ID, arg.ReauthenticatedAt)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE account_sessions
SET last_seen_at = $2
WHERE id = $1 AND last_seen_at < $2::timestamptz - interval '1 minute'
`

type TouchSessionParams struct {
	ID         uuid.UUID
	LastSeenAt time.Time
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.LastSeenAt)
	return err
}
