// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteTripShare = `-- name: DeleteTripShare :execrows
DELETE FROM trip_shares
WHERE account_id = $1 AND trip_id = $2
`

type DeleteTripShareParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
}

func (q *Queries) DeleteTripShare(ctx context.Context, arg DeleteTripShareParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTripShare, arg.AccountID, arg.TripID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTripShareByTrip = `-- name: GetTripShareByTrip :one

SELECT id, account_id, trip_id, token, created_at, rotated_at, last_viewed_at, view_count FROM trip_shares
WHERE account_id = $1 AND trip_id = $2
`

type GetTripShareByTripParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
}

// 旅行分享（数据库设计 v0.4 表 24）。解析查询联出主人账号状态与旅行删除标记，访客侧一次查询完成全部前置判断。
func (q *Queries) GetTripShareByTrip(ctx context.Context, arg GetTripShareByTripParams) (TripShare, error) {
	row := q.db.QueryRow(ctx, getTripShareByTrip, arg.AccountID, arg.TripID)
	var i TripShare
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TripID,
		&i.Token,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.LastViewedAt,
		&i.ViewCount,
	)
	return i, err
}

const insertTripShare = `-- name: InsertTripShare :one
INSERT INTO trip_shares (id, account_id, trip_id, token, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (account_id, trip_id) DO NOTHING
RETURNING id, account_id, trip_id, token, created_at, rotated_at, last_viewed_at, view_count
`

type InsertTripShareParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	TripID    uuid.UUID
	Token     string
	CreatedAt time.Time
}

func (q *Queries) InsertTripShare(ctx context.Context, arg InsertTripShareParams) (TripShare, error) {
	row := q.db.QueryRow(ctx, insertTripShare,
		arg.ID,
		arg.AccountID,
		arg.TripID,
		arg.Token,
		arg.CreatedAt,
	)
	var i TripShare
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TripID,
		&i.Token,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.LastViewedAt,
		&i.ViewCount,
	)
	return i, err
}

const recordTripShareView = `-- name: RecordTripShareView :exec
UPDATE trip_shares
SET view_count = view_count + 1, last_viewed_at = $1
WHERE id = $2
`

type RecordTripShareViewParams struct {
	ViewedAt *time.Time
	ID       uuid.UUID
}

func (q *Queries) RecordTripShareView(ctx context.Context, arg RecordTripShareViewParams) error {
	_, err := q.db.Exec(ctx, recordTripShareView, arg.ViewedAt, arg.ID)
	return err
}

const resolveTripShareToken = `-- name: ResolveTripShareToken :one
SELECT s.id, s.account_id, s.trip_id, s.token, s.created_at, s.rotated_at, s.last_viewed_at, s.view_count, a.status AS owner_status, t.deleted_at AS trip_deleted_at
FROM trip_shares s
JOIN accounts a ON a.id = s.account_id
JOIN trips t ON t.account_id = s.account_id AND t.id = s.trip_id
WHERE s.token = $1
`

type ResolveTripShareTokenRow struct {
	ID            uuid.UUID
	AccountID     uuid.UUID
	TripID        uuid.UUID
	Token         string
	CreatedAt     time.Time
	RotatedAt     *time.Time
	LastViewedAt  *time.Time
	ViewCount     int64
	OwnerStatus   string
	TripDeletedAt *time.Time
}

func (q *Queries) ResolveTripShareToken(ctx context.Context, token string) (ResolveTripShareTokenRow, error) {
	row := q.db.QueryRow(ctx, resolveTripShareToken, token)
	var i ResolveTripShareTokenRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TripID,
		&i.Token,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.LastViewedAt,
		&i.ViewCount,
		&i.OwnerStatus,
		&i.TripDeletedAt,
	)
	return i, err
}

const rotateTripShare = `-- name: RotateTripShare :one
UPDATE trip_shares
SET token = $1, rotated_at = $2
WHERE account_id = $3 AND trip_id = $4
RETURNING id, account_id, trip_id, token, created_at, rotated_at, last_viewed_at, view_count
`

type RotateTripShareParams struct {
	Token     string
	RotatedAt *time.Time
	AccountID uuid.UUID
	TripID    uuid.UUID
}

func (q *Queries) RotateTripShare(ctx context.Context, arg RotateTripShareParams) (TripShare, error) {
	row := q.db.QueryRow(ctx, rotateTripShare,
		arg.Token,
		arg.RotatedAt,
		arg.AccountID,
		arg.TripID,
	)
	var i TripShare
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TripID,
		&i.Token,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.LastViewedAt,
		&i.ViewCount,
	)
	return i, err
}
