// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snapshots.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const snapshotAssets = `-- name: SnapshotAssets :many
SELECT id, account_id, version, created_at, updated_at, deleted_at, scope, trip_id, original_name, status, upload_attempt, staging_object_key, expected_size, declared_media_type, client_sha256, upload_expires_at, confirmed_at, media_type, byte_size, sha256, object_key, thumbnail_object_key, thumbnail_status, width, height, exif_taken_at_local, exif_latitude, exif_longitude, error_code, unreferenced_since FROM assets WHERE account_id=$1 AND trip_id=$2 AND deleted_at IS NULL ORDER BY id
`

type SnapshotAssetsParams struct {
	AccountID uuid.UUID
	TripID    uuid.NullUUID
}

func (q *Queries) SnapshotAssets(ctx context.Context, arg SnapshotAssetsParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, snapshotAssets, arg.AccountID, arg.TripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Scope,
			&i.TripID,
			&i.OriginalName,
			&i.Status,
			&i.UploadAttempt,
			&i.StagingObjectKey,
			&i.ExpectedSize,
			&i.DeclaredMediaType,
			&i.ClientSha256,
			&i.UploadExpiresAt,
			&i.ConfirmedAt,
			&i.MediaType,
			&i.ByteSize,
			&i.Sha256,
			&i.ObjectKey,
			&i.ThumbnailObjectKey,
			&i.ThumbnailStatus,
			&i.Width,
			&i.Height,
			&i.ExifTakenAtLocal,
			&i.ExifLatitude,
			&i.ExifLongitude,
			&i.ErrorCode,
			&i.UnreferencedSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotCategories = `-- name: SnapshotCategories :many
SELECT id, account_id, version, created_at, updated_at, deleted_at, name, icon, sort_order, is_preset FROM expense_categories WHERE account_id=$1 AND deleted_at IS NULL ORDER BY id
`

func (q *Queries) SnapshotCategories(ctx context.Context, accountID uuid.UUID) ([]ExpenseCategory, error) {
	rows, err := q.db.Query(ctx, snapshotCategories, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseCategory{}
	for rows.Next() {
		var i ExpenseCategory
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.Icon,
			&i.SortOrder,
			&i.IsPreset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotDocuments = `-- name: SnapshotDocuments :many
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, title, notes, asset_id, reservation_id FROM documents WHERE account_id=$1 AND trip_id=$2 AND deleted_at IS NULL ORDER BY id
`

type SnapshotDocumentsParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
}

func (q *Queries) SnapshotDocuments(ctx context.Context, arg SnapshotDocumentsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, snapshotDocuments, arg.AccountID, arg.TripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TripID,
			&i.Title,
			&i.Notes,
			&i.AssetID,
			&i.ReservationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotItinerary = `-- name: SnapshotItinerary :many
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, title, kind, scheduled_on, sort_order, planned_start_local, planned_end_local, planned_duration_minutes, place_name, address, latitude, longitude, estimated_amount, notes, status, actual_start_local, actual_end_local, actual_notes, footprint_excluded, poi_id FROM itinerary_items WHERE account_id=$1 AND trip_id=$2 AND deleted_at IS NULL ORDER BY id
`

type SnapshotItineraryParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
}

func (q *Queries) SnapshotItinerary(ctx context.Context, arg SnapshotItineraryParams) ([]ItineraryItem, error) {
	rows, err := q.db.Query(ctx, snapshotItinerary, arg.AccountID, arg.TripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItineraryItem{}
	for rows.Next() {
		var i ItineraryItem
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TripID,
			&i.Title,
			&i.Kind,
			&i.ScheduledOn,
			&i.SortOrder,
			&i.PlannedStartLocal,
			&i.PlannedEndLocal,
			&i.PlannedDurationMinutes,
			&i.PlaceName,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.EstimatedAmount,
			&i.Notes,
			&i.Status,
			&i.ActualStartLocal,
			&i.ActualEndLocal,
			&i.ActualNotes,
			&i.FootprintExcluded,
			&i.PoiID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotLedger = `-- name: SnapshotLedger :many
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, kind, amount, category_id, occurred_on, notes, refunded_entry_id, split_count, personal_amount, payer_member_id, split_mode FROM ledger_entries WHERE account_id=$1 AND trip_id=$2 AND deleted_at IS NULL ORDER BY id
`

type SnapshotLedgerParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
}

func (q *Queries) SnapshotLedger(ctx context.Context, arg SnapshotLedgerParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, snapshotLedger, arg.AccountID, arg.TripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TripID,
			&i.Kind,
			&i.Amount,
			&i.CategoryID,
			&i.OccurredOn,
			&i.Notes,
			&i.RefundedEntryID,
			&i.SplitCount,
			&i.PersonalAmount,
			&i.PayerMemberID,
			&i.SplitMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotMembers = `-- name: SnapshotMembers :many
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, name, share_percent, sort_order, is_self FROM trip_members WHERE account_id=$1 AND trip_id=$2 AND deleted_at IS NULL ORDER BY id
`

type SnapshotMembersParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
}

func (q *Queries) SnapshotMembers(ctx context.Context, arg SnapshotMembersParams) ([]TripMember, error) {
	rows, err := q.db.Query(ctx, snapshotMembers, arg.AccountID, arg.TripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TripMember{}
	for rows.Next() {
		var i TripMember
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TripID,
			&i.Name,
			&i.SharePercent,
			&i.SortOrder,
			&i.IsSelf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotPacking = `-- name: SnapshotPacking :many
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, name, category, quantity, notes, status, sort_order FROM packing_items WHERE account_id=$1 AND trip_id=$2 AND deleted_at IS NULL ORDER BY id
`

type SnapshotPackingParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
}

func (q *Queries) SnapshotPacking(ctx context.Context, arg SnapshotPackingParams) ([]PackingItem, error) {
	rows, err := q.db.Query(ctx, snapshotPacking, arg.AccountID, arg.TripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PackingItem{}
	for rows.Next() {
		var i PackingItem
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TripID,
			&i.Name,
			&i.Category,
			&i.Quantity,
			&i.Notes,
			&i.Status,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotPhotos = `-- name: SnapshotPhotos :many
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, asset_id, taken_at_local, recorded_on, caption, sort_order, place_name, address, latitude, longitude FROM photos WHERE account_id=$1 AND trip_id=$2 AND deleted_at IS NULL ORDER BY id
`

type SnapshotPhotosParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
}

func (q *Queries) SnapshotPhotos(ctx context.Context, arg SnapshotPhotosParams) ([]Photo, error) {
	rows, err := q.db.Query(ctx, snapshotPhotos, arg.AccountID, arg.TripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TripID,
			&i.AssetID,
			&i.TakenAtLocal,
			&i.RecordedOn,
			&i.Caption,
			&i.SortOrder,
			&i.PlaceName,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotReservations = `-- name: SnapshotReservations :many
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, kind, title, booking_reference, transport_number, provider_name, start_local, end_local, origin, destination, address, contact_name, contact_phone, notes FROM reservations WHERE account_id=$1 AND trip_id=$2 AND deleted_at IS NULL ORDER BY id
`

type SnapshotReservationsParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
}

func (q *Queries) SnapshotReservations(ctx context.Context, arg SnapshotReservationsParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, snapshotReservations, arg.AccountID, arg.TripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TripID,
			&i.Kind,
			&i.Title,
			&i.BookingReference,
			&i.TransportNumber,
			&i.ProviderName,
			&i.StartLocal,
			&i.EndLocal,
			&i.Origin,
			&i.Destination,
			&i.Address,
			&i.ContactName,
			&i.ContactPhone,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotTodos = `-- name: SnapshotTodos :many
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, title, due_on, notes, completed_at, sort_order FROM todo_items WHERE account_id=$1 AND trip_id=$2 AND deleted_at IS NULL ORDER BY id
`

type SnapshotTodosParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
}

func (q *Queries) SnapshotTodos(ctx context.Context, arg SnapshotTodosParams) ([]TodoItem, error) {
	rows, err := q.db.Query(ctx, snapshotTodos, arg.AccountID, arg.TripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoItem{}
	for rows.Next() {
		var i TodoItem
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TripID,
			&i.Title,
			&i.DueOn,
			&i.Notes,
			&i.CompletedAt,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotTrips = `-- name: SnapshotTrips :many

SELECT id, account_id, version, created_at, updated_at, deleted_at, name, start_date, end_date, destination, notes, timezone, currency_code, currency_locked_at, budget_amount, archived_at, purge_after_at, purge_requested_at, route_short_mode, route_short_distance_meters FROM trips WHERE account_id=$1 AND purge_requested_at IS NULL ORDER BY id
`

// Snapshot reads all share the builder's single REPEATABLE READ transaction.
func (q *Queries) SnapshotTrips(ctx context.Context, accountID uuid.UUID) ([]Trip, error) {
	rows, err := q.db.Query(ctx, snapshotTrips, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trip{}
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.Destination,
			&i.Notes,
			&i.Timezone,
			&i.CurrencyCode,
			&i.CurrencyLockedAt,
			&i.BudgetAmount,
			&i.ArchivedAt,
			&i.PurgeAfterAt,
			&i.PurgeRequestedAt,
			&i.RouteShortMode,
			&i.RouteShortDistanceMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
