// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const advanceAccountSeq = `-- name: AdvanceAccountSeq :exec
UPDATE account_sync_state
SET last_seq = $2, updated_at = $3
WHERE account_id = $1
`

type AdvanceAccountSeqParams struct {
	AccountID uuid.UUID
	LastSeq   int64
	UpdatedAt time.Time
}

func (q *Queries) AdvanceAccountSeq(ctx context.Context, arg AdvanceAccountSeqParams) error {
	_, err := q.db.Exec(ctx, advanceAccountSeq, arg.AccountID, arg.LastSeq, arg.UpdatedAt)
	return err
}

const changedFieldsBetweenVersions = `-- name: ChangedFieldsBetweenVersions :many
SELECT entity_version, changed_fields
FROM sync_changes
WHERE account_id = $1 AND entity_type = $2 AND entity_id = $3
  AND entity_version > $4 AND entity_version <= $5
  AND change_kind = 'upsert'
ORDER BY entity_version
`

type ChangedFieldsBetweenVersionsParams struct {
	AccountID       uuid.UUID
	EntityType      string
	EntityID        uuid.UUID
	EntityVersion   int64
	EntityVersion_2 int64
}

type ChangedFieldsBetweenVersionsRow struct {
	EntityVersion int64
	ChangedFields []string
}

func (q *Queries) ChangedFieldsBetweenVersions(ctx context.Context, arg ChangedFieldsBetweenVersionsParams) ([]ChangedFieldsBetweenVersionsRow, error) {
	rows, err := q.db.Query(ctx, changedFieldsBetweenVersions,
		arg.AccountID,
		arg.EntityType,
		arg.EntityID,
		arg.EntityVersion,
		arg.EntityVersion_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangedFieldsBetweenVersionsRow{}
	for rows.Next() {
		var i ChangedFieldsBetweenVersionsRow
		if err := rows.Scan(&i.EntityVersion, &i.ChangedFields); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMutationReceipt = `-- name: GetMutationReceipt :one
SELECT account_id, operation_id, operation_type, request_hash, result, created_at FROM mutation_receipts
WHERE account_id = $1 AND operation_id = $2
`

type GetMutationReceiptParams struct {
	AccountID   uuid.UUID
	OperationID uuid.UUID
}

func (q *Queries) GetMutationReceipt(ctx context.Context, arg GetMutationReceiptParams) (MutationReceipt, error) {
	row := q.db.QueryRow(ctx, getMutationReceipt, arg.AccountID, arg.OperationID)
	var i MutationReceipt
	err := row.Scan(
		&i.AccountID,
		&i.OperationID,
		&i.OperationType,
		&i.RequestHash,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const insertMutationReceipt = `-- name: InsertMutationReceipt :exec
INSERT INTO mutation_receipts (account_id, operation_id, operation_type, request_hash, result, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertMutationReceiptParams struct {
	AccountID     uuid.UUID
	OperationID   uuid.UUID
	OperationType string
	RequestHash   []byte
	Result        []byte
	CreatedAt     time.Time
}

func (q *Queries) InsertMutationReceipt(ctx context.Context, arg InsertMutationReceiptParams) error {
	_, err := q.db.Exec(ctx, insertMutationReceipt,
		arg.AccountID,
		arg.OperationID,
		arg.OperationType,
		arg.RequestHash,
		arg.Result,
		arg.CreatedAt,
	)
	return err
}

const insertSyncChange = `-- name: InsertSyncChange :exec
INSERT INTO sync_changes (
    account_id, seq, batch_id, batch_end_seq, entity_type, entity_id, trip_id,
    entity_version, change_kind, schema_version, snapshot, changed_fields, requires_snapshot, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type InsertSyncChangeParams struct {
	AccountID        uuid.UUID
	Seq              int64
	BatchID          uuid.UUID
	BatchEndSeq      int64
	EntityType       string
	EntityID         uuid.UUID
	TripID           uuid.NullUUID
	EntityVersion    int64
	ChangeKind       string
	SchemaVersion    int16
	Snapshot         []byte
	ChangedFields    []string
	RequiresSnapshot bool
	CreatedAt        time.Time
}

func (q *Queries) InsertSyncChange(ctx context.Context, arg InsertSyncChangeParams) error {
	_, err := q.db.Exec(ctx, insertSyncChange,
		arg.AccountID,
		arg.Seq,
		arg.BatchID,
		arg.BatchEndSeq,
		arg.EntityType,
		arg.EntityID,
		arg.TripID,
		arg.EntityVersion,
		arg.ChangeKind,
		arg.SchemaVersion,
		arg.Snapshot,
		arg.ChangedFields,
		arg.RequiresSnapshot,
		arg.CreatedAt,
	)
	return err
}

const listSyncChanges = `-- name: ListSyncChanges :many
SELECT account_id, seq, batch_id, batch_end_seq, entity_type, entity_id, trip_id, entity_version, change_kind, schema_version, snapshot, changed_fields, requires_snapshot, created_at FROM sync_changes
WHERE account_id = $1 AND seq > $2 AND seq <= $3
ORDER BY seq
LIMIT $4
`

type ListSyncChangesParams struct {
	AccountID uuid.UUID
	Seq       int64
	Seq_2     int64
	Limit     int32
}

func (q *Queries) ListSyncChanges(ctx context.Context, arg ListSyncChangesParams) ([]SyncChange, error) {
	rows, err := q.db.Query(ctx, listSyncChanges,
		arg.AccountID,
		arg.Seq,
		arg.Seq_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncChange{}
	for rows.Next() {
		var i SyncChange
		if err := rows.Scan(
			&i.AccountID,
			&i.Seq,
			&i.BatchID,
			&i.BatchEndSeq,
			&i.EntityType,
			&i.EntityID,
			&i.TripID,
			&i.EntityVersion,
			&i.ChangeKind,
			&i.SchemaVersion,
			&i.Snapshot,
			&i.ChangedFields,
			&i.RequiresSnapshot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccountForWrite = `-- name: LockAccountForWrite :one

SELECT s.last_seq, a.status
FROM account_sync_state s
JOIN accounts a ON a.id = s.account_id
WHERE s.account_id = $1
FOR UPDATE OF s
`

type LockAccountForWriteRow struct {
	LastSeq int64
	Status  string
}

// 统一写事务：账号锁、变更日志、操作收据、字段级合并读取。
func (q *Queries) LockAccountForWrite(ctx context.Context, accountID uuid.UUID) (LockAccountForWriteRow, error) {
	row := q.db.QueryRow(ctx, lockAccountForWrite, accountID)
	var i LockAccountForWriteRow
	err := row.Scan(&i.LastSeq, &i.Status)
	return i, err
}
