// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todo.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getTodoItem = `-- name: GetTodoItem :one

SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, title, due_on, notes, completed_at FROM todo_items
WHERE account_id = $1 AND trip_id = $2 AND id = $3
`

type GetTodoItemParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	ID        uuid.UUID
}

// 待办（数据库设计表 7）。逾期不落列，按应用传入的旅行时区“今天”在 SQL 中筛选；空截止日期用哨兵排在最后，与索引表达式一致。
func (q *Queries) GetTodoItem(ctx context.Context, arg GetTodoItemParams) (TodoItem, error) {
	row := q.db.QueryRow(ctx, getTodoItem, arg.AccountID, arg.TripID, arg.ID)
	var i TodoItem
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Title,
		&i.DueOn,
		&i.Notes,
		&i.CompletedAt,
	)
	return i, err
}

const getTodoItemForUpdate = `-- name: GetTodoItemForUpdate :one
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, title, due_on, notes, completed_at FROM todo_items
WHERE account_id = $1 AND trip_id = $2 AND id = $3
FOR UPDATE
`

type GetTodoItemForUpdateParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetTodoItemForUpdate(ctx context.Context, arg GetTodoItemForUpdateParams) (TodoItem, error) {
	row := q.db.QueryRow(ctx, getTodoItemForUpdate, arg.AccountID, arg.TripID, arg.ID)
	var i TodoItem
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Title,
		&i.DueOn,
		&i.Notes,
		&i.CompletedAt,
	)
	return i, err
}

const insertTodoItem = `-- name: InsertTodoItem :one
INSERT INTO todo_items (id, account_id, trip_id, title, due_on, notes, completed_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $8)
RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, title, due_on, notes, completed_at
`

type InsertTodoItemParams struct {
	ID          uuid.UUID
	AccountID   uuid.UUID
	TripID      uuid.UUID
	Title       string
	DueOn       *time.Time
	Notes       string
	CompletedAt *time.Time
	CreatedAt   time.Time
}

func (q *Queries) InsertTodoItem(ctx context.Context, arg InsertTodoItemParams) (TodoItem, error) {
	row := q.db.QueryRow(ctx, insertTodoItem,
		arg.ID,
		arg.AccountID,
		arg.TripID,
		arg.Title,
		arg.DueOn,
		arg.Notes,
		arg.CompletedAt,
		arg.CreatedAt,
	)
	var i TodoItem
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Title,
		&i.DueOn,
		&i.Notes,
		&i.CompletedAt,
	)
	return i, err
}

const listTodoItems = `-- name: ListTodoItems :many
SELECT id, account_id, version, created_at, updated_at, deleted_at, trip_id, title, due_on, notes, completed_at FROM todo_items
WHERE account_id = $1 AND trip_id = $2 AND deleted_at IS NULL
  AND ($3::text = 'all'
       OR ($3::text = 'pending' AND completed_at IS NULL)
       OR ($3::text = 'completed' AND completed_at IS NOT NULL)
       OR ($3::text = 'overdue' AND completed_at IS NULL AND due_on < $4::date))
  AND ($5::date IS NULL
       OR (COALESCE(due_on, DATE '9999-12-31'), id) > ($5::date, $6::uuid))
ORDER BY COALESCE(due_on, DATE '9999-12-31'), id
LIMIT $7
`

type ListTodoItemsParams struct {
	AccountID    uuid.UUID
	TripID       uuid.UUID
	State        string
	Today        time.Time
	CursorDueKey *time.Time
	CursorID     uuid.NullUUID
	RowLimit     int32
}

// 列表：接口设计 3.9 TodoFilters；state 为 all/pending/completed/overdue，today 为旅行时区的今天。
func (q *Queries) ListTodoItems(ctx context.Context, arg ListTodoItemsParams) ([]TodoItem, error) {
	rows, err := q.db.Query(ctx, listTodoItems,
		arg.AccountID,
		arg.TripID,
		arg.State,
		arg.Today,
		arg.CursorDueKey,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoItem{}
	for rows.Next() {
		var i TodoItem
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TripID,
			&i.Title,
			&i.DueOn,
			&i.Notes,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTodoItem = `-- name: SoftDeleteTodoItem :one
UPDATE todo_items
SET deleted_at = $1, version = version + 1, updated_at = $1
WHERE account_id = $2 AND trip_id = $3 AND id = $4
RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, title, due_on, notes, completed_at
`

type SoftDeleteTodoItemParams struct {
	DeletedAt *time.Time
	AccountID uuid.UUID
	TripID    uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteTodoItem(ctx context.Context, arg SoftDeleteTodoItemParams) (TodoItem, error) {
	row := q.db.QueryRow(ctx, softDeleteTodoItem,
		arg.DeletedAt,
		arg.AccountID,
		arg.TripID,
		arg.ID,
	)
	var i TodoItem
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Title,
		&i.DueOn,
		&i.Notes,
		&i.CompletedAt,
	)
	return i, err
}

const todoItemIDExists = `-- name: TodoItemIDExists :one
SELECT EXISTS (SELECT 1 FROM todo_items t WHERE t.id = $1)
    OR EXISTS (SELECT 1 FROM entity_tombstones et WHERE et.account_id = $2 AND et.entity_type = 'todo' AND et.entity_id = $1) AS exists
`

type TodoItemIDExistsParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) TodoItemIDExists(ctx context.Context, arg TodoItemIDExistsParams) (*bool, error) {
	row := q.db.QueryRow(ctx, todoItemIDExists, arg.ID, arg.AccountID)
	var exists *bool
	err := row.Scan(&exists)
	return exists, err
}

const updateTodoItem = `-- name: UpdateTodoItem :one
UPDATE todo_items
SET title = $1, due_on = $2, notes = $3, completed_at = $4,
    version = version + 1, updated_at = $5
WHERE account_id = $6 AND trip_id = $7 AND id = $8
RETURNING id, account_id, version, created_at, updated_at, deleted_at, trip_id, title, due_on, notes, completed_at
`

type UpdateTodoItemParams struct {
	Title       string
	DueOn       *time.Time
	Notes       string
	CompletedAt *time.Time
	UpdatedAt   time.Time
	AccountID   uuid.UUID
	TripID      uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) UpdateTodoItem(ctx context.Context, arg UpdateTodoItemParams) (TodoItem, error) {
	row := q.db.QueryRow(ctx, updateTodoItem,
		arg.Title,
		arg.DueOn,
		arg.Notes,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.AccountID,
		arg.TripID,
		arg.ID,
	)
	var i TodoItem
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TripID,
		&i.Title,
		&i.DueOn,
		&i.Notes,
		&i.CompletedAt,
	)
	return i, err
}
