// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trips.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getAccountDefaultTimezone = `-- name: GetAccountDefaultTimezone :one
SELECT default_timezone FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountDefaultTimezone(ctx context.Context, accountID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getAccountDefaultTimezone, accountID)
	var default_timezone string
	err := row.Scan(&default_timezone)
	return default_timezone, err
}

const getActiveTripDeletionJob = `-- name: GetActiveTripDeletionJob :one
SELECT id, owner_account_id, scope, target_trip_id, status, stage, processed_items, total_items, receipt_token_hash, receipt_expires_at, error_code, created_at, started_at, finished_at, retain_until FROM deletion_jobs
WHERE owner_account_id = $1 AND target_trip_id = $2
  AND scope = 'trip' AND status IN ('queued', 'running', 'failed')
`

type GetActiveTripDeletionJobParams struct {
	AccountID uuid.UUID
	TripID    uuid.NullUUID
}

func (q *Queries) GetActiveTripDeletionJob(ctx context.Context, arg GetActiveTripDeletionJobParams) (DeletionJob, error) {
	row := q.db.QueryRow(ctx, getActiveTripDeletionJob, arg.AccountID, arg.TripID)
	var i DeletionJob
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.Scope,
		&i.TargetTripID,
		&i.Status,
		&i.Stage,
		&i.ProcessedItems,
		&i.TotalItems,
		&i.ReceiptTokenHash,
		&i.ReceiptExpiresAt,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.RetainUntil,
	)
	return i, err
}

const getTrip = `-- name: GetTrip :one

SELECT id, account_id, version, created_at, updated_at, deleted_at, name, start_date, end_date, destination, notes, timezone, currency_code, currency_locked_at, budget_amount, archived_at, purge_after_at, purge_requested_at FROM trips
WHERE account_id = $1 AND id = $2
`

type GetTripParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

// 旅行与回收站。时间一律由应用时钟传入；阶段按旅行时区的“今天”在 SQL 中计算，使筛选与返回值一致。
func (q *Queries) GetTrip(ctx context.Context, arg GetTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, getTrip, arg.AccountID, arg.ID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Destination,
		&i.Notes,
		&i.Timezone,
		&i.CurrencyCode,
		&i.CurrencyLockedAt,
		&i.BudgetAmount,
		&i.ArchivedAt,
		&i.PurgeAfterAt,
		&i.PurgeRequestedAt,
	)
	return i, err
}

const getTripForUpdate = `-- name: GetTripForUpdate :one
SELECT id, account_id, version, created_at, updated_at, deleted_at, name, start_date, end_date, destination, notes, timezone, currency_code, currency_locked_at, budget_amount, archived_at, purge_after_at, purge_requested_at FROM trips
WHERE account_id = $1 AND id = $2
FOR UPDATE
`

type GetTripForUpdateParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetTripForUpdate(ctx context.Context, arg GetTripForUpdateParams) (Trip, error) {
	row := q.db.QueryRow(ctx, getTripForUpdate, arg.AccountID, arg.ID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Destination,
		&i.Notes,
		&i.Timezone,
		&i.CurrencyCode,
		&i.CurrencyLockedAt,
		&i.BudgetAmount,
		&i.ArchivedAt,
		&i.PurgeAfterAt,
		&i.PurgeRequestedAt,
	)
	return i, err
}

const insertTrip = `-- name: InsertTrip :one
INSERT INTO trips (id, account_id, name, start_date, end_date, destination, notes, timezone, currency_code, budget_amount, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $11)
RETURNING id, account_id, version, created_at, updated_at, deleted_at, name, start_date, end_date, destination, notes, timezone, currency_code, currency_locked_at, budget_amount, archived_at, purge_after_at, purge_requested_at
`

type InsertTripParams struct {
	ID           uuid.UUID
	AccountID    uuid.UUID
	Name         string
	StartDate    time.Time
	EndDate      time.Time
	Destination  string
	Notes        string
	Timezone     string
	CurrencyCode string
	BudgetAmount *string
	CreatedAt    time.Time
}

func (q *Queries) InsertTrip(ctx context.Context, arg InsertTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, insertTrip,
		arg.ID,
		arg.AccountID,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.Destination,
		arg.Notes,
		arg.Timezone,
		arg.CurrencyCode,
		arg.BudgetAmount,
		arg.CreatedAt,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Destination,
		&i.Notes,
		&i.Timezone,
		&i.CurrencyCode,
		&i.CurrencyLockedAt,
		&i.BudgetAmount,
		&i.ArchivedAt,
		&i.PurgeAfterAt,
		&i.PurgeRequestedAt,
	)
	return i, err
}

const insertTripDeletionJob = `-- name: InsertTripDeletionJob :one
INSERT INTO deletion_jobs (id, owner_account_id, scope, target_trip_id, status, stage, created_at)
VALUES ($1, $2, 'trip', $3, $4, $5, $6)
RETURNING id, owner_account_id, scope, target_trip_id, status, stage, processed_items, total_items, receipt_token_hash, receipt_expires_at, error_code, created_at, started_at, finished_at, retain_until
`

type InsertTripDeletionJobParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	TripID    uuid.NullUUID
	Status    string
	Stage     string
	CreatedAt time.Time
}

func (q *Queries) InsertTripDeletionJob(ctx context.Context, arg InsertTripDeletionJobParams) (DeletionJob, error) {
	row := q.db.QueryRow(ctx, insertTripDeletionJob,
		arg.ID,
		arg.AccountID,
		arg.TripID,
		arg.Status,
		arg.Stage,
		arg.CreatedAt,
	)
	var i DeletionJob
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.Scope,
		&i.TargetTripID,
		&i.Status,
		&i.Stage,
		&i.ProcessedItems,
		&i.TotalItems,
		&i.ReceiptTokenHash,
		&i.ReceiptExpiresAt,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.RetainUntil,
	)
	return i, err
}

const listTrashedTrips = `-- name: ListTrashedTrips :many
SELECT id, account_id, version, created_at, updated_at, deleted_at, name, start_date, end_date, destination, notes, timezone, currency_code, currency_locked_at, budget_amount, archived_at, purge_after_at, purge_requested_at FROM trips
WHERE account_id = $1
  AND deleted_at IS NOT NULL
  AND ($2::timestamptz IS NULL
       OR (deleted_at, id) < ($2::timestamptz, $3::uuid))
ORDER BY deleted_at DESC, id DESC
LIMIT $4
`

type ListTrashedTripsParams struct {
	AccountID       uuid.UUID
	CursorDeletedAt *time.Time
	CursorID        uuid.NullUUID
	RowLimit        int32
}

func (q *Queries) ListTrashedTrips(ctx context.Context, arg ListTrashedTripsParams) ([]Trip, error) {
	rows, err := q.db.Query(ctx, listTrashedTrips,
		arg.AccountID,
		arg.CursorDeletedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trip{}
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.Destination,
			&i.Notes,
			&i.Timezone,
			&i.CurrencyCode,
			&i.CurrencyLockedAt,
			&i.BudgetAmount,
			&i.ArchivedAt,
			&i.PurgeAfterAt,
			&i.PurgeRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripsByStartDate = `-- name: ListTripsByStartDate :many
SELECT t.id, t.account_id, t.version, t.created_at, t.updated_at, t.deleted_at, t.name, t.start_date, t.end_date, t.destination, t.notes, t.timezone, t.currency_code, t.currency_locked_at, t.budget_amount, t.archived_at, t.purge_after_at, t.purge_requested_at,
       CASE
           WHEN ($1::timestamptz AT TIME ZONE t.timezone)::date < t.start_date THEN 'planned'
           WHEN ($1::timestamptz AT TIME ZONE t.timezone)::date > t.end_date THEN 'ended'
           ELSE 'ongoing'
       END::text AS phase
FROM trips t
WHERE t.account_id = $2
  AND t.deleted_at IS NULL
  AND ($3::text = 'all'
       OR ($3::text = 'true' AND t.archived_at IS NOT NULL)
       OR ($3::text = 'false' AND t.archived_at IS NULL))
  AND ($4::text IS NULL
       OR t.name ILIKE '%' || $4::text || '%'
       OR t.destination ILIKE '%' || $4::text || '%')
  AND ($5::text IS NULL
       OR ($5::text = 'planned' AND ($1::timestamptz AT TIME ZONE t.timezone)::date < t.start_date)
       OR ($5::text = 'ended' AND ($1::timestamptz AT TIME ZONE t.timezone)::date > t.end_date)
       OR ($5::text = 'ongoing' AND ($1::timestamptz AT TIME ZONE t.timezone)::date BETWEEN t.start_date AND t.end_date))
  AND ($6::date IS NULL
       OR (t.start_date, t.id) < ($6::date, $7::uuid))
ORDER BY t.start_date DESC, t.id DESC
LIMIT $8
`

type ListTripsByStartDateParams struct {
	Now             time.Time
	AccountID       uuid.UUID
	Archived        string
	Q               *string
	Phase           *string
	CursorStartDate *time.Time
	CursorID        uuid.NullUUID
	RowLimit        int32
}

type ListTripsByStartDateRow struct {
	Trip  Trip
	Phase string
}

// 列表：接口设计 3.9 TripFilters。q 由应用转义 LIKE 通配符；游标用行比较走 (account_id, start_date DESC, id DESC) 索引。
func (q *Queries) ListTripsByStartDate(ctx context.Context, arg ListTripsByStartDateParams) ([]ListTripsByStartDateRow, error) {
	rows, err := q.db.Query(ctx, listTripsByStartDate,
		arg.Now,
		arg.AccountID,
		arg.Archived,
		arg.Q,
		arg.Phase,
		arg.CursorStartDate,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTripsByStartDateRow{}
	for rows.Next() {
		var i ListTripsByStartDateRow
		if err := rows.Scan(
			&i.Trip.ID,
			&i.Trip.AccountID,
			&i.Trip.Version,
			&i.Trip.CreatedAt,
			&i.Trip.UpdatedAt,
			&i.Trip.DeletedAt,
			&i.Trip.Name,
			&i.Trip.StartDate,
			&i.Trip.EndDate,
			&i.Trip.Destination,
			&i.Trip.Notes,
			&i.Trip.Timezone,
			&i.Trip.CurrencyCode,
			&i.Trip.CurrencyLockedAt,
			&i.Trip.BudgetAmount,
			&i.Trip.ArchivedAt,
			&i.Trip.PurgeAfterAt,
			&i.Trip.PurgeRequestedAt,
			&i.Phase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripsByUpdatedAt = `-- name: ListTripsByUpdatedAt :many
SELECT t.id, t.account_id, t.version, t.created_at, t.updated_at, t.deleted_at, t.name, t.start_date, t.end_date, t.destination, t.notes, t.timezone, t.currency_code, t.currency_locked_at, t.budget_amount, t.archived_at, t.purge_after_at, t.purge_requested_at,
       CASE
           WHEN ($1::timestamptz AT TIME ZONE t.timezone)::date < t.start_date THEN 'planned'
           WHEN ($1::timestamptz AT TIME ZONE t.timezone)::date > t.end_date THEN 'ended'
           ELSE 'ongoing'
       END::text AS phase
FROM trips t
WHERE t.account_id = $2
  AND t.deleted_at IS NULL
  AND ($3::text = 'all'
       OR ($3::text = 'true' AND t.archived_at IS NOT NULL)
       OR ($3::text = 'false' AND t.archived_at IS NULL))
  AND ($4::text IS NULL
       OR t.name ILIKE '%' || $4::text || '%'
       OR t.destination ILIKE '%' || $4::text || '%')
  AND ($5::text IS NULL
       OR ($5::text = 'planned' AND ($1::timestamptz AT TIME ZONE t.timezone)::date < t.start_date)
       OR ($5::text = 'ended' AND ($1::timestamptz AT TIME ZONE t.timezone)::date > t.end_date)
       OR ($5::text = 'ongoing' AND ($1::timestamptz AT TIME ZONE t.timezone)::date BETWEEN t.start_date AND t.end_date))
  AND ($6::timestamptz IS NULL
       OR (t.updated_at, t.id) < ($6::timestamptz, $7::uuid))
ORDER BY t.updated_at DESC, t.id DESC
LIMIT $8
`

type ListTripsByUpdatedAtParams struct {
	Now             time.Time
	AccountID       uuid.UUID
	Archived        string
	Q               *string
	Phase           *string
	CursorUpdatedAt *time.Time
	CursorID        uuid.NullUUID
	RowLimit        int32
}

type ListTripsByUpdatedAtRow struct {
	Trip  Trip
	Phase string
}

func (q *Queries) ListTripsByUpdatedAt(ctx context.Context, arg ListTripsByUpdatedAtParams) ([]ListTripsByUpdatedAtRow, error) {
	rows, err := q.db.Query(ctx, listTripsByUpdatedAt,
		arg.Now,
		arg.AccountID,
		arg.Archived,
		arg.Q,
		arg.Phase,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTripsByUpdatedAtRow{}
	for rows.Next() {
		var i ListTripsByUpdatedAtRow
		if err := rows.Scan(
			&i.Trip.ID,
			&i.Trip.AccountID,
			&i.Trip.Version,
			&i.Trip.CreatedAt,
			&i.Trip.UpdatedAt,
			&i.Trip.DeletedAt,
			&i.Trip.Name,
			&i.Trip.StartDate,
			&i.Trip.EndDate,
			&i.Trip.Destination,
			&i.Trip.Notes,
			&i.Trip.Timezone,
			&i.Trip.CurrencyCode,
			&i.Trip.CurrencyLockedAt,
			&i.Trip.BudgetAmount,
			&i.Trip.ArchivedAt,
			&i.Trip.PurgeAfterAt,
			&i.Trip.PurgeRequestedAt,
			&i.Phase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestTripPurge = `-- name: RequestTripPurge :one
UPDATE trips
SET purge_requested_at = $1, version = version + 1, updated_at = $1
WHERE account_id = $2 AND id = $3
RETURNING id, account_id, version, created_at, updated_at, deleted_at, name, start_date, end_date, destination, notes, timezone, currency_code, currency_locked_at, budget_amount, archived_at, purge_after_at, purge_requested_at
`

type RequestTripPurgeParams struct {
	RequestedAt *time.Time
	AccountID   uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) RequestTripPurge(ctx context.Context, arg RequestTripPurgeParams) (Trip, error) {
	row := q.db.QueryRow(ctx, requestTripPurge, arg.RequestedAt, arg.AccountID, arg.ID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Destination,
		&i.Notes,
		&i.Timezone,
		&i.CurrencyCode,
		&i.CurrencyLockedAt,
		&i.BudgetAmount,
		&i.ArchivedAt,
		&i.PurgeAfterAt,
		&i.PurgeRequestedAt,
	)
	return i, err
}

const restoreTrip = `-- name: RestoreTrip :one
UPDATE trips
SET deleted_at = NULL, purge_after_at = NULL, version = version + 1, updated_at = $1
WHERE account_id = $2 AND id = $3
RETURNING id, account_id, version, created_at, updated_at, deleted_at, name, start_date, end_date, destination, notes, timezone, currency_code, currency_locked_at, budget_amount, archived_at, purge_after_at, purge_requested_at
`

type RestoreTripParams struct {
	UpdatedAt time.Time
	AccountID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) RestoreTrip(ctx context.Context, arg RestoreTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, restoreTrip, arg.UpdatedAt, arg.AccountID, arg.ID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Destination,
		&i.Notes,
		&i.Timezone,
		&i.CurrencyCode,
		&i.CurrencyLockedAt,
		&i.BudgetAmount,
		&i.ArchivedAt,
		&i.PurgeAfterAt,
		&i.PurgeRequestedAt,
	)
	return i, err
}

const setTripArchived = `-- name: SetTripArchived :one
UPDATE trips
SET archived_at = $1, version = version + 1, updated_at = $2
WHERE account_id = $3 AND id = $4
RETURNING id, account_id, version, created_at, updated_at, deleted_at, name, start_date, end_date, destination, notes, timezone, currency_code, currency_locked_at, budget_amount, archived_at, purge_after_at, purge_requested_at
`

type SetTripArchivedParams struct {
	ArchivedAt *time.Time
	UpdatedAt  time.Time
	AccountID  uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) SetTripArchived(ctx context.Context, arg SetTripArchivedParams) (Trip, error) {
	row := q.db.QueryRow(ctx, setTripArchived,
		arg.ArchivedAt,
		arg.UpdatedAt,
		arg.AccountID,
		arg.ID,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Destination,
		&i.Notes,
		&i.Timezone,
		&i.CurrencyCode,
		&i.CurrencyLockedAt,
		&i.BudgetAmount,
		&i.ArchivedAt,
		&i.PurgeAfterAt,
		&i.PurgeRequestedAt,
	)
	return i, err
}

const trashTrip = `-- name: TrashTrip :one
UPDATE trips
SET deleted_at = $1, purge_after_at = $2, version = version + 1, updated_at = $1
WHERE account_id = $3 AND id = $4
RETURNING id, account_id, version, created_at, updated_at, deleted_at, name, start_date, end_date, destination, notes, timezone, currency_code, currency_locked_at, budget_amount, archived_at, purge_after_at, purge_requested_at
`

type TrashTripParams struct {
	DeletedAt    *time.Time
	PurgeAfterAt *time.Time
	AccountID    uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) TrashTrip(ctx context.Context, arg TrashTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, trashTrip,
		arg.DeletedAt,
		arg.PurgeAfterAt,
		arg.AccountID,
		arg.ID,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Destination,
		&i.Notes,
		&i.Timezone,
		&i.CurrencyCode,
		&i.CurrencyLockedAt,
		&i.BudgetAmount,
		&i.ArchivedAt,
		&i.PurgeAfterAt,
		&i.PurgeRequestedAt,
	)
	return i, err
}

const tripHasEstimatedAmounts = `-- name: TripHasEstimatedAmounts :one
SELECT EXISTS (
    SELECT 1 FROM itinerary_items
    WHERE account_id = $1 AND trip_id = $2 AND deleted_at IS NULL AND estimated_amount IS NOT NULL
) AS exists
`

type TripHasEstimatedAmountsParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
}

func (q *Queries) TripHasEstimatedAmounts(ctx context.Context, arg TripHasEstimatedAmountsParams) (bool, error) {
	row := q.db.QueryRow(ctx, tripHasEstimatedAmounts, arg.AccountID, arg.TripID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const tripHasItineraryOutside = `-- name: TripHasItineraryOutside :one
SELECT EXISTS (
    SELECT 1 FROM itinerary_items
    WHERE account_id = $1 AND trip_id = $2 AND deleted_at IS NULL
      AND (scheduled_on < $3 OR scheduled_on > $4)
) AS exists
`

type TripHasItineraryOutsideParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
	StartDate time.Time
	EndDate   time.Time
}

func (q *Queries) TripHasItineraryOutside(ctx context.Context, arg TripHasItineraryOutsideParams) (bool, error) {
	row := q.db.QueryRow(ctx, tripHasItineraryOutside,
		arg.AccountID,
		arg.TripID,
		arg.StartDate,
		arg.EndDate,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const tripHasLocalTimes = `-- name: TripHasLocalTimes :one
SELECT EXISTS (
    SELECT 1 FROM itinerary_items ii
    WHERE ii.account_id = $1 AND ii.trip_id = $2 AND ii.deleted_at IS NULL
      AND (ii.planned_start_local IS NOT NULL OR ii.planned_end_local IS NOT NULL OR ii.actual_start_local IS NOT NULL OR ii.actual_end_local IS NOT NULL)
) OR EXISTS (
    SELECT 1 FROM reservations rs
    WHERE rs.account_id = $1 AND rs.trip_id = $2 AND rs.deleted_at IS NULL
      AND (rs.start_local IS NOT NULL OR rs.end_local IS NOT NULL)
) OR EXISTS (
    SELECT 1 FROM photos ph
    WHERE ph.account_id = $1 AND ph.trip_id = $2 AND ph.deleted_at IS NULL AND ph.taken_at_local IS NOT NULL
) AS exists
`

type TripHasLocalTimesParams struct {
	AccountID uuid.UUID
	TripID    uuid.UUID
}

func (q *Queries) TripHasLocalTimes(ctx context.Context, arg TripHasLocalTimesParams) (*bool, error) {
	row := q.db.QueryRow(ctx, tripHasLocalTimes, arg.AccountID, arg.TripID)
	var exists *bool
	err := row.Scan(&exists)
	return exists, err
}

const tripIDExists = `-- name: TripIDExists :one
SELECT EXISTS (SELECT 1 FROM trips t WHERE t.id = $1)
    OR EXISTS (SELECT 1 FROM entity_tombstones et WHERE et.account_id = $2 AND et.entity_type = 'trip' AND et.entity_id = $1) AS exists
`

type TripIDExistsParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) TripIDExists(ctx context.Context, arg TripIDExistsParams) (*bool, error) {
	row := q.db.QueryRow(ctx, tripIDExists, arg.ID, arg.AccountID)
	var exists *bool
	err := row.Scan(&exists)
	return exists, err
}

const updateTrip = `-- name: UpdateTrip :one
UPDATE trips
SET name = $1, start_date = $2, end_date = $3, destination = $4,
    notes = $5, timezone = $6, currency_code = $7, budget_amount = $8,
    version = version + 1, updated_at = $9
WHERE account_id = $10 AND id = $11
RETURNING id, account_id, version, created_at, updated_at, deleted_at, name, start_date, end_date, destination, notes, timezone, currency_code, currency_locked_at, budget_amount, archived_at, purge_after_at, purge_requested_at
`

type UpdateTripParams struct {
	Name         string
	StartDate    time.Time
	EndDate      time.Time
	Destination  string
	Notes        string
	Timezone     string
	CurrencyCode string
	BudgetAmount *string
	UpdatedAt    time.Time
	AccountID    uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) UpdateTrip(ctx context.Context, arg UpdateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, updateTrip,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.Destination,
		arg.Notes,
		arg.Timezone,
		arg.CurrencyCode,
		arg.BudgetAmount,
		arg.UpdatedAt,
		arg.AccountID,
		arg.ID,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Destination,
		&i.Notes,
		&i.Timezone,
		&i.CurrencyCode,
		&i.CurrencyLockedAt,
		&i.BudgetAmount,
		&i.ArchivedAt,
		&i.PurgeAfterAt,
		&i.PurgeRequestedAt,
	)
	return i, err
}
