import {
  Baby,
  Bath,
  BedDouble,
  Beer,
  Bike,
  BusFront,
  Camera,
  Car,
  CircleEllipsis,
  Coffee,
  CupSoda,
  Dumbbell,
  FerrisWheel,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  HandCoins,
  HeartPulse,
  IceCreamCone,
  Landmark,
  Mountain,
  Music,
  Palette,
  ParkingCircle,
  PawPrint,
  Pill,
  Plane,
  Scissors,
  Ship,
  Shirt,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Tag,
  Tent,
  Ticket,
  TrainFront,
  Utensils,
  Waves,
} from '@lucide/vue'
import type { Component } from 'vue'

/** 图标键与 Metadata.expense_category_icons 一致；Lucide 组件由页面统一定尺寸与描边。 */
export const categoryIconVisuals: Record<string, { label: string; component: Component }> = {
  transport: { label: '交通', component: BusFront },
  lodging: { label: '住宿', component: BedDouble },
  food: { label: '美食', component: Utensils },
  attraction: { label: '景点', component: Landmark },
  shopping: { label: '购物', component: ShoppingBag },
  entertainment: { label: '娱乐', component: Sparkles },
  ticket: { label: '票券', component: Ticket },
  gift: { label: '礼物', component: Gift },
  medical: { label: '医疗', component: HeartPulse },
  other: { label: '其他', component: CircleEllipsis },
  flight: { label: '机票', component: Plane },
  train: { label: '火车', component: TrainFront },
  car: { label: '打车', component: Car },
  fuel: { label: '加油', component: Fuel },
  parking: { label: '停车', component: ParkingCircle },
  ship: { label: '船票', component: Ship },
  bike: { label: '骑行', component: Bike },
  coffee: { label: '咖啡', component: Coffee },
  drink: { label: '饮品', component: CupSoda },
  alcohol: { label: '酒水', component: Beer },
  dessert: { label: '甜品', component: IceCreamCone },
  photo: { label: '摄影', component: Camera },
  nature: { label: '山野', component: Mountain },
  beach: { label: '海滩', component: Waves },
  camping: { label: '露营', component: Tent },
  amusement: { label: '游乐', component: FerrisWheel },
  art: { label: '艺术', component: Palette },
  movie: { label: '电影', component: Film },
  music: { label: '音乐', component: Music },
  game: { label: '游戏', component: Gamepad2 },
  sport: { label: '运动', component: Dumbbell },
  spa: { label: '温泉', component: Bath },
  clothing: { label: '服饰', component: Shirt },
  beauty: { label: '美容', component: Scissors },
  phone: { label: '通讯', component: Smartphone },
  baby: { label: '母婴', component: Baby },
  pet: { label: '宠物', component: PawPrint },
  pharmacy: { label: '药品', component: Pill },
  insurance: { label: '保险', component: ShieldCheck },
  tips: { label: '小费', component: HandCoins },
}

export function categoryIconComponent(icon: string | null | undefined): Component {
  return (icon && categoryIconVisuals[icon]?.component) || Tag
}

export function categoryIconLabel(icon: string | null | undefined) {
  return icon ? (categoryIconVisuals[icon]?.label ?? icon) : '无图标'
}
